Brush::Util
using Brush::Util::TypeMap = std::map<std::type_index, T>
typedef struct Log_Stats Brush::Util::Log_stats
Logger& Brush::Util::logger
Referenced by Brush::Pop::Population< T >::load, Brush::Pop::Population< T >::save, Brush::Parameters::set_verbosity.
Rnd& Brush::Util::r
Referenced by Brush::detail::Autodiff, Brush::Var::Variation< T >::bandit_sample_op, Brush::Var::Variation< T >::bandit_sample_op_with_arg, bind_params, Brush::MAB::DummyBandit< T >::choose, Brush::MAB::LinearThompsonSamplingBandit< T >::choose, Brush::MAB::ThompsonSamplingBandit< T >::choose, Brush::Var::Variation< T >::cross, Brush::Data::Dataset::get_batch, Brush::SearchSpace::get_node_like, Brush::Data::Dataset::init, Brush::Engine< T >::init, Brush::SearchSpace::make_program, Brush::Function< NodeType::Median >::median, Brush::Pop::Population< T >::migrate, Brush::Var::SubtreeMutation::mutate, Brush::Var::Variation< T >::mutate, Brush::RandomDequeue, reverse_map, Brush::SearchSpace::sample_op, Brush::SearchSpace::sample_op, Brush::SearchSpace::sample_op_with_arg, Brush::MAB::LinearThompsonSamplingBandit< T >::sample_probs, Brush::MAB::ThompsonSamplingBandit< T >::sample_probs, Brush::SearchSpace::sample_terminal, Brush::SearchSpace::sample_terminal, Brush::Sel::Lexicase< T >::select, Brush::Sel::NSGA2< T >::select, Brush::Fitness::set_rank, Brush::Var::Variation< T >::vary, Brush::Var::Variation< T >::vary_and_update.
string Brush::Util::PBSTR
Referenced by Brush::Engine< T >::print_progress.
int Brush::Util::PBWIDTH
Referenced by Brush::Engine< T >::print_progress.
TypeMap< std::string > Brush::Util::type_names
void Brush::Util::HandleErrorThrow(string err, const char *file, int line)
prints error and throws an exception
void Brush::Util::HandleErrorNoThrow(string err, const char *file, int line)
prints error to stderr and returns
void Brush::Util::clean(ArrayXf &x)
limits node output to be between MIN_FLT and MAX_FLT
References MAX_FLT, MIN_FLT.
std::string Brush::Util::ltrim(std::string str, const std::string &chars)
Referenced by trim.
std::string Brush::Util::rtrim(std::string str, const std::string &chars)
Referenced by trim.
std::string Brush::Util::trim(std::string str, const std::string &chars)
References ltrim, rtrim.
Referenced by Brush::Data::read_csv.
vector< type_index > Brush::Util::get_dtypes(MatrixXf &X)
calculates data types for each column of X
float Brush::Util::condition_number(const MatrixXf &X)
returns true for elements of x that are infinite
returns the condition number of a matrix.
References MAX_FLT.
MatrixXf Brush::Util::corrcoef(const MatrixXf &X)
returns the pearson correlation coefficients of matrix.
References corrcoef.
Referenced by corrcoef, mean_square_corrcoef.
float Brush::Util::mean_square_corrcoef(const MatrixXf &X)
References corrcoef.
int Brush::Util::argmiddle(vector< float > &v)
returns the (first) index of the element with the middlest value in v
float Brush::Util::variance(const ArrayXf &v)
calculate variance
Referenced by Brush::Split::gain, kurtosis, pearson_correlation, Brush::Simpl::Constants_simplifier::simplify_tree, skew, slope.
float Brush::Util::skew(const ArrayXf &v)
calculate skew
References variance.
float Brush::Util::kurtosis(const ArrayXf &v)
calculate kurtosis
References variance.
float Brush::Util::covariance(const ArrayXf &x, const ArrayXf &y)
covariance of x and y
Referenced by pearson_correlation, slope.
float Brush::Util::slope(const ArrayXf &x, const ArrayXf &y)
slope of x/y
References covariance, variance.
Referenced by Brush::calc_initial_weight.
float Brush::Util::pearson_correlation(const ArrayXf &x, const ArrayXf &y)
the normalized covariance of x and y
References covariance, variance.
float Brush::Util::mad(const ArrayXf &x)
median absolute deviation
References median.
Referenced by Brush::Sel::Lexicase< T >::select.
std::string Brush::Util::ReplaceString(std::string subject, const std::string &search, const std::string &replace)
find and replace string
void Brush::Util::ReplaceStringInPlace(std::string &subject, const std::string &search, const std::string &replace)
string find and replace in place
vector< size_t > Brush::Util::mask_to_index(const ArrayXb &mask)
convert a boolean mask to an index array
Referenced by Brush::Data::Dataset::split.
tuple< vector< size_t >, vector< size_t > > Brush::Util::mask_to_indices(const ArrayXb &mask)
returns 2 indices: first where mask is true, and second where mask is false.
convert a boolean mask into true and false index arrays
bool Brush::Util::in(const V &v, const T &i)
check if element is in vector.
Referenced by Brush::Var::Variation< T >::bandit_sample_op_with_arg, Brush::SearchSpace::CreateNode, Brush::Pop::Population< T >::init, Brush::Pop::Population< T >::init, Brush::SearchSpace::sample_op_with_arg, Brush::Pop::Archive< T >::set_objectives, Brush::Sel::Selection< T >::set_type.
Scalar Brush::Util::median(const T &v)
calculate median
calculate median
Referenced by mad, Brush::Data::TimeSeries< bool >::median, Brush::Function< NodeType::Median >::median.
float Brush::Util::variance(const ArrayXf &v, float mean)
calculate variance when mean provided
vector< size_t > Brush::Util::argsort(const vector< T > &v, bool ascending=true)
return indices that sort a vector
Referenced by Brush::Eval::average_precision_score.
vector< T > Brush::Util::softmax(const vector< T > &w)
return the softmax transformation of a vector.
Referenced by Brush::Function< NodeType::Softmax >::operator().
vector< T > Brush::Util::unique(vector< T > w)
returns unique elements in vector
Referenced by Brush::Parameters::set_n_classes, unique, unique, unique.
vector< T > Brush::Util::unique(Matrix< T, -1, -1 > w)
returns unique elements in Eigen matrix of variable rows/cols
References unique.
vector< T > Brush::Util::unique(Matrix< T, -1, 1 > w)
returns unique elements in Eigen vector
References unique.
vector< T > Brush::Util::unique(Array< T, -1, 1 > w)
returns unique elements in 1d Eigen array
References unique.
string Brush::Util::to_string(const T &value)
template function to convert objects to string for logging
Referenced by bind_variation, Brush::Data::Dataset::copy_and_make_features, Brush::Pop::Population< T >::init, Brush::Pop::Population< T >::load, Brush::Eval::log_loss, Brush::Data::Dataset::make_features, Brush::Engine< T >::predict_archive, Brush::Engine< T >::predict_proba_archive, Brush::Pop::Population< T >::print_models, Brush::Fitness::repr, Brush::Fitness::toString.
Brush::Util::NLOHMANN_DEFINE_TYPE_NON_INTRUSIVE(Log_Stats, generation, time, best_score, best_score_v, med_score, med_score_v, med_size, med_complexity, max_size, max_complexity)
std::enable_if_t< std::is_scalar_v< T >, T > Brush::Util::limited(T x)
limits the output to finite real numbers
References MAX_FLT, MIN_FLT.
std::enable_if_t< std::is_base_of_v< Eigen::ArrayBase< T >, T >, T > Brush::Util::limited(T x)
References MAX_FLT, MIN_FLT.
void Brush::Util::reorder(vector< T > &v, vector< int > const &order)
array< Array< T,-1, 1 >, 2 > Brush::Util::split(const Array< T,-1, 1 > &v, const ArrayXb &mask)
split Eigen matrix or array into two by mask
void Brush::Util::print(T t)
prints comma delimited container contents.
void Brush::Util::unique_insert(Vector &v, const T &t)
unique insertion into a vector. allows a vector to be used like a set. source: http://www.lafstern.org/matt/col1.pdf
Referenced by Brush::Data::Dataset::init.
auto Brush::Util::vectorToTupleHelper(const std::vector< T > &v, std::index_sequence< Indices... >)
Referenced by vectorToTuple.
auto Brush::Util::vectorToTuple(const std::vector< T > &v)
References vectorToTupleHelper.
R Brush::Util::apply(const std::function< R(Args...)> &f, const vector< Arg > &inputs)
References HANDLE_ERROR_THROW.
std::vector< T > Brush::Util::slice(const vector< T > &v, const U &idx)
Referenced by Brush::Data::TimeSeries< bool >::operator().
static map< V, K > Brush::Util::reverse_map(const map< K, V > &m)
Given a map from keys to values, creates a new map from values to keys.
References r.
ostream & Brush::Util::operator<<(ostream &os, const vector< T > &v)