Brush::Split
ArrayXb Brush::Split::threshold_mask(const T &x, const float &threshold)
Applies a learned threshold to a feature, returning a mask.
References HANDLE_ERROR_THROW, Brush::is_one_of_v.
Referenced by threshold_mask< State >.
ArrayXb Brush::Split::threshold_mask(const T &x, const float &threshold)
Applies a learned threshold to a feature, returning a mask.
ArrayXb Brush::Split::threshold_mask(const T &x, const float &threshold)
Applies a learned threshold to a feature, returning a mask.
ArrayXb Brush::Split::threshold_mask(const T &x, const float &threshold)
Applies a learned threshold to a feature, returning a mask.
References HANDLE_ERROR_THROW.
ArrayXb Brush::Split::threshold_mask(const T &x, const float &threshold)
Applies a learned threshold to a feature, returning a mask.
ArrayXb Brush::Split::threshold_mask(const T &x, const float &threshold)
Applies a learned threshold to a feature, returning a mask.
ArrayXb Brush::Split::threshold_mask(const T &x, const float &threshold)
Applies a learned threshold to a feature, returning a mask.
References HANDLE_ERROR_THROW, Brush::is_one_of_v.
Referenced by threshold_mask< State >.
float Brush::Split::gini_impurity_index(const ArrayXf &classes, const vector< float > &uc)
Referenced by gain.
float Brush::Split::gain(const ArrayXf &lsplit, const ArrayXf &rsplit, bool classification, vector< float > unique_classes)
References gini_impurity_index, Brush::Util::variance.
vector< float > Brush::Split::get_thresholds(const T &x)
tuple< string, float > Brush::Split::get_best_variable_and_threshold(const Dataset &d, TreeNode &tn)
References get_best_thresholds.
tuple< float, float > Brush::Split::best_threshold(const T &x, const ArrayXf &y, bool classification)
void Brush::Split::get_best_threshold_by_type(const Dataset &d, auto &results)
auto Brush::Split::get_best_thresholds(const Dataset &d, std::index_sequence< Is... >)
References HANDLE_ERROR_THROW, Brush::is_std_array_v.
Referenced by get_best_variable_and_threshold.
T Brush::Split::stitch(array< T, 2 > &child_outputs, const ArrayXb &mask)
Stitches together outputs from left or right child based on threshold.
vector< float > Brush::Split::get_thresholds< ArrayXb >(const ArrayXb &x)
vector< float > Brush::Split::get_thresholds< ArrayXbJet >(const ArrayXbJet &x)
vector< float > Brush::Split::get_thresholds< ArrayXi >(const ArrayXi &x)
vector< float > Brush::Split::get_thresholds< ArrayXiJet >(const ArrayXiJet &x)
vector< float > Brush::Split::get_thresholds< ArrayXf >(const ArrayXf &x)
vector< float > Brush::Split::get_thresholds< ArrayXfJet >(const ArrayXfJet &x)
ArrayXb Brush::Split::threshold_mask< State >(const State &x, const float &threshold)
References threshold_mask.