Brush::Eval
float Brush::Eval::mse(const VectorXf &y, const VectorXf &yhat, VectorXf &loss, const vector< float > &class_weights)
mean squared error
Calculates the mean squared error between the predicted values and the true values. y The true values. yhat The predicted values. loss Reference to store the calculated losses for each sample. class_weights The optional class weights (not used for MSE). The mean squared error.
Referenced by Brush::Eval::Scorer< P >::Scorer.
VectorXf Brush::Eval::log_loss(const VectorXf &y, const VectorXf &predict_proba, const vector< float > &class_weights=vector< float >())
Calculates the log loss between the predicted probabilities and the true labels.
y The true labels. predict_proba The predicted probabilities. class_weights The optional class weights. The log loss.
References Brush::Util::to_string.
Referenced by mean_log_loss.
float Brush::Eval::mean_log_loss(const VectorXf &y, const VectorXf &predict_proba, VectorXf &loss, const vector< float > &class_weights)
log loss
Calculates the mean log loss between the predicted probabilities and the true labels. y The true labels. predict_proba The predicted probabilities. loss Reference to store the calculated losses for each sample. class_weights The optional class weights. The mean log loss.
References log_loss.
Referenced by Brush::Eval::Scorer< P >::Scorer.
float Brush::Eval::zero_one_loss(const VectorXf &y, const VectorXf &predict_proba, VectorXf &loss, const vector< float > &class_weights=vector< float >())
Accuracy for binary classification.
y The true labels. predict_proba The predicted probabilities. loss Reference to store the calculated losses for each sample. class_weights The optional class weights. The final accuracy.
Referenced by Brush::Eval::Scorer< P >::Scorer.
float Brush::Eval::bal_zero_one_loss(const VectorXf &y, const VectorXf &predict_proba, VectorXf &loss, const vector< float > &class_weights=vector< float >())
Balanced accuracy for binary classification.
y The true labels. predict_proba The predicted probabilities. loss Reference to store the calculated losses for each sample. class_weights The optional class weights. The final accuracy.
Referenced by Brush::Eval::Scorer< P >::Scorer.
float Brush::Eval::average_precision_score(const VectorXf &y, const VectorXf &predict_proba, VectorXf &loss, const vector< float > &class_weights=vector< float >())
Calculates the average precision score between the predicted probabilities and the true labels.
y The true labels. predict_proba The predicted probabilities. loss Reference to store the calculated losses for each sample. class_weights The optional class weights. The average precision score.
References Brush::Util::argsort.
Referenced by Brush::Eval::Scorer< P >::Scorer.
VectorXf Brush::Eval::multi_log_loss(const VectorXf &y, const ArrayXXf &predict_proba, const vector< float > &class_weights=vector< float >())
Calculates the multinomial log loss between the predicted probabilities and the true labels.
y The true labels. predict_proba The predicted probabilities. class_weights The optional class weights. The multinomial log loss.
Referenced by mean_multi_log_loss.
float Brush::Eval::mean_multi_log_loss(const VectorXf &y, const ArrayXXf &predict_proba, VectorXf &loss, const vector< float > &class_weights=vector< float >())
Calculates the mean multinomial log loss between the predicted probabilities and the true labels.
y The true labels. predict_proba The predicted probabilities. loss Reference to store the calculated losses for each sample. class_weights The optional class weights. The mean multinomial log loss.
References multi_log_loss.
Referenced by Brush::Eval::Scorer< P >::Scorer.
float Brush::Eval::multi_zero_one_loss(const VectorXf &y, const ArrayXXf &predict_proba, VectorXf &loss, const vector< float > &class_weights=vector< float >())
Accuracy for multi-classification.
y The true labels. predict_proba The predicted probabilities. loss Reference to store the calculated losses for each sample. class_weights The optional class weights. The average accuracy in a one-vs-all schema.
Referenced by Brush::Eval::Scorer< P >::Scorer.