Brush::Data::Dataset
vector<size_t> Brush::Data::Dataset::training_data_idx
Referenced by get_training_data, init.
vector<size_t> Brush::Data::Dataset::validation_data_idx
Referenced by get_validation_data, init.
std::vector<DataType> Brush::Data::Dataset::unique_data_types
keeps track of the unique data types in the dataset.
Referenced by init, Brush::SearchSpace::init, Brush::Simpl::Inexact_simplifier::init.
std::vector<DataType> Brush::Data::Dataset::feature_types
types of data in the features.
Referenced by init.
std::vector<string> Brush::Data::Dataset::feature_names
names of the feature types as string representations.
Referenced by copy_and_make_features, make_features.
std::unordered_map<DataType,vector<string> > Brush::Data::Dataset::features_of_type
map from data types to features having that type.
Referenced by get_feature_type, init.
std::map<string, State> Brush::Data::Dataset::features
dataset features, as key value pairs
Referenced by copy_and_make_features, Dataset, Dataset, Brush::generate_terminals, get_n_samples, init, operator(), operator[].
ArrayXf Brush::Data::Dataset::y
length N array, the target label
Referenced by bind_dataset, Dataset, Brush::Operator< NodeType::MeanLabel, S, Fit >::fit, Brush::generate_terminals, init, Brush::SearchSpace::init, operator(), Brush::Eval::Evaluation< T >::update_fitness.
bool Brush::Data::Dataset::classification
whether this is a classification problem
Referenced by Dataset, Dataset, Brush::Operator< NodeType::MeanLabel, S, Fit >::fit, Brush::generate_terminals, init, Brush::SearchSpace::init, operator().
std::optional<std::reference_wrapper<const ArrayXXf> > Brush::Data::Dataset::Xref
Referenced by Dataset, get_X.
float Brush::Data::Dataset::validation_size
percentage of original data used for train. if 0.0, then all data is used for train and validation
Referenced by Dataset, Dataset, init.
bool Brush::Data::Dataset::use_validation
Referenced by Brush::Eval::Evaluation< T >::assign_fit, Dataset, Dataset, init.
bool Brush::Data::Dataset::shuffle_split
Referenced by Dataset, Dataset, init.
float Brush::Data::Dataset::batch_size
percentage of training data size to use in each batch. if 1.0, then all data is used
Referenced by Dataset, Dataset, get_batch, get_batch_size, set_batch_size.
bool Brush::Data::Dataset::use_batch
Referenced by Dataset, Dataset, get_batch, Brush::Engine< T >::run, set_batch_size.
Dataset Brush::Data::Dataset::operator()(const vector< size_t > &idx) const
return a slice of the data using indices idx
References Brush::always_false_v, classification, Dataset, features, y.
void Brush::Data::Dataset::init()
call init at the end of constructors to define metafeatures of the data.
References classification, feature_types, features, features_of_type, get_n_samples, HANDLE_ERROR_THROW, Brush::Util::r, shuffle_split, Brush::Data::StateType, training_data_idx, unique_data_types, Brush::Util::unique_insert, use_validation, validation_data_idx, validation_size, y.
Referenced by Dataset, Dataset.
map< string, State > Brush::Data::Dataset::make_features(const ArrayXXf &X, const map< string, State > &Z={}, const vector< string > &vn={}, const vector< string > &ft={})
turns input data into a feature map
References Brush::Data::check_type, feature_names, HANDLE_ERROR_THROW, Brush::Util::to_string.
map< string, State > Brush::Data::Dataset::copy_and_make_features(const ArrayXXf &X, const Dataset &ref_dataset, const vector< string > &vn={})
turns input into a feature map, with feature types copied from a reference
References Brush::Data::cast_type, Dataset, feature_names, features, HANDLE_ERROR_THROW, Brush::Util::to_string.
Referenced by Dataset.
Brush::Data::Dataset::Dataset(std::map< string, State > &d, const Ref< const ArrayXf > &y_=ArrayXf(), bool c=false, float validation_size=0.0, float batch_size=1.0, bool shuffle_split=false)
initialize data from a map.
References batch_size, classification, features, init, shuffle_split, use_batch, use_validation, validation_size, y.
Referenced by copy_and_make_features, Dataset, get_batch, get_training_data, get_validation_data, operator().
Brush::Data::Dataset::Dataset(const ArrayXXf &X, const Ref< const ArrayXf > &y_=ArrayXf(), const vector< string > &vn={}, const map< string, State > &Z={}, const vector< string > &ft={}, bool c=false, float validation_size=0.0, float batch_size=1.0, bool shuffle_split=false)
initialize data from a matrix with feature columns.
Brush::Data::Dataset::Dataset(const ArrayXXf &X, const vector< string > &vn, const vector< string > &ft={}, bool c=false, float validation_size=0.0, float batch_size=1.0, bool shuffle_split=false)
initialize data from X and feature names
Brush::Data::Dataset::Dataset(const ArrayXXf &X, const Dataset &ref_dataset, const vector< string > &vn)
References batch_size, classification, copy_and_make_features, Dataset, features, init, shuffle_split, use_batch, use_validation, validation_size, Xref.
void Brush::Data::Dataset::print() const
References get_n_features, get_n_samples.
Referenced by bind_dataset.
auto Brush::Data::Dataset::get_X() const
References HANDLE_ERROR_THROW, Xref.
Referenced by bind_dataset.
Dataset Brush::Data::Dataset::get_training_data() const
References Dataset, training_data_idx.
Referenced by Brush::Eval::Evaluation< T >::assign_fit, bind_dataset, Brush::Simpl::Inexact_simplifier::init, Brush::Eval::Evaluation< T >::update_fitness.
Dataset Brush::Data::Dataset::get_validation_data() const
References Dataset, validation_data_idx.
Referenced by Brush::Eval::Evaluation< T >::assign_fit, bind_dataset.
int Brush::Data::Dataset::get_n_samples() const
References features.
Referenced by bind_dataset, Brush::Operator< NodeType::Constant, S, Fit >::eval, get_batch, init, Brush::Simpl::Inexact_simplifier::init, Brush::Operator< NodeType::MeanLabel, S, Fit >::predict, print.
int Brush::Data::Dataset::get_n_features() const
Referenced by bind_dataset, Brush::Operator< NodeType::Constant, S, Fit >::eval, Brush::Operator< NodeType::MeanLabel, S, Fit >::predict, print.
Dataset Brush::Data::Dataset::get_batch() const
select random subset of data for training weights.
References batch_size, Dataset, get_n_samples, Brush::Util::r, use_batch.
Referenced by bind_dataset, Brush::Engine< T >::run.
float Brush::Data::Dataset::get_batch_size()
References batch_size.
Referenced by bind_dataset.
void Brush::Data::Dataset::set_batch_size(float new_size)
References batch_size, use_batch.
Referenced by bind_dataset.
DataType Brush::Data::Dataset::get_feature_type(const string &name) const
References Brush::ArrayF, features_of_type, HANDLE_ERROR_THROW.
array< Dataset, 2 > Brush::Data::Dataset::split(const ArrayXb &mask) const
References Brush::Util::mask_to_index.
Referenced by bind_dataset.
State Brush::Data::Dataset::operator[](std::string name) const
References features, HANDLE_ERROR_THROW.