Brush::MAB::BanditOperator
using Brush::MAB::BanditOperator< T >::Iter = tree<Node>::pre_order_iterator
std::map<T, float> Brush::MAB::BanditOperator< T >::probabilities
Referenced by Brush::MAB::BanditOperator< T >::BanditOperator, Brush::MAB::BanditOperator< T >::BanditOperator, Brush::MAB::DummyBandit< T >::choose, Brush::MAB::DummyBandit< T >::sample_probs, Brush::MAB::LinearThompsonSamplingBandit< T >::sample_probs, Brush::MAB::ThompsonSamplingBandit< T >::sample_probs.
Brush::MAB::BanditOperator< T >::BanditOperator(vector< T > arms)
Constructs a BanditOperator object with a vector of arms.
arms The vector of arms.
References Brush::MAB::BanditOperator< T >::probabilities.
Referenced by Brush::MAB::DummyBandit< T >::DummyBandit, Brush::MAB::DummyBandit< T >::DummyBandit, Brush::MAB::LinearThompsonSamplingBandit< T >::LinearThompsonSamplingBandit, Brush::MAB::LinearThompsonSamplingBandit< T >::LinearThompsonSamplingBandit, Brush::MAB::ThompsonSamplingBandit< T >::ThompsonSamplingBandit, Brush::MAB::ThompsonSamplingBandit< T >::ThompsonSamplingBandit.
Brush::MAB::BanditOperator< T >::BanditOperator(map< T, float > arms_probs)
Constructs a BanditOperator object with a map of arms and their probabilities.
arms_probs The map of arms and their probabilities.
References Brush::MAB::BanditOperator< T >::probabilities.
Brush::MAB::BanditOperator< T >::~BanditOperator()
std::map< T, float > Brush::MAB::BanditOperator< T >::sample_probs(bool update)
Samples the probabilities of the arms.
update A boolean indicating whether to update the probabilities. A map of arms and their probabilities.
References Brush::MAB::BanditOperator< T >::update.
T Brush::MAB::BanditOperator< T >::choose(const VectorXf &context)
Chooses an arm based on the given tree and fitness. Should call sample_probs internally.
tree The tree structure used to choose the arm. f The fitness value used to influence the choice. The arm with highest probability.
References HANDLE_ERROR_THROW.
void Brush::MAB::BanditOperator< T >::update(T arm, float reward, VectorXf &context)
Updates the reward for a specific arm.
arm The arm for which to update the reward. reward The reward value.
Referenced by Brush::MAB::BanditOperator< T >::sample_probs.