name: brush
channels:
    - conda-forge
dependencies:
    - breathe
    - cmake #=3.18.*
    - eigen #=3.4.*
    - fmt
    - clang >= 15.0.3 # [osx]
    - clangxx >= 15.0.3 # [osx]
    - gtest #=1.10.0
    - ipython
    - jupyter
    - ninja
    - pip
    - pip:
      - graphviz
      - Maisie-Sphinx-Theme
      - pmlb
      - sphinx
    - pybind11 #=2.6.2
    - pydot
    - pytest #=6.2.4
    - python #=3.8.2
    - doxygen
    - pip
    - pip:
      - pydot
      - maisie_sphinx_theme
      - breathe
      - doxygen