name: brush
channels:
    - conda-forge
dependencies:
    - python>=3.8
    - cmake #=3.18.*
    - eigen #=3.4.*
    - fmt
    - cxx-compiler
    - ninja
    - ceres-solver=2.1.0
    - boost-cpp=1.82.0
    - pybind11>=2.6.2
    - taskflow
    - pytest #=6.2.4
    - pydot
    - scikit-learn
    - scikit-build-core
    - pandas
    # not required to install the c++ library (but used in the wrapper)
    - jupyter
    - ipython
    - pip
    - nlohmann_json
    - pybind11_json
    # Building documentation
    - doxygen
    - sphinx
    - pip:
      - graphviz
      - deap # TODO: deap optional
      - pmlb
      