name: brush
channels:
    - conda-forge
dependencies:
    - python #=3.8.2
    - cmake #=3.18.*
    - eigen #=3.4.*
    - gtest #=1.10.0
    - pybind11 #=2.6.2
    - ninja
    - pytest #=6.2.4
    - pydot
    - fmt
    - breathe
    - pip
    - pip:
      - sphinx
      - Maisie-Sphinx-Theme
      = pmlb
    # - pandas=1.1.*
    # - scikit-learn=0.23.*
    # - setuptools=45.*
    # - wheel=0.35.*
