name: brush
channels:
    - conda-forge
dependencies:
    - python=3.*
    - cmake=3.18.*
    - eigen=3.3.*
    - gtest=1.10.0
    # - pandas=1.1.*
    # - scikit-learn=0.23.*
    # - setuptools=45.*
    # - wheel=0.35.*
