#!/bin/bash

check_for_python=false
choice="n"
nobuild=false

if [ $# > 0 ] ; then 
    for var in $@ ; do
        if [ $var == "debug" ] ; then
            make -C debug -j
        elif [ $var == "lpc" ] ; then
            module load gcc/5.2.0
            export EIGEN3_INCLUDE_DIR="$HOME/eigen-3.3.4/"
        elif [ $var == "n" ] ; then
            check_for_python=false
        elif [ $var == "y" ] || [ $var == "python" ] ; then
            check_for_python=false
            choice="y"
        fi 
    done
fi

if [ $nobuild == false ] ; then
    make -C build -j 4
fi

if [ $check_for_python == true ] ; then
    read -p "Install python wrapper? (y/n) " choice
fi

if [ $choice == "y" ] ; then 
        echo "installing python module..."
        cd python
        rm -rf build 
        rm -rf dist
        python setup.py install
        cd ..
fi

echo "done"
