[build-system]
requires = [
    "setuptools>=42",
    "wheel",
    "scikit-build",
    "cmake",
    "ninja",
    "pybind11",
    "sphinx",
    "numpy",
    "maisie_sphinx_theme",
    "breathe"
]
build-backend = "setuptools.build_meta"