Operator< NT, S, Fit, enable_if_t< is_in_v< NT, NodeType::SplitOn, NodeType::SplitBest > > >
using Operator< NT, S, Fit, enable_if_t< is_in_v< NT, NodeType::SplitOn, NodeType::SplitBest > > >::ArgTypes = typename S::ArgTypes
using Operator< NT, S, Fit, enable_if_t< is_in_v< NT, NodeType::SplitOn, NodeType::SplitBest > > >::FirstArg = typename S::FirstArg
using Operator< NT, S, Fit, enable_if_t< is_in_v< NT, NodeType::SplitOn, NodeType::SplitBest > > >::RetType = typename S::RetType
using Operator< NT, S, Fit, enable_if_t< is_in_v< NT, NodeType::SplitOn, NodeType::SplitBest > > >::W = typename S::WeightType
using Operator< NT, S, Fit, enable_if_t< is_in_v< NT, NodeType::SplitOn, NodeType::SplitBest > > >::NthType = typename S::NthType<N>
size_t Operator< NT, S, Fit, enable_if_t< is_in_v< NT, NodeType::SplitOn, NodeType::SplitBest > > >::ArgCount
Function<NT> Operator< NT, S, Fit, enable_if_t< is_in_v< NT, NodeType::SplitOn, NodeType::SplitBest > > >::F
array< RetType, 2 > Operator< NT, S, Fit, enable_if_t< is_in_v< NT, NodeType::SplitOn, NodeType::SplitBest > > >::get_kids(const array< Dataset, 2 > &d, TreeNode &tn, const W **weights=nullptr) const
Referenced by predict.
RetType Operator< NT, S, Fit, enable_if_t< is_in_v< NT, NodeType::SplitOn, NodeType::SplitBest > > >::fit(const Dataset &d, TreeNode &tn) const
References Split::best_threshold, Dataset::classification, Split::get_best_variable_and_threshold, predict, Dataset::y.
Referenced by eval.
RetType Operator< NT, S, Fit, enable_if_t< is_in_v< NT, NodeType::SplitOn, NodeType::SplitBest > > >::predict(const Dataset &d, TreeNode &tn, const W **weights=nullptr) const
References get_kids, Dataset::get_n_samples, Dataset::split, Split::stitch, Split::threshold_mask.
Referenced by eval, fit.
RetType Operator< NT, S, Fit, enable_if_t< is_in_v< NT, NodeType::SplitOn, NodeType::SplitBest > > >::eval(const Dataset &d, TreeNode &tn, const W **weights=nullptr) const
References fit, predict.