Brush::TinyCostFunction
using Brush::TinyCostFunction< CostFunctor, DualType, ScalarType, StorageOrder >::Scalar = ScalarType
using Brush::TinyCostFunction< CostFunctor, DualType, ScalarType, StorageOrder >::JacobianType = Eigen::Matrix<Brush::Scalar, -1, -1>
using Brush::TinyCostFunction< CostFunctor, DualType, ScalarType, StorageOrder >::QRSolver = Eigen::ColPivHouseholderQR<JacobianType>
int Brush::TinyCostFunction< CostFunctor, DualType, ScalarType, StorageOrder >::Stride
int Brush::TinyCostFunction< CostFunctor, DualType, ScalarType, StorageOrder >::Storage
CostFunctor Brush::TinyCostFunction< CostFunctor, DualType, ScalarType, StorageOrder >::functor_
Referenced by Brush::TinyCostFunction< CostFunctor, DualType, ScalarType, StorageOrder >::Evaluate, Brush::TinyCostFunction< CostFunctor, DualType, ScalarType, StorageOrder >::NumParameters, Brush::TinyCostFunction< CostFunctor, DualType, ScalarType, StorageOrder >::NumResiduals, Brush::TinyCostFunction< CostFunctor, DualType, ScalarType, StorageOrder >::TinyCostFunction.
Brush::TinyCostFunction< CostFunctor, DualType, ScalarType, StorageOrder >::TinyCostFunction(CostFunctor const &functor)
References Brush::TinyCostFunction< CostFunctor, DualType, ScalarType, StorageOrder >::functor_.
bool Brush::TinyCostFunction< CostFunctor, DualType, ScalarType, StorageOrder >::Evaluate(Scalar const *parameters, Scalar *residuals, Scalar *jacobian) const
References Brush::detail::Autodiff, Brush::TinyCostFunction< CostFunctor, DualType, ScalarType, StorageOrder >::functor_.
Referenced by Brush::TinyCostFunction< CostFunctor, DualType, ScalarType, StorageOrder >::df, Brush::TinyCostFunction< CostFunctor, DualType, ScalarType, StorageOrder >::operator(), Brush::TinyCostFunction< CostFunctor, DualType, ScalarType, StorageOrder >::operator().
bool Brush::TinyCostFunction< CostFunctor, DualType, ScalarType, StorageOrder >::operator()(Scalar const *parameters, Scalar *residuals, Scalar *jacobian) const
References Brush::TinyCostFunction< CostFunctor, DualType, ScalarType, StorageOrder >::Evaluate.
int Brush::TinyCostFunction< CostFunctor, DualType, ScalarType, StorageOrder >::NumResiduals() const
References Brush::TinyCostFunction< CostFunctor, DualType, ScalarType, StorageOrder >::functor_.
Referenced by Brush::TinyCostFunction< CostFunctor, DualType, ScalarType, StorageOrder >::values.
int Brush::TinyCostFunction< CostFunctor, DualType, ScalarType, StorageOrder >::NumParameters() const
References Brush::TinyCostFunction< CostFunctor, DualType, ScalarType, StorageOrder >::functor_.
Referenced by Brush::TinyCostFunction< CostFunctor, DualType, ScalarType, StorageOrder >::inputs.
int Brush::TinyCostFunction< CostFunctor, DualType, ScalarType, StorageOrder >::operator()(Eigen::Matrix< Scalar, -1, 1 > const &input, Eigen::Matrix< Scalar, -1, 1 > &residual)
References Brush::TinyCostFunction< CostFunctor, DualType, ScalarType, StorageOrder >::Evaluate.
int Brush::TinyCostFunction< CostFunctor, DualType, ScalarType, StorageOrder >::df(Eigen::Matrix< Scalar, -1, 1 > const &input, Eigen::Matrix< Scalar, -1, -1 > &jacobian)
References Brush::TinyCostFunction< CostFunctor, DualType, ScalarType, StorageOrder >::Evaluate.
int Brush::TinyCostFunction< CostFunctor, DualType, ScalarType, StorageOrder >::values() const
References Brush::TinyCostFunction< CostFunctor, DualType, ScalarType, StorageOrder >::NumResiduals.
int Brush::TinyCostFunction< CostFunctor, DualType, ScalarType, StorageOrder >::inputs() const
References Brush::TinyCostFunction< CostFunctor, DualType, ScalarType, StorageOrder >::NumParameters.