Brush::SearchSpace
using Brush::SearchSpace::ArgsHash = std::size_t
using Brush::SearchSpace::Map = unordered_map<DataType, unordered_map<ArgsHash, unordered_map<NodeType, T>>>
Map<Node> Brush::SearchSpace::node_map
Maps return types to argument types to node types.
schema: { return_type : { arguments_type : {node_type : node } }}
Referenced by AddNode, check, check, check, Brush::Var::SubtreeMutation::find_spots, get, get_node_like, init, sample_op, sample_op, sample_op_with_arg, sample_subtree.
Map<float> Brush::SearchSpace::node_map_weights
A map of weights corresponding to elements in node_map, used to weight probabilities of each node being sampled from the map.
Referenced by AddNode, get_weights, get_weights, get_weights, init, sample_op, sample_op_with_arg.
unordered_map<DataType, vector<Node> > Brush::SearchSpace::terminal_map
Maps return types to terminals.
schema: { return_type : vector of Nodes }
Referenced by init, sample_terminal, sample_terminal, Brush::Simpl::Constants_simplifier::simplify_tree.
unordered_map<DataType, vector<float> > Brush::SearchSpace::terminal_weights
A map of weights corresponding to elements in terminal_map, used to weight probabilities of each terminal being sampled from the map.
Referenced by init, sample_terminal, sample_terminal.
vector<DataType> Brush::SearchSpace::terminal_types
A vector storing the available return types of terminals.
Referenced by init, sample_op_with_arg.
vector<string> Brush::SearchSpace::op_names
A vector storing the available operator names (used by bandits).
Referenced by init.
PT Brush::SearchSpace::make_program(const Parameters &params, int max_d=0, int max_size=0)
Makes a random program.
We use an implementation of PTC2 for strongly typed GP from Sean Luke. "Two fast tree-creation algorithms for genetic programming" (https://doi.org/10.1109/4235.873237) PT program type max_d max depth of the program max_size max size of the programd a program of type PTsize
Referenced by Brush::Pop::Individual< PT::Regressor >::init, make_classifier, make_multiclass_classifier, make_regressor, make_representer.
RegressorProgram Brush::SearchSpace::make_regressor(int max_d=0, int max_size=0, const Parameters &params=Parameters())
Makes a random regressor program. Convenience wrapper for make_program.
max_d max depth of the program max_size max size of the program a regressor program
References make_program.
Referenced by bind_search_space.
ClassifierProgram Brush::SearchSpace::make_classifier(int max_d=0, int max_size=0, const Parameters &params=Parameters())
Makes a random classifier program. Convenience wrapper for make_program.
max_d max depth of the program max_size max size of the program a classifier program
References make_program.
Referenced by bind_search_space.
MulticlassClassifierProgram Brush::SearchSpace::make_multiclass_classifier(int max_d=0, int max_size=0, const Parameters &params=Parameters())
Makes a random multiclass classifier program. Convenience wrapper for make_program.
max_d max depth of the program max_size max size of the program a multiclass classifier program
References make_program.
Referenced by bind_search_space.
RepresenterProgram Brush::SearchSpace::make_representer(int max_d=0, int max_size=0, const Parameters &params=Parameters())
Makes a random representer program. Convenience wrapper for make_program.
max_d max depth of the program max_size max size of the program a representer program
References make_program.
Referenced by bind_search_space.
Brush::SearchSpace::SearchSpace()=default
Brush::SearchSpace::SearchSpace(const Dataset &d, const unordered_map< string, float > &user_ops={}, bool weights_init=true)
Construct a search space.
d A dataset containing terminal definitions user_ops Optional user-provided dictionary of operators with their probability of being chosen weights_init whether the terminal prob_change should be estimated from correlations with the target value
void Brush::SearchSpace::init(const Dataset &d, const unordered_map< string, float > &user_ops={}, bool weights_init=true)
Called by the constructor to initialize the search space.
d A dataset containing terminal definitions user_ops Optional user-provided dictionary of operators with their probability of being chosen weights_init whether the terminal prob_change should be estimated from correlations with the target value
References Brush::Data::Dataset::classification, Brush::NodeTypes::Count, Brush::generate_terminals, GenerateNodeMap, node_map, node_map_weights, Brush::NodeTypeName, op_names, terminal_map, terminal_types, terminal_weights, Brush::Data::Dataset::unique_data_types, Brush::Data::Dataset::y.
bool Brush::SearchSpace::check(DataType R) const
check if a return type is in the node map
R data type true if it exists
References HANDLE_ERROR_THROW, node_map.
Referenced by check, check, get, sample_op, sample_op, sample_op_with_arg.
bool Brush::SearchSpace::check(DataType R, size_t sig_hash) const
check if a function signature is in the search space
R return type sig_hash signature hash true if it exists
References check, HANDLE_ERROR_THROW, node_map.
bool Brush::SearchSpace::check(DataType R, size_t sig_hash, NodeType type) const
check if a typed Node is in the search space
R return type sig_hash signature hash type the node type true if it exists
References check, HANDLE_ERROR_THROW, node_map.
bool Brush::SearchSpace::has_solution_space(Iter start, Iter end) const
Takes iterators to weight vectors and checks if they have a non-empty solution space. An empty solution space is defined as having no non-zero, positive values.
T type of iterator. start Start iterator end End iterator true if at least one weight is positive
Referenced by get_node_like, sample_op, sample_op, sample_op_with_arg, sample_subtree, sample_terminal, sample_terminal.
Node Brush::SearchSpace::get(const string &name)
Referenced by make_program.
Node Brush::SearchSpace::get(NodeType type, DataType R, size_t sig_hash) const
get a typed node
type the node type R the return type of the node sig_hash the signature hash of the node the matching Node
References check, node_map.
Node Brush::SearchSpace::get(NodeType type, DataType R, S sig) const
get a typed node.
S the signature of the node, inferred. type the node type R the return type of the node sig the signature of the node the matching Node
References get.
Referenced by get.
vector< float > Brush::SearchSpace::get_weights() const
get weights of the return types
a weight vector, each element corresponding to a return type.
References node_map_weights.
Referenced by get_node_like, sample_op, sample_subtree.
vector< float > Brush::SearchSpace::get_weights(DataType ret) const
get weights of the argument types matching return type ret.
ret return type a weight vector, each element corresponding to an args type.
References node_map_weights.
vector< float > Brush::SearchSpace::get_weights(DataType ret, ArgsHash sig_hash) const
get the weights of nodes matching a signature.
ret return type sig_hash signature hash a weight vector, each element corresponding to a node.
References node_map_weights.
std::optional< Node > Brush::SearchSpace::sample_terminal(bool force_return=false) const
Get a random terminal.
std::optional that may contain a terminal Node.
References has_solution_space, Brush::Util::r, terminal_map, terminal_weights.
Referenced by get_node_like, make_program, PTC2.
std::optional< Node > Brush::SearchSpace::sample_terminal(DataType R, bool force_return=false) const
Get a random terminal with return type R
std::optional that may contain a terminal Node of type R.
References has_solution_space, Brush::Util::r, terminal_map, terminal_weights.
std::optional< Node > Brush::SearchSpace::sample_op(DataType ret) const
get an operator matching return type ret.
ret return type std::optional that may contain a randomly chosen operator matching return type ret
References check, get_weights, has_solution_space, node_map, Brush::Util::r.
Referenced by make_program, PTC2.
std::optional< Node > Brush::SearchSpace::sample_op(NodeType type, DataType R)
Get a specific node type that matches a return value.
type the node type R the return type std::optional that may contain a Node of type type with return type R.
References check, has_solution_space, node_map, node_map_weights, Brush::Util::r.
std::optional< Node > Brush::SearchSpace::sample_op_with_arg(DataType ret, DataType arg, bool terminal_compatible=true, int max_args=0) const
get operator with at least one argument matching arg
ret return type arg argument type to match terminal_compatible if true, the other args the returned operator takes must exist in the terminal types. max_args if zero, there is no limit on number of arguments of the operator. If not, the operator can have at most max_args arguments. std::optional that may contain a matching operator respecting all restrictions.
References check, has_solution_space, Brush::Util::in, node_map, node_map_weights, Brush::Util::r, terminal_types.
std::optional< Node > Brush::SearchSpace::get_node_like(Node node) const
get a node with a signature matching node
node the node to match std::optional that may contain a Node
References Brush::Node::args_type, get_weights, has_solution_space, Brush::Is, node_map, Brush::Node::node_type, Brush::Util::r, Brush::Node::ret_type, sample_terminal.
std::optional< tree< Node > > Brush::SearchSpace::sample_subtree(Node root, int max_d, int max_size) const
create a subtree with maximum size and depth restrictions and root of type root_type
root_type return type max_d the maximum depth max_size the maximum size of the tree (will be sampled between [1, max_size]) std::optional that may contain a tree
References get_weights, has_solution_space, node_map, PTC2, Brush::Node::ret_type.
Referenced by Brush::Var::SubtreeMutation::mutate.
void Brush::SearchSpace::print() const
prints the search space map.
Referenced by bind_search_space.
std::string Brush::SearchSpace::repr() const
returns a string with a json representation of the search space map
References Brush::ArgsName.
Referenced by bind_search_space.
P Brush::SearchSpace::make_program(const Parameters &params, int max_d, int max_size)
References Brush::ArrayF, Brush::BinaryClassifier, Brush::Node::fixed, get, Brush::Logistic, Brush::MatrixF, Brush::Parameters::max_depth, Brush::Parameters::max_size, Brush::MulticlassClassifier, Brush::OffsetSum, PTC2, Brush::Util::r, sample_op, sample_terminal, Brush::Node::set_is_weighted, Brush::Node::set_prob_change, Brush::Softmax.
tree< Node > & Brush::SearchSpace::PTC2(tree< Node > &Tree, tree< Node >::iterator root, int max_d, int max_size) const
References Brush::Node::arg_types, Brush::DataTypeName, Brush::Node::get_is_weighted, HANDLE_ERROR_THROW, Brush::Is, Brush::Isnt, Brush::Node::node_type, Brush::RandomDequeue, sample_op, sample_terminal.
Referenced by make_program, sample_subtree.
void Brush::SearchSpace::AddNode(const unordered_map< string, float > &user_ops, const vector< DataType > &unique_data_types)
References CreateNode, Brush::Is, node_map, node_map_weights, Brush::NodeTypeName.
Referenced by AddNodes.
void Brush::SearchSpace::AddNodes(const unordered_map< string, float > &user_ops, const vector< DataType > &unique_data_types, std::index_sequence< Is... >)
References AddNode.
Referenced by MakeNodes.
void Brush::SearchSpace::MakeNodes(const unordered_map< string, float > &user_ops, const vector< DataType > &unique_data_types)
References AddNodes, Brush::Is, Brush::NodeTypeName.
Referenced by GenerateNodeMap.
void Brush::SearchSpace::GenerateNodeMap(const unordered_map< string, float > &user_ops, const vector< DataType > &unique_data_types, std::index_sequence< Is... >)
References MakeNodes.
Referenced by init.
static constexpr std::optional< Node > Brush::SearchSpace::CreateNode(const auto &unique_data_types, bool use_all, bool weighted)
References Brush::ArgsName, Brush::Util::in.
Referenced by AddNode.