Brush::Data::TimeSeries
using Brush::Data::TimeSeries< T >::Scalar = T
using Brush::Data::TimeSeries< T >::EntryType = Eigen::Array<T,Dynamic,1>
using Brush::Data::TimeSeries< T >::ValType = std::vector<EntryType>
using Brush::Data::TimeSeries< T >::TimeType = std::vector<Eigen::ArrayXi>
const size_t Brush::Data::TimeSeries< T >::NumDimensions
TimeType Brush::Data::TimeSeries< T >::time
ValType Brush::Data::TimeSeries< T >::value
Referenced by Brush::Data::TimeSeries< T >::cols, Brush::Data::TimeSeries< T >::rows, Brush::Data::TimeSeries< T >::size.
Brush::Data::TimeSeries< T >::TimeSeries()=default
Wraps time and value slices to matrices TODO: define begin() and end() iterators? figure out how to handle operators that just use values versus time
Referenced by Brush::Data::TimeSeries< T >::operator().
Brush::Data::TimeSeries< T >::TimeSeries(const TimeType &t, const ValType &v)
TimeSeries Brush::Data::TimeSeries< T >::operator()(const U &idx, const V &idx2=Eigen::all) const
return a slice of the data using indices idx
References Brush::Util::slice, Brush::Data::TimeSeries< T >::TimeSeries.
auto Brush::Data::TimeSeries< T >::size() const -> size_t
References Brush::Data::TimeSeries< T >::value.
auto Brush::Data::TimeSeries< T >::rows() const -> size_t
References Brush::Data::TimeSeries< T >::value.
auto Brush::Data::TimeSeries< T >::cols(int i=0) const -> size_t
References Brush::Data::TimeSeries< T >::value.
ValType::iterator Brush::Data::TimeSeries< T >::begin()
ValType::iterator Brush::Data::TimeSeries< T >::end()
auto Brush::Data::TimeSeries< T >::cbegin() const
Referenced by Brush::Data::TimeSeries< T >::reduce, Brush::Data::TimeSeries< T >::transform.
auto Brush::Data::TimeSeries< T >::cend() const
Referenced by Brush::Data::TimeSeries< T >::reduce, Brush::Data::TimeSeries< T >::transform.
TimeType::iterator Brush::Data::TimeSeries< T >::tbegin()
TimeType::iterator Brush::Data::TimeSeries< T >::tend()
auto Brush::Data::TimeSeries< T >::ctbegin() const
auto Brush::Data::TimeSeries< T >::ctend() const
auto Brush::Data::TimeSeries< T >::transform(std::function< ET(EntryType)> op) const
References Brush::Data::TimeSeries< T >::cbegin, Brush::Data::TimeSeries< T >::cend.
Referenced by Brush::Data::TimeSeries< T >::abs, Brush::Data::TimeSeries< T >::acos, Brush::Data::TimeSeries< T >::asin, Brush::Data::TimeSeries< T >::atan, Brush::Data::TimeSeries< T >::ceil, Brush::Data::TimeSeries< T >::cos, Brush::Data::TimeSeries< T >::cosh, Brush::Data::TimeSeries< T >::exp, Brush::Data::TimeSeries< T >::floor, Brush::Data::TimeSeries< T >::log, Brush::Data::TimeSeries< T >::log1p, Brush::Data::TimeSeries< T >::logabs, Brush::Data::TimeSeries< T >::pow, Brush::Data::TimeSeries< T >::sin, Brush::Data::TimeSeries< T >::sinh, Brush::Data::TimeSeries< T >::sqrt, Brush::Data::TimeSeries< T >::sqrtabs, Brush::Data::TimeSeries< T >::square, Brush::Data::TimeSeries< T >::tan, Brush::Data::TimeSeries< T >::tanh.
auto Brush::Data::TimeSeries< T >::reduce(const auto &op) const
References Brush::Data::TimeSeries< T >::cbegin, Brush::Data::TimeSeries< T >::cend.
Referenced by Brush::Data::TimeSeries< T >::max, Brush::Data::TimeSeries< T >::mean, Brush::Data::TimeSeries< T >::median, Brush::Data::TimeSeries< T >::min, Brush::Data::TimeSeries< T >::std.
auto Brush::Data::TimeSeries< T >::cast() const
auto Brush::Data::TimeSeries< T >::abs() const
References Brush::Data::TimeSeries< T >::transform.
auto Brush::Data::TimeSeries< T >::pow() const
References Brush::Data::TimeSeries< T >::transform.
auto Brush::Data::TimeSeries< T >::log() const
References Brush::Data::TimeSeries< T >::transform.
Referenced by Brush::Data::TimeSeries< T >::logabs.
auto Brush::Data::TimeSeries< T >::logabs() const
References Brush::Data::TimeSeries< T >::log, Brush::Data::TimeSeries< T >::transform.
auto Brush::Data::TimeSeries< T >::log1p() const
References Brush::Data::TimeSeries< T >::transform.
auto Brush::Data::TimeSeries< T >::ceil() const
References Brush::Data::TimeSeries< T >::transform.
auto Brush::Data::TimeSeries< T >::floor() const
References Brush::Data::TimeSeries< T >::transform.
auto Brush::Data::TimeSeries< T >::exp() const
References Brush::Data::TimeSeries< T >::transform.
auto Brush::Data::TimeSeries< T >::sin() const
References Brush::Data::TimeSeries< T >::transform.
auto Brush::Data::TimeSeries< T >::cos() const
References Brush::Data::TimeSeries< T >::transform.
auto Brush::Data::TimeSeries< T >::tan() const
References Brush::Data::TimeSeries< T >::transform.
auto Brush::Data::TimeSeries< T >::asin() const
References Brush::Data::TimeSeries< T >::transform.
auto Brush::Data::TimeSeries< T >::acos() const
References Brush::Data::TimeSeries< T >::transform.
auto Brush::Data::TimeSeries< T >::atan() const
References Brush::Data::TimeSeries< T >::transform.
auto Brush::Data::TimeSeries< T >::sinh() const
References Brush::Data::TimeSeries< T >::transform.
auto Brush::Data::TimeSeries< T >::cosh() const
References Brush::Data::TimeSeries< T >::transform.
auto Brush::Data::TimeSeries< T >::tanh() const
References Brush::Data::TimeSeries< T >::transform.
auto Brush::Data::TimeSeries< T >::sqrt() const
References Brush::Data::TimeSeries< T >::transform.
Referenced by Brush::Data::TimeSeries< T >::sqrtabs.
auto Brush::Data::TimeSeries< T >::sqrtabs() const
References Brush::Data::TimeSeries< T >::sqrt, Brush::Data::TimeSeries< T >::transform.
auto Brush::Data::TimeSeries< T >::square() const
References Brush::Data::TimeSeries< T >::transform.
auto Brush::Data::TimeSeries< T >::median() const
References Brush::Util::median, Brush::Data::TimeSeries< T >::reduce.
Referenced by Brush::Function< NodeType::Median >::operator().
auto Brush::Data::TimeSeries< T >::mean() const
References Brush::Data::TimeSeries< T >::reduce.
Referenced by Brush::Function< NodeType::Mean >::operator().
auto Brush::Data::TimeSeries< T >::std() const
References Brush::Data::TimeSeries< T >::reduce.
auto Brush::Data::TimeSeries< T >::max() const
References Brush::Data::TimeSeries< T >::reduce.
Referenced by Brush::Function< NodeType::Max >::operator().
auto Brush::Data::TimeSeries< T >::min() const
References Brush::Data::TimeSeries< T >::reduce.
Referenced by Brush::Function< NodeType::Min >::operator().
auto Brush::Data::TimeSeries< T >::sum() const
Referenced by Brush::Function< NodeType::Sum >::operator().
auto Brush::Data::TimeSeries< T >::count() const
Referenced by Brush::Function< NodeType::Count >::operator().
auto Brush::Data::TimeSeries< T >::prod() const
Referenced by Brush::Function< NodeType::Prod >::operator().
auto Brush::Data::TimeSeries< T >::operator*(T2 v)
auto Brush::Data::TimeSeries< T >::before(const TimeSeries< T2 > &t2) const
auto Brush::Data::TimeSeries< T >::after(const TimeSeries< T2 > &t2) const
auto Brush::Data::TimeSeries< T >::during(const TimeSeries< T2 > &t2) const
std::string Brush::Data::TimeSeries< T >::print() const
Referenced by fmt::formatter< Brush::Data::TimeSeriesb >::format, fmt::formatter< Brush::Data::TimeSeriesf >::format, fmt::formatter< Brush::Data::TimeSeriesi >::format, Brush::operator<<.