Brush::Util::Normalizer
vector<float> Brush::Util::Normalizer::scale
Referenced by fit, normalize.
vector<float> Brush::Util::Normalizer::offset
Referenced by fit, normalize.
vector<char> Brush::Util::Normalizer::dtypes
Referenced by fit, fit_normalize, normalize.
bool Brush::Util::Normalizer::scale_all
Referenced by normalize, Normalizer.
Brush::Util::Normalizer::Normalizer(bool sa=true)
References scale_all.
void Brush::Util::Normalizer::fit(MatrixXf &X, const vector< char > &dt)
fit the scale and offset of data.
References dtypes, offset, scale.
Referenced by fit_normalize.
void Brush::Util::Normalizer::normalize(MatrixXf &X)
normalize matrix.
References dtypes, NEAR_ZERO, offset, scale, scale_all.
Referenced by fit_normalize.
void Brush::Util::Normalizer::fit_normalize(MatrixXf &X, const vector< char > &dtypes)
References dtypes, fit, normalize.
Referenced by Brush::calc_initial_weight.