Dataset
vector<size_t> Brush::Data::Dataset::training_data_idx
vector<size_t> Brush::Data::Dataset::validation_data_idx
std::vector<DataType> Brush::Data::Dataset::unique_data_types
keeps track of the unique data types in the dataset.
std::vector<DataType> Brush::Data::Dataset::feature_types
types of data in the features.
std::vector<string> Brush::Data::Dataset::feature_names
names of the feature types as string representations.
std::unordered_map<DataType,vector<string> > Brush::Data::Dataset::features_of_type
map from data types to features having that type.
Referenced by Split::get_best_threshold_by_type.
std::map<string, State> Brush::Data::Dataset::features
dataset features, as key value pairs
ArrayXf Brush::Data::Dataset::y
length N array, the target label
Referenced by Operator< NT, S, Fit, enable_if_t< is_in_v< NT, NodeType::SplitOn, NodeType::SplitBest > > >::fit, Split::get_best_threshold_by_type, Brush::Eval::Scorer< P >::score.
bool Brush::Data::Dataset::classification
whether this is a classification problem
Referenced by Operator< NT, S, Fit, enable_if_t< is_in_v< NT, NodeType::SplitOn, NodeType::SplitBest > > >::fit, Split::get_best_threshold_by_type.
std::optional<std::reference_wrapper<const ArrayXXf> > Brush::Data::Dataset::Xref
float Brush::Data::Dataset::validation_size
percentage of original data used for train. if 0.0, then all data is used for train and validation
bool Brush::Data::Dataset::use_validation
bool Brush::Data::Dataset::shuffle_split
float Brush::Data::Dataset::batch_size
percentage of training data size to use in each batch. if 1.0, then all data is used
bool Brush::Data::Dataset::use_batch
Dataset Brush::Data::Dataset::operator()(const vector< size_t > &idx) const
return a slice of the data using indices idx
void Brush::Data::Dataset::init()
call init at the end of constructors to define metafeatures of the data.
map< string, State > Brush::Data::Dataset::make_features(const ArrayXXf &X, const map< string, State > &Z={}, const vector< string > &vn={}, const vector< string > &ft={})
turns input data into a feature map
map< string, State > Brush::Data::Dataset::copy_and_make_features(const ArrayXXf &X, const Dataset &ref_dataset, const vector< string > &vn={})
turns input into a feature map, with feature types copied from a reference
Brush::Data::Dataset::Dataset(std::map< string, State > &d, const Ref< const ArrayXf > &y_=ArrayXf(), bool c=false, float validation_size=0.0, float batch_size=1.0, bool shuffle_split=false)
initialize data from a map.
Brush::Data::Dataset::Dataset(const ArrayXXf &X, const Ref< const ArrayXf > &y_=ArrayXf(), const vector< string > &vn={}, const map< string, State > &Z={}, const vector< string > &ft={}, bool c=false, float validation_size=0.0, float batch_size=1.0, bool shuffle_split=false)
initialize data from a matrix with feature columns.
Brush::Data::Dataset::Dataset(const ArrayXXf &X, const vector< string > &vn, const vector< string > &ft={}, bool c=false, float validation_size=0.0, float batch_size=1.0, bool shuffle_split=false)
initialize data from X and feature names
Brush::Data::Dataset::Dataset(const ArrayXXf &X, const Dataset &ref_dataset, const vector< string > &vn)
void Brush::Data::Dataset::print() const
auto Brush::Data::Dataset::get_X() const
Dataset Brush::Data::Dataset::get_training_data() const
Dataset Brush::Data::Dataset::get_validation_data() const
int Brush::Data::Dataset::get_n_samples() const
Referenced by Operator< NT, S, Fit, enable_if_t< is_in_v< NT, NodeType::SplitOn, NodeType::SplitBest > > >::predict.
int Brush::Data::Dataset::get_n_features() const
Dataset Brush::Data::Dataset::get_batch() const
select random subset of data for training weights.
float Brush::Data::Dataset::get_batch_size()
void Brush::Data::Dataset::set_batch_size(float new_size)
DataType Brush::Data::Dataset::get_feature_type(const string &name) const
Referenced by Operator< NT, S, Fit, enable_if_t< is_in_v< NT, NodeType::SplitOn, NodeType::SplitBest > > >::fit.
array< Dataset, 2 > Brush::Data::Dataset::split(const ArrayXb &mask) const
Referenced by Operator< NT, S, Fit, enable_if_t< is_in_v< NT, NodeType::SplitOn, NodeType::SplitBest > > >::predict.
State Brush::Data::Dataset::operator[](std::string name) const