Brush::Util::Timer
typedef std::chrono::high_resolution_clock Brush::Util::Timer::high_resolution_clock
typedef std::chrono::seconds Brush::Util::Timer::seconds
high_resolution_clock::time_point Brush::Util::Timer::_start
Referenced by Elapsed, Reset.
Brush::Util::Timer::Timer(bool run=false)
References Reset.
Referenced by operator<<.
void Brush::Util::Timer::Reset()
References _start.
Referenced by Timer.
std::chrono::duration< float > Brush::Util::Timer::Elapsed() const
References _start.
Referenced by operator<<.
std::basic_ostream< T, Traits > & operator<<(std::basic_ostream< T, Traits > &out, const Timer &timer)
References Elapsed, Timer.