Brush
NodeType
ProgramType
DataType
using Brush::NT = NodeType
using Brush::UnderlyingNodeType = std::underlying_type_t<NodeType>
using Brush::Scalar = float
typedef tree<Node>::pre_order_iterator Brush::Iter
typedef tree<Node>::post_order_iterator Brush::PostIter
typedef ProgramType Brush::PT = ProgramType
using Brush::Jetify_t = typename Jetify<T>::type
using Brush::UnJetify_t = typename UnJetify<T>::type
using Brush::NarySignature_t = typename NarySignature<R,Arg,ArgCount>::type
using Brush::NarySignatures_t = typename NarySignatures<R,Arg,MaxArgCount>::type
typedef Eigen::Array<bool,Eigen::Dynamic,1> Brush::ArrayXb
typedef Eigen::Array<int,Eigen::Dynamic,1> Brush::ArrayXi
typedef Eigen::Array<bool,Eigen::Dynamic,Eigen::Dynamic> Brush::ArrayXXb
typedef Eigen::Array<int,Eigen::Dynamic,Eigen::Dynamic> Brush::ArrayXXi
typedef ceres::Jet<float, stride> Brush::fJet
typedef ceres::Jet<int, stride> Brush::iJet
typedef ceres::Jet<bool, stride> Brush::bJet
typedef Eigen::Array<fJet,Eigen::Dynamic,1> Brush::ArrayXfJet
typedef Eigen::Array<iJet,Eigen::Dynamic,1> Brush::ArrayXiJet
typedef Eigen::Array<bJet,Eigen::Dynamic,1> Brush::ArrayXbJet
typedef Eigen::Array<fJet,Eigen::Dynamic,Eigen::Dynamic> Brush::ArrayXXfJet
typedef Eigen::Array<iJet,Eigen::Dynamic,Eigen::Dynamic> Brush::ArrayXXiJet
typedef Eigen::Array<bJet,Eigen::Dynamic,Eigen::Dynamic> Brush::ArrayXXbJet
using Brush::WeightType_t = typename WeightType<T>::type
typedef Program<PT::Regressor> Brush::RegressorProgram
typedef Program<PT::BinaryClassifier> Brush::ClassifierProgram
typedef Program<PT::MulticlassClassifier> Brush::MulticlassClassifierProgram
typedef Program<PT::Representer> Brush::RepresenterProgram
typedef Pop::Individual<PT::Regressor> Brush::RegressorIndividual
typedef Pop::Individual<PT::BinaryClassifier> Brush::ClassifierIndividual
typedef Pop::Individual<PT::MulticlassClassifier> Brush::MulticlassClassifierIndividual
typedef Pop::Individual<PT::Representer> Brush::RepresenterIndividual
typedef Engine<PT::Regressor> Brush::RegressorEngine
typedef Engine<PT::BinaryClassifier> Brush::ClassifierEngine
typedef Engine<PT::MulticlassClassifier> Brush::MulticlassClassifierEngine
typedef Engine<PT::Representer> Brush::RepresenterEngine
using Brush::DT = DataType
using Brush::TreeIter = tree<Node>::pre_order_iterator
map< DataType, string > Brush::DataTypeName
Referenced by fmt::formatter< Brush::DataType >::format, Brush::Data::operator<<, Brush::SearchSpace::PTC2.
map< string, DataType > Brush::DataNameType
const map< DataType, std::type_index > Brush::DataTypeID
map< std::type_index, DataType > Brush::DataIDType
constexpr bool Brush::always_false_v
DispatchTable< true > Brush::dtable_fit
DispatchTable< false > Brush::dtable_predict
constexpr auto Brush::Stack
Stacks Eigen arrays into a 2d-array, where each array is a column.
T : underlying type in array
std::map< std::string, NodeType > Brush::NodeNameType
std::map< NodeType, std::string > Brush::NodeTypeName
Referenced by Brush::SearchSpace::AddNode, fmt::formatter< Brush::NodeType >::format, from_json, Brush::SearchSpace::MakeNodes, operator<<.
constexpr size_t Brush::MAX_ARGS
constexpr bool Brush::all_same_v
constexpr bool Brush::is_one_of_v
constexpr int Brush::stride
constexpr bool Brush::is_std_array_v
constexpr bool Brush::is_eigen_array_v
constexpr bool Brush::is_tuple_v
std::unordered_map< std::size_t, std::string > Brush::ArgsName
Referenced by Brush::SearchSpace::CreateNode, fmt::formatter< Brush::SearchSpace >::format.
SearchSpace Brush::SS
Referenced by bind_search_space, Brush::Var::SubtreeMutation::find_spots, fmt::formatter< Brush::SearchSpace >::format, Brush::Var::PointMutation::mutate, Brush::Var::InsertMutation::mutate, Brush::Var::DeleteMutation::mutate, Brush::Var::SubtreeMutation::mutate.
ostream & Brush::operator<<(ostream &os, DataType n)
std::ostream & Brush::operator<<(std::ostream &output, const Brush::Data::TimeSeries< bool > &ts)
References bind_engine.
std::ostream & Brush::operator<<(std::ostream &output, const Brush::Data::TimeSeries< float > &ts)
References bind_engine.
std::ostream & Brush::operator<<(std::ostream &output, const Brush::Data::TimeSeries< int > &ts)
References bind_engine.
Brush::NLOHMANN_DEFINE_TYPE_NON_INTRUSIVE(Engine< PT::Regressor >, params, best_ind, archive)
Brush::NLOHMANN_DEFINE_TYPE_NON_INTRUSIVE(Engine< PT::BinaryClassifier >, params, best_ind, archive)
Brush::NLOHMANN_DEFINE_TYPE_NON_INTRUSIVE(Engine< PT::MulticlassClassifier >, params, best_ind, archive)
Brush::NLOHMANN_DEFINE_TYPE_NON_INTRUSIVE(Engine< PT::Representer >, params, best_ind, archive)
void Brush::to_json(json &j, const Fitness &f)
References bind_engine.
Referenced by Brush::Engine< T >::get_archive.
void Brush::from_json(const json &j, Fitness &f)
References bind_engine.
Brush::NLOHMANN_DEFINE_TYPE_NON_INTRUSIVE(Parameters, verbosity, random_state, pop_size, max_gens, max_stall, max_time, scorer_, load_population, save_population, logfile, current_gen, num_islands, max_depth, n_jobs, max_size, objectives, sel, surv, cx_prob, mig_prob, classification, n_classes, validation_size, feature_names, batch_size, mutation_probs, functions)
R Brush::DispatchOp(const Data::Dataset &d, TreeNode &tn, const W **weights)
References bind_engine, Brush::Operator< NT, S, Fit, E >::eval.
R Brush::DispatchOp(const Data::Dataset &d, TreeNode &tn)
References bind_engine, Brush::Operator< NT, S, Fit, E >::eval.
ostream & Brush::operator<<(ostream &os, const NodeType &nt)
References bind_engine, NodeTypeName.
ostream & Brush::operator<<(ostream &os, const Node &n)
References bind_engine.
void Brush::to_json(json &j, const Node &p)
References bind_engine.
void Brush::init_node_with_default_signature(Node &node)
References Abs, Acos, Add, And, Asin, Atan, bind_engine, Ceil, Cos, Cosh, CustomSplit, CustomUnaryOp, Div, Exp, Floor, HANDLE_ERROR_THROW, Is, Log, Log1p, Logabs, Logistic, Max, Mean, Median, Min, Mul, OffsetSum, Or, Pow, Prod, Sin, Sinh, Softmax, SplitBest, SplitOn, Sqrt, Sqrtabs, Square, Sub, Sum, Tan, Tanh.
Referenced by from_json.
void Brush::from_json(const json &j, Node &p)
References bind_engine, HANDLE_ERROR_THROW, init_node_with_default_signature, NodeTypeName.
auto Brush::Isnt(DataType dt) -> bool
References bind_engine.
Referenced by IsDifferentiable, IsWeighable, IsWeighable, IsWeighable.
auto Brush::IsWeighable() noexcept -> bool
References ArrayB, ArrayBJet, Isnt, MatrixB, MatrixBJet, TimeSeriesB.
Referenced by Brush::Node::init, Brush::Var::ToggleWeightOnMutation::mutate, Brush::Node::set_is_weighted.
auto Brush::IsWeighable(DataType dt) noexcept -> bool
References ArrayB, ArrayBJet, bind_engine, Isnt, MatrixB, MatrixBJet, TimeSeriesB.
auto Brush::Is(NodeType nt) -> bool
References bind_engine.
Referenced by init_node_with_default_signature, Brush::DispatchTable< Fit >::InitMap, IsCommutative, Brush::NarySignatures< R, Arg, MaxArgCount >::make_signatures.
auto Brush::Isnt(NodeType nt) -> bool
References bind_engine.
auto Brush::IsLeaf(NodeType nt) noexcept -> bool
References bind_engine.
auto Brush::IsCommutative(NodeType nt) noexcept -> bool
References Add, bind_engine, Is, Max, Min, Mul.
auto Brush::IsDifferentiable(NodeType nt) noexcept -> bool
References After, And, Before, bind_engine, Ceil, Count, During, Floor, Isnt, Not, Or.
auto Brush::IsWeighable(NodeType nt) noexcept -> bool
References After, And, Before, bind_engine, Ceil, Count, During, Floor, Isnt, Not, Or, SplitBest, SplitOn.
constexpr auto Brush::operator&(NodeType lhs, NodeType rhs) -> NodeType
References bind_engine.
constexpr auto Brush::operator|(NodeType lhs, NodeType rhs) -> NodeType
References bind_engine.
constexpr auto Brush::operator^(NodeType lhs, NodeType rhs) -> NodeType
References bind_engine.
constexpr auto Brush::operator~(NodeType lhs) -> NodeType
References bind_engine.
auto Brush::operator&=(NodeType &lhs, NodeType rhs) -> NodeType &
References bind_engine.
auto Brush::operator|=(NodeType &lhs, NodeType rhs) -> NodeType &
References bind_engine.
auto Brush::operator^=(NodeType &lhs, NodeType rhs) -> NodeType &
References bind_engine.
void Brush::to_json(json &j, const Program< PType > &p)
References bind_engine.
void Brush::from_json(const json &j, Program< PType > &p)
References bind_engine.
float Brush::calc_initial_weight(const ArrayXf &value, const ArrayXf &y)
References bind_engine, Brush::Util::slope.
Referenced by generate_terminals.
vector< Node > Brush::generate_terminals(const Dataset &d, const bool weights_init)
generate terminals from the dataset features and random constants.
d a dataset weights_init whether the terminal prob_change should be estimated from correlations with the target value a vector of nodes
References bind_engine, calc_initial_weight, Constant, HANDLE_ERROR_THROW, MeanLabel, Brush::Node::set_prob_change, Terminal.
Referenced by Brush::SearchSpace::init.
T Brush::RandomDequeue(std::vector< T > &Q)
queue for make program
References bind_engine, Brush::Util::r, Brush::Util::Rnd::rnd_int.
Referenced by Brush::SearchSpace::PTC2.