Brush::Engine
float Brush::Engine< T >::best_score
Referenced by Brush::Engine< T >::init.
int Brush::Engine< T >::best_complexity
Referenced by Brush::Engine< T >::init, Brush::Engine< T >::update_best.
Parameters Brush::Engine< T >::params
hyperparameters of brush, which the user can interact
Referenced by Brush::Engine< T >::calculate_stats, Brush::Engine< T >::init, Brush::Engine< T >::log_stats, Brush::Engine< T >::print_stats, Brush::Engine< T >::run, Brush::Engine< T >::update_best.
Individual<T> Brush::Engine< T >::best_ind
Referenced by Brush::Engine< T >::predict_archive, Brush::Engine< T >::predict_proba_archive, Brush::Engine< T >::update_best.
Archive<T> Brush::Engine< T >::archive
pareto front archive
Referenced by Brush::Engine< T >::get_archive, Brush::Engine< T >::init, Brush::Engine< T >::predict_archive, Brush::Engine< T >::predict_proba_archive, Brush::Engine< T >::run.
SearchSpace Brush::Engine< T >::ss
Referenced by Brush::Engine< T >::init, Brush::Engine< T >::run.
Population<T> Brush::Engine< T >::pop
population of programs
Referenced by Brush::Engine< T >::init, Brush::Engine< T >::predict_archive, Brush::Engine< T >::predict_proba_archive, Brush::Engine< T >::run, Brush::Engine< T >::update_best.
Selection<T> Brush::Engine< T >::selector
selection algorithm
Referenced by Brush::Engine< T >::init.
Evaluation<T> Brush::Engine< T >::evaluator
evaluation code
Referenced by Brush::Engine< T >::init, Brush::Engine< T >::run.
Variation<T> Brush::Engine< T >::variator
variation operators
Referenced by Brush::Engine< T >::init, Brush::Engine< T >::run.
Selection<T> Brush::Engine< T >::survivor
survival algorithm
Referenced by Brush::Engine< T >::init, Brush::Engine< T >::run.
Log_Stats Brush::Engine< T >::stats
runtime stats
Referenced by Brush::Engine< T >::init, Brush::Engine< T >::print_stats.
Timer Brush::Engine< T >::timer
start time of training
Referenced by Brush::Engine< T >::init, Brush::Engine< T >::print_stats, Brush::Engine< T >::run.
bool Brush::Engine< T >::is_fitted
keeps track of whether fit was called.
Brush::Engine< T >::Engine(const Parameters &p=Parameters())
Brush::Engine< T >::~Engine()
void Brush::Engine< T >::print_progress(float percentage)
References Brush::Util::PBSTR, Brush::Util::PBWIDTH.
Referenced by Brush::Engine< T >::run.
void Brush::Engine< T >::calculate_stats()
References Brush::Engine< T >::params.
Referenced by Brush::Engine< T >::run.
void Brush::Engine< T >::print_stats(std::ofstream &log, float fraction)
References Brush::Engine< T >::params, Brush::Engine< T >::stats, Brush::Engine< T >::timer.
Referenced by Brush::Engine< T >::run.
void Brush::Engine< T >::log_stats(std::ofstream &log)
References Brush::Engine< T >::params.
Referenced by Brush::Engine< T >::run.
Parameters & Brush::Engine< T >::get_params()
void Brush::Engine< T >::set_params(Parameters &p)
bool Brush::Engine< T >::get_is_fitted()
bool Brush::Engine< T >::update_best(const Dataset &data, bool val=false)
updates best score by searching in the population for the individual that best fits the given data
References Brush::Engine< T >::best_complexity, Brush::Engine< T >::best_ind, Brush::Engine< T >::params, Brush::Engine< T >::pop, Brush::Pop::Individual< T >::weightsMap.
Referenced by Brush::Engine< T >::run.
Individual< T > & Brush::Engine< T >::get_best_ind()
Engine< T > & Brush::Engine< T >::fit(Dataset &data)
Referenced by Brush::Engine< PT::Regressor >::fit.
Engine< T > & Brush::Engine< T >::fit(const Ref< const ArrayXXf > &X, const Ref< const ArrayXf > &y)
auto Brush::Engine< T >::predict(const Dataset &data)
Referenced by Brush::Engine< PT::Regressor >::predict.
auto Brush::Engine< T >::predict(const Ref< const ArrayXXf > &X)
auto Brush::Engine< T >::predict_proba(const Dataset &d)
Referenced by Brush::Engine< PT::Regressor >::predict_proba.
auto Brush::Engine< T >::predict_proba(const Ref< const ArrayXXf > &X)
int Brush::Engine< T >::get_archive_size()
return archive size
vector< json > Brush::Engine< T >::get_archive(bool front)
return population as string
References Brush::Engine< T >::archive, Brush::to_json.
auto Brush::Engine< T >::predict_archive(int id, const Dataset &data)
predict on unseen data from the archive
References Brush::Engine< T >::archive, Brush::Engine< T >::best_ind, Brush::Pop::Individual< T >::id, Brush::Engine< T >::pop, Brush::Pop::Individual< T >::predict, Brush::Util::to_string.
Referenced by Brush::Engine< T >::predict_archive.
auto Brush::Engine< T >::predict_archive(int id, const Ref< const ArrayXXf > &X)
References Brush::Engine< T >::predict_archive.
auto Brush::Engine< T >::predict_proba_archive(int id, const Dataset &data)
References Brush::Engine< T >::archive, Brush::Engine< T >::best_ind, Brush::Pop::Individual< T >::id, Brush::Engine< T >::pop, Brush::Pop::Individual< T >::predict_proba, Brush::Engine< T >::predict_proba_archive, Brush::Util::to_string.
Referenced by Brush::Engine< T >::predict_proba_archive, Brush::Engine< T >::predict_proba_archive.
auto Brush::Engine< T >::predict_proba_archive(int id, const Ref< const ArrayXXf > &X)
References Brush::Engine< T >::predict_proba_archive.
void Brush::Engine< T >::run(Dataset &d)
train the model
References Brush::Engine< T >::archive, Brush::Engine< T >::calculate_stats, Brush::Data::delta, Brush::Engine< T >::evaluator, Brush::Data::Dataset::get_batch, Brush::Engine< T >::init, Brush::Engine< T >::log_stats, Brush::Engine< T >::params, Brush::Engine< T >::pop, Brush::Engine< T >::print_progress, Brush::Engine< T >::print_stats, Brush::Engine< T >::ss, Brush::Engine< T >::survivor, Brush::Engine< T >::timer, Brush::Engine< T >::update_best, Brush::Data::Dataset::use_batch, Brush::Engine< T >::variator.
Referenced by Brush::Engine< PT::Regressor >::fit.
void Brush::Engine< T >::init()
initialize Feat object for fitting.
References Brush::Engine< T >::archive, Brush::Engine< T >::best_complexity, Brush::Engine< T >::best_score, Brush::Engine< T >::evaluator, MAX_FLT, Brush::Engine< T >::params, Brush::Engine< T >::pop, Brush::Util::r, Brush::Engine< T >::selector, Brush::Engine< T >::set_is_fitted, Brush::Engine< T >::ss, Brush::Engine< T >::stats, Brush::Engine< T >::survivor, Brush::Engine< T >::timer, Brush::Engine< T >::variator.
Referenced by Brush::Engine< T >::run.
void Brush::Engine< T >::set_is_fitted(bool f)
set flag indicating whether fit has been called
Referenced by Brush::Engine< T >::init.