Brush::Fitness
float Brush::Fitness::loss
aggregate loss score
Referenced by Brush::from_json, get_loss, set_loss, Brush::to_json.
float Brush::Fitness::loss_v
aggregate validation loss score
Referenced by Brush::from_json, get_loss_v, set_loss_v, Brush::to_json.
unsigned int Brush::Fitness::complexity
Referenced by Brush::from_json, get_complexity, set_complexity, Brush::Pop::Archive< T >::sortComplexity, Brush::to_json.
unsigned int Brush::Fitness::linear_complexity
Referenced by Brush::from_json, get_linear_complexity, set_linear_complexity, Brush::Pop::Archive< T >::sortLinearComplexity, Brush::to_json.
unsigned int Brush::Fitness::size
Referenced by Brush::from_json, get_size, set_size, Brush::to_json.
unsigned int Brush::Fitness::depth
Referenced by Brush::from_json, get_depth, set_depth, Brush::to_json.
float Brush::Fitness::prev_loss
Referenced by Brush::from_json, get_prev_loss, set_loss, Brush::to_json.
float Brush::Fitness::prev_loss_v
Referenced by Brush::from_json, get_prev_loss_v, set_loss_v, Brush::to_json.
unsigned int Brush::Fitness::prev_complexity
Referenced by Brush::from_json, get_prev_complexity, set_complexity, Brush::to_json.
unsigned int Brush::Fitness::prev_linear_complexity
Referenced by Brush::from_json, get_prev_linear_complexity, set_linear_complexity, Brush::to_json.
unsigned int Brush::Fitness::prev_size
Referenced by Brush::from_json, get_prev_size, set_size, Brush::to_json.
unsigned int Brush::Fitness::prev_depth
Referenced by Brush::from_json, get_prev_depth, set_depth, Brush::to_json.
unsigned int Brush::Fitness::dcounter
number of individuals this dominates
Referenced by Brush::from_json, get_dcounter, set_dcounter, Brush::to_json.
vector<unsigned int> Brush::Fitness::dominated
individual indices this dominates
Referenced by Brush::Sel::NSGA2< T >::fast_nds, Brush::from_json, get_dominated, set_dominated, Brush::to_json.
unsigned int Brush::Fitness::rank
pareto front rank
Referenced by Brush::from_json, get_rank, set_rank, Brush::to_json.
float Brush::Fitness::crowding_dist
crowding distance on the Pareto front
Referenced by Brush::from_json, get_crowding_dist, set_crowding_dist, Brush::to_json, Brush::Sel::NSGA2< T >::tournament.
vector<float> Brush::Fitness::values
Referenced by Brush::from_json, get_values, repr, set_values, Brush::to_json, toString.
vector<float> Brush::Fitness::weights
Referenced by Brush::from_json, get_weights, set_values, set_weights, Brush::to_json.
vector<float> Brush::Fitness::wvalues
Referenced by clearValues, Brush::from_json, get_wvalues, hash, operator<, operator==, set_values, Brush::Pop::Archive< T >::sortObj1, Brush::to_json, valid.
void Brush::Fitness::set_dominated(vector< unsigned int > &dom)
References dominated.
vector< unsigned int > Brush::Fitness::get_dominated() const
References dominated.
void Brush::Fitness::set_loss(float f)
References loss, prev_loss.
Referenced by Brush::Eval::Evaluation< T >::assign_fit, bind_fitness, Brush::Eval::Evaluation< T >::update_fitness, Brush::Var::Variation< T >::vary, Brush::Var::Variation< T >::vary_and_update.
float Brush::Fitness::get_loss() const
References loss.
Referenced by bind_fitness, Brush::Var::Variation< T >::vary, Brush::Var::Variation< T >::vary_and_update.
float Brush::Fitness::get_prev_loss() const
References prev_loss.
Referenced by Brush::Var::Variation< T >::vary_and_update.
void Brush::Fitness::set_loss_v(float f_v)
References loss_v, prev_loss_v.
Referenced by Brush::Eval::Evaluation< T >::assign_fit, bind_fitness, Brush::Eval::Evaluation< T >::update_fitness, Brush::Var::Variation< T >::vary, Brush::Var::Variation< T >::vary_and_update.
float Brush::Fitness::get_loss_v() const
References loss_v.
Referenced by bind_fitness, Brush::Var::Variation< T >::vary, Brush::Var::Variation< T >::vary_and_update.
float Brush::Fitness::get_prev_loss_v() const
References prev_loss_v.
void Brush::Fitness::set_size(unsigned int new_s)
References prev_size, size.
Referenced by Brush::Eval::Evaluation< T >::assign_fit, bind_fitness, Brush::Var::Variation< T >::vary, Brush::Var::Variation< T >::vary_and_update.
unsigned int Brush::Fitness::get_size() const
References size.
Referenced by bind_fitness, Brush::Var::Variation< T >::vary, Brush::Var::Variation< T >::vary_and_update.
unsigned int Brush::Fitness::get_prev_size() const
References prev_size.
Referenced by Brush::Var::Variation< T >::vary_and_update.
void Brush::Fitness::set_complexity(unsigned int new_c)
References complexity, prev_complexity.
Referenced by Brush::Eval::Evaluation< T >::assign_fit, bind_fitness, Brush::Var::Variation< T >::vary, Brush::Var::Variation< T >::vary_and_update.
unsigned int Brush::Fitness::get_complexity() const
References complexity.
Referenced by bind_fitness, Brush::Var::Variation< T >::vary, Brush::Var::Variation< T >::vary_and_update.
unsigned int Brush::Fitness::get_prev_complexity() const
References prev_complexity.
Referenced by Brush::Var::Variation< T >::vary_and_update.
void Brush::Fitness::set_linear_complexity(unsigned int new_lc)
References linear_complexity, prev_linear_complexity.
Referenced by Brush::Eval::Evaluation< T >::assign_fit, bind_fitness, Brush::Var::Variation< T >::vary, Brush::Var::Variation< T >::vary_and_update.
unsigned int Brush::Fitness::get_linear_complexity() const
References linear_complexity.
Referenced by bind_fitness, Brush::Var::Variation< T >::vary, Brush::Var::Variation< T >::vary_and_update.
unsigned int Brush::Fitness::get_prev_linear_complexity() const
References prev_linear_complexity.
Referenced by Brush::Var::Variation< T >::vary_and_update.
void Brush::Fitness::set_depth(unsigned int new_d)
References depth, prev_depth.
Referenced by Brush::Eval::Evaluation< T >::assign_fit, bind_fitness, Brush::Var::Variation< T >::vary, Brush::Var::Variation< T >::vary_and_update.
unsigned int Brush::Fitness::get_depth() const
References depth.
Referenced by bind_fitness, Brush::Var::Variation< T >::vary, Brush::Var::Variation< T >::vary_and_update.
unsigned int Brush::Fitness::get_prev_depth() const
References prev_depth.
Referenced by Brush::Var::Variation< T >::vary_and_update.
void Brush::Fitness::set_dcounter(unsigned int d)
References dcounter.
unsigned int Brush::Fitness::get_dcounter() const
References dcounter.
void Brush::Fitness::set_rank(unsigned r)
References Brush::Util::r, rank.
Referenced by bind_fitness.
size_t Brush::Fitness::get_rank() const
References rank.
Referenced by bind_fitness.
void Brush::Fitness::set_crowding_dist(float cd)
References crowding_dist.
Referenced by bind_fitness.
float Brush::Fitness::get_crowding_dist() const
References crowding_dist.
Referenced by bind_fitness.
Brush::Fitness::Fitness(const vector< float > &w={})
Referenced by dominates, operator!=, operator<, operator<=, operator==, operator>, operator>=.
size_t Brush::Fitness::hash() const
References wvalues.
Referenced by bind_fitness.
void Brush::Fitness::set_weights(vector< float > &w)
References weights.
vector< float > Brush::Fitness::get_weights() const
References weights.
Referenced by bind_fitness.
vector< float > Brush::Fitness::get_values() const
References values.
Referenced by bind_fitness.
vector< float > Brush::Fitness::get_wvalues() const
References wvalues.
Referenced by bind_fitness, dominates.
void Brush::Fitness::set_values(vector< float > &v)
References values, weights, wvalues.
Referenced by Brush::Eval::Evaluation< T >::assign_fit, bind_fitness.
void Brush::Fitness::clearValues()
References wvalues.
Referenced by bind_fitness.
bool Brush::Fitness::valid() const
References wvalues.
Referenced by bind_fitness, repr, toString, Brush::Var::Variation< T >::vary, Brush::Var::Variation< T >::vary_and_update.
bool Brush::Fitness::operator==(const Fitness &other) const
References Fitness, wvalues.
bool Brush::Fitness::operator!=(const Fitness &other) const
References Fitness.
bool Brush::Fitness::operator<(const Fitness &other) const
References Fitness, wvalues.
bool Brush::Fitness::operator>(const Fitness &other) const
References Fitness.
bool Brush::Fitness::operator<=(const Fitness &other) const
References Fitness.
bool Brush::Fitness::operator>=(const Fitness &other) const
References Fitness.
std::string Brush::Fitness::toString() const
References Brush::Util::to_string, valid, values.
Referenced by bind_fitness, Brush::Pop::Population< T >::print_models.
std::string Brush::Fitness::repr() const
References Brush::Util::to_string, valid, values.
Referenced by bind_fitness.
int Brush::Fitness::dominates(const Fitness &b) const
set obj vector given a string of objective names
References Fitness, get_wvalues.
Referenced by bind_fitness, Brush::Pop::Population< T >::hall_of_fame, Brush::Sel::NSGA2< T >::tournament.