module.cpp
STRINGIFY
MACRO_STRINGIFY
Referenced by PYBIND11_MODULE.
void bind_params(py::module &)
References Brush::Parameters::get_bandit, Brush::Parameters::get_batch_size, Brush::Parameters::get_class_weights, Brush::Parameters::get_classification, Brush::Parameters::get_constants_simplification, Brush::Parameters::get_current_gen, Brush::Parameters::get_cx_prob, Brush::Parameters::get_feature_names, Brush::Parameters::get_functions, Brush::Parameters::get_inexact_simplification, Brush::Parameters::get_load_population, Brush::Parameters::get_logfile, Brush::Parameters::get_max_depth, Brush::Parameters::get_max_gens, Brush::Parameters::get_max_size, Brush::Parameters::get_max_stall, Brush::Parameters::get_max_time, Brush::Parameters::get_mig_prob, Brush::Parameters::get_mutation_probs, Brush::Parameters::get_n_classes, Brush::Parameters::get_n_jobs, Brush::Parameters::get_num_islands, Brush::Parameters::get_objectives, Brush::Parameters::get_pop_size, Brush::Parameters::get_random_state, Brush::Parameters::get_sample_weights, Brush::Parameters::get_save_population, Brush::Parameters::get_scorer, Brush::Parameters::get_sel, Brush::Parameters::get_shuffle_split, Brush::Parameters::get_surv, Brush::Parameters::get_use_arch, Brush::Parameters::get_val_from_arch, Brush::Parameters::get_validation_size, Brush::Parameters::get_verbosity, Brush::Parameters::get_weights_init, Brush::Util::Rnd::initRand, Brush::Util::r, Brush::Parameters::set_bandit, Brush::Parameters::set_batch_size, Brush::Parameters::set_class_weights, Brush::Parameters::set_classification, Brush::Parameters::set_constants_simplification, Brush::Parameters::set_current_gen, Brush::Parameters::set_cx_prob, Brush::Parameters::set_feature_names, Brush::Parameters::set_functions, Brush::Parameters::set_inexact_simplification, Brush::Parameters::set_load_population, Brush::Parameters::set_logfile, Brush::Parameters::set_max_depth, Brush::Parameters::set_max_gens, Brush::Parameters::set_max_size, Brush::Parameters::set_max_stall, Brush::Parameters::set_max_time, Brush::Parameters::set_mig_prob, Brush::Parameters::set_mutation_probs, Brush::Parameters::set_n_classes, Brush::Parameters::set_n_jobs, Brush::Parameters::set_num_islands, Brush::Parameters::set_objectives, Brush::Parameters::set_pop_size, Brush::Parameters::set_random_state, Brush::Parameters::set_sample_weights, Brush::Parameters::set_save_population, Brush::Parameters::set_scorer, Brush::Parameters::set_sel, Brush::Parameters::set_shuffle_split, Brush::Parameters::set_surv, Brush::Parameters::set_use_arch, Brush::Parameters::set_val_from_arch, Brush::Parameters::set_validation_size, Brush::Parameters::set_verbosity, Brush::Parameters::set_weights_init.
Referenced by PYBIND11_MODULE.
void bind_dataset(py::module &)
References Brush::Data::Dataset::get_batch, Brush::Data::Dataset::get_batch_size, Brush::Data::Dataset::get_n_features, Brush::Data::Dataset::get_n_samples, Brush::Data::Dataset::get_training_data, Brush::Data::Dataset::get_validation_data, Brush::Data::Dataset::get_X, Brush::Data::Dataset::print, Brush::Data::read_csv, Brush::Data::Dataset::set_batch_size, Brush::Data::Dataset::split, Brush::Data::Dataset::y.
Referenced by PYBIND11_MODULE.
void bind_search_space(py::module &)
References Brush::SearchSpace::make_classifier, Brush::SearchSpace::make_multiclass_classifier, Brush::SearchSpace::make_regressor, Brush::SearchSpace::make_representer, Brush::SearchSpace::print, Brush::SearchSpace::repr, Brush::SS.
Referenced by PYBIND11_MODULE.
void bind_fitness(py::module &)
References Brush::Fitness::clearValues, Brush::Fitness::dominates, Brush::Fitness::get_complexity, Brush::Fitness::get_crowding_dist, Brush::Fitness::get_depth, Brush::Fitness::get_linear_complexity, Brush::Fitness::get_loss, Brush::Fitness::get_loss_v, Brush::Fitness::get_rank, Brush::Fitness::get_size, Brush::Fitness::get_values, Brush::Fitness::get_weights, Brush::Fitness::get_wvalues, Brush::Fitness::hash, Brush::Fitness::repr, Brush::Fitness::set_complexity, Brush::Fitness::set_crowding_dist, Brush::Fitness::set_depth, Brush::Fitness::set_linear_complexity, Brush::Fitness::set_loss, Brush::Fitness::set_loss_v, Brush::Fitness::set_rank, Brush::Fitness::set_size, Brush::Fitness::set_values, Brush::Fitness::toString, Brush::Fitness::valid.
Referenced by PYBIND11_MODULE.
void bind_programs(py::module &)
References bind_program.
Referenced by PYBIND11_MODULE.
void bind_evaluators(py::module &)
References bind_evaluator.
Referenced by PYBIND11_MODULE.
void bind_individuals(py::module &)
References bind_individual.
Referenced by PYBIND11_MODULE.
void bind_variations(py::module &)
References bind_variation.
Referenced by PYBIND11_MODULE.
void bind_selections(py::module &)
References bind_selection.
Referenced by PYBIND11_MODULE.
void bind_engines(py::module &)
References bind_engine.
Referenced by PYBIND11_MODULE.
PYBIND11_MODULE(_brush, m)
References bind_dataset, bind_engines, bind_evaluators, bind_fitness, bind_individuals, bind_params, bind_programs, bind_search_space, bind_selections, bind_variations, MACRO_STRINGIFY.