Brush::DispatchTable
using Brush::DispatchTable< Fit >::Callable = typename std::conditional_t<Fit, std::function<T(const Data::Dataset&, TreeNode&)>, std::function<T(const Data::Dataset&, TreeNode&, const typename WeightType<T>::type**)> >
using Brush::DispatchTable< Fit >::CallVariant = std::variant< Callable<ArrayXb>, Callable<ArrayXi>, Callable<ArrayXf>, Callable<ArrayXXb>, Callable<ArrayXXi>, Callable<ArrayXXf>, Callable<TimeSeriesb>, Callable<TimeSeriesi>, Callable<TimeSeriesf>, Callable<ArrayXbJet>, Callable<ArrayXiJet>, Callable<ArrayXfJet>, Callable<ArrayXXbJet>, Callable<ArrayXXiJet>, Callable<ArrayXXfJet>, Callable<Data::TimeSeriesbJet>, Callable<Data::TimeSeriesiJet>, Callable<Data::TimeSeriesfJet> >
using Brush::DispatchTable< Fit >::SigMap = std::unordered_map<std::size_t,CallVariant>
maps Signature hashes -> Dispatch Operator
using Brush::DispatchTable< Fit >::DTMap = std::unordered_map<NodeType, SigMap>
maps NodeTypes -> Signature hash -> Dispatch Operator
DTMap Brush::DispatchTable< Fit >::map_
Referenced by Brush::DispatchTable< Fit >::DispatchTable, Brush::DispatchTable< Fit >::Get, Brush::DispatchTable< Fit >::InitMap, Brush::DispatchTable< Fit >::operator=, Brush::DispatchTable< Fit >::operator=, Brush::DispatchTable< Fit >::print.
void Brush::DispatchTable< Fit >::InitMap(std::index_sequence< Is... >)
References Brush::Is, Brush::DispatchTable< Fit >::MakeOperators, Brush::DispatchTable< Fit >::map_.
Referenced by Brush::DispatchTable< Fit >::DispatchTable.
SigMap Brush::DispatchTable< Fit >::MakeOperators()
References Brush::DispatchTable< Fit >::AddOperator.
Referenced by Brush::DispatchTable< Fit >::InitMap.
static constexpr auto Brush::DispatchTable< Fit >::AddOperator(std::index_sequence< Is... >)
References is_in_v, Brush::DispatchTable< Fit >::MakeCallable.
Referenced by Brush::DispatchTable< Fit >::MakeOperators.
static constexpr auto Brush::DispatchTable< Fit >::MakeCallable()
References Brush::DispatchOp.
Referenced by Brush::DispatchTable< Fit >::AddOperator.
Brush::DispatchTable< Fit >::DispatchTable()
References Brush::DispatchTable< Fit >::InitMap.
Referenced by Brush::DispatchTable< Fit >::DispatchTable, Brush::DispatchTable< Fit >::DispatchTable, Brush::DispatchTable< Fit >::operator=, Brush::DispatchTable< Fit >::operator=.
void Brush::DispatchTable< Fit >::print()
References Brush::DispatchTable< Fit >::map_.
Brush::DispatchTable< Fit >::~DispatchTable()=default
DispatchTable & Brush::DispatchTable< Fit >::operator=(DispatchTable const &other)
References Brush::DispatchTable< Fit >::DispatchTable, Brush::DispatchTable< Fit >::map_.
DispatchTable & Brush::DispatchTable< Fit >::operator=(DispatchTable &&other) noexcept
References Brush::DispatchTable< Fit >::DispatchTable, Brush::DispatchTable< Fit >::map_.
Brush::DispatchTable< Fit >::DispatchTable(DispatchTable const &other)
References Brush::DispatchTable< Fit >::DispatchTable, Brush::DispatchTable< Fit >::map_.
Brush::DispatchTable< Fit >::DispatchTable(DispatchTable &&other) noexcept
References Brush::DispatchTable< Fit >::DispatchTable.
Callable< T > const & Brush::DispatchTable< Fit >::Get(NodeType n, std::size_t sig_hash) const
References HANDLE_ERROR_THROW, Brush::DispatchTable< Fit >::map_.