Brush::Simpl::Inexact_simplifier
int Brush::Simpl::Inexact_simplifier::inputDim
Referenced by hash, init.
std::unordered_map<DataType, HashStorage> Brush::Simpl::Inexact_simplifier::equivalentExpressions
Referenced by index, init, log_simplification_table, query.
vector<MatrixXf> Brush::Simpl::Inexact_simplifier::uniformPlanes
Referenced by hash, init.
void Brush::Simpl::Inexact_simplifier::init(int hashSize, const Dataset &data, int numPlanes)
References equivalentExpressions, Brush::Data::Dataset::get_n_samples, Brush::Data::Dataset::get_training_data, inputDim, uniformPlanes, Brush::Data::Dataset::unique_data_types.
void Brush::Simpl::Inexact_simplifier::analyze_tree(Program< P > &program, const SearchSpace &ss, const Dataset &d)
References index, Brush::Isnt, Brush::Program< PType >::size_at, Brush::Program< PType >::Tree.
Referenced by simplify_tree.
Program< P > Brush::Simpl::Inexact_simplifier::simplify_tree(Program< P > &program, const SearchSpace &ss, const Dataset &d)
References analyze_tree, Brush::Isnt, Brush::Program< PType >::predict, query, Brush::Program< PType >::Tree.
Brush::Simpl::Inexact_simplifier::Inexact_simplifier()
Brush::Simpl::Inexact_simplifier::~Inexact_simplifier()
void Brush::Simpl::Inexact_simplifier::index(TreeIter &spot, const Dataset &d)
References equivalentExpressions, hash.
Referenced by analyze_tree.
void Brush::Simpl::Inexact_simplifier::log_simplification_table(std::ofstream &log)
References dt_to_string, equivalentExpressions, Brush::Simpl::HashStorage::print.
vector< size_t > Brush::Simpl::Inexact_simplifier::hash(TreeIter &spot, const Dataset &d)
References Brush::ArrayB, Brush::ArrayI, inputDim, Brush::Regressor, Brush::Representer, uniformPlanes.
Referenced by index, query.
optional< vector< tree< Node > > > Brush::Simpl::Inexact_simplifier::query(TreeIter &spot, const Dataset &d)
References equivalentExpressions, hash.
Referenced by simplify_tree.
string Brush::Simpl::Inexact_simplifier::dt_to_string(DataType dt)
References Brush::ArrayB, Brush::ArrayBJet, Brush::ArrayF, Brush::ArrayFJet, Brush::ArrayI, Brush::ArrayIJet, Brush::MatrixB, Brush::MatrixBJet, Brush::MatrixF, Brush::MatrixFJet, Brush::MatrixI, Brush::MatrixIJet, Brush::TimeSeriesB, Brush::TimeSeriesBJet, Brush::TimeSeriesF, Brush::TimeSeriesFJet, Brush::TimeSeriesI, Brush::TimeSeriesIJet.
Referenced by log_simplification_table.