Brush::Data
TimeValues
StringFeatures
typedef TimeSeries<bool> Brush::Data::TimeSeriesb
TimeSeries convenience typedefs.
typedef TimeSeries<int> Brush::Data::TimeSeriesi
typedef TimeSeries<float> Brush::Data::TimeSeriesf
typedef TimeSeries<bJet> Brush::Data::TimeSeriesbJet
typedef TimeSeries<iJet> Brush::Data::TimeSeriesiJet
typedef TimeSeries<fJet> Brush::Data::TimeSeriesfJet
typedef std::variant< ArrayXb, ArrayXi, ArrayXf, ArrayXXb, ArrayXXi, ArrayXXf, TimeSeriesb, TimeSeriesi, TimeSeriesf, ArrayXbJet, ArrayXiJet, ArrayXfJet, ArrayXXbJet, ArrayXXiJet, ArrayXXfJet, TimeSeriesbJet, TimeSeriesiJet, TimeSeriesfJet > Brush::Data::State
defines the possible types of data flowing thru nodes.
std::vector<DataType> Brush::Data::StateTypes
Referenced by StateType.
DataType Brush::Data::StateType(const State &arg)
References bind_engine, StateTypes.
Referenced by Brush::Data::Dataset::init.
State Brush::Data::check_type(const ArrayXf &x)
determines data types of columns of matrix X.
References bind_engine.
Referenced by Brush::Data::Dataset::make_features, read_csv.
State Brush::Data::cast_type(const ArrayXf &x, const StateRef &x_ref)
References bind_engine.
Referenced by Brush::Data::Dataset::copy_and_make_features.
ostream & Brush::Data::operator<<(ostream &os, DataType dt)
References bind_engine, Brush::DataTypeName.
Dataset Brush::Data::read_csv(const std::string &path, const std::string &target, char sep)
read csv file into Data.
References bind_engine, check_type, HANDLE_ERROR_THROW, Brush::Util::trim.