variation
typedef tree<Node>::pre_order_iterator variation::Iter
bool variation::point_mutation(tree< Node > &Tree, Iter spot, const SearchSpace &SS)
replace node with same typed node
Tree the program tree spot an iterator to the node that is being mutated SS the search space to sample a node like spot boolean indicating the success (true) or fail (false) of the operation
References Brush::SearchSpace::get_node_like, Brush::SS.
Referenced by mutate.
bool variation::insert_mutation(tree< Node > &Tree, Iter spot, const SearchSpace &SS)
insert a node with spot as a child
Tree the program tree spot an iterator to the node that is being mutated SS the search space to sample a node like spot boolean indicating the success (true) or fail (false) of the operation
References Brush::PARAMS, Brush::SearchSpace::sample_op_with_arg, Brush::SearchSpace::sample_terminal, Brush::SS.
Referenced by mutate.
bool variation::delete_mutation(tree< Node > &Tree, Iter spot, const SearchSpace &SS)
delete subtree and replace it with a terminal of the same return type
Tree the program tree spot an iterator to the node that is being mutated SS the search space to sample a node like spot boolean indicating the success (true) or fail (false) of the operation
References Brush::SearchSpace::sample_terminal, Brush::SS.
Referenced by mutate.
bool variation::toggle_weight_on_mutation(tree< Node > &Tree, Iter spot, const SearchSpace &SS)
toggle the node's weight ON.
Tree the program tree spot an iterator to the node that is being mutated SS the search space (unused) boolean indicating the success (true) or fail (false) of the operation
References Brush::IsWeighable.
Referenced by mutate.
bool variation::toggle_weight_off_mutation(tree< Node > &Tree, Iter spot, const SearchSpace &SS)
toggle the node's weight OFF.
Tree the program tree spot an iterator to the node that is being mutated SS the search space (unused) boolean indicating the success (true) or fail (false) of the operation
Referenced by mutate.
bool variation::subtree_mutation(tree< Node > &Tree, Iter spot, const SearchSpace &SS)
replaces the subtree rooted in spot
Tree the program tree spot an iterator to the node that is being mutated SS the search space to generate a compatible subtree boolean indicating the success (true) or fail (false) of the operation
References Brush::PARAMS, Brush::SearchSpace::sample_subtree, Brush::SS.
Referenced by mutate.
std::optional<Program<T> > variation::mutate(const Program< T > &parent, const SearchSpace &SS)
Stochastically mutate a program.
Types of mutation: point mutation changes a single node. insertion mutation inserts a node as the parent of an existing node, and fills in the other arguments. deletion mutation deletes a node. subtree mutation inserts a new subtree into the program. toggle_weight_on mutation turns a node's weight ON. toggle_weight_off mutation turns a node's weight OFF. Every mutation has a probability (weight) based on global parameters. The spot where the mutation will take place is sampled based on attribute get_prob_change of each node in the tree. Inside each type of mutation, when a new node is inserted, it is sampled based on terminal_weights. Due to the stochastic behavior, and the several sampling steps, it may come to a case where the search space does not hold any possible modification to do in the program. In this case, the method returns std::nullopt (and has overloads so it can be used in a boolean context). If the mutation succeeds, the mutated program can be accessed through the .value() attribute of the std::optional. This means that, if you use the mutation as auto opt = mutate(parent, SS), either opt==false or opt.value() contains the child program. T program type parent the program to be mutated SS a search space std::optional that may contain the child program of type T
References delete_mutation, HANDLE_ERROR_THROW, insert_mutation, Brush::PARAMS, point_mutation, Brush::Util::r, Brush::Util::Rnd::random_choice, Brush::Util::Rnd::select_randomly, Brush::SS, subtree_mutation, toggle_weight_off_mutation, toggle_weight_on_mutation, Brush::util::weights.
Referenced by bind_program, Brush::Program< PType >::mutate.
std::optional<Program<T> > variation::cross(const Program< T > &root, const Program< T > &other)
Stochastically swaps subtrees between root and other, returning a new program.
The spot where the cross will take place in the root parent is sampled based on attribute get_prob_change of each node in the tree. After selecting the cross spot, the program will iterate through the other parent searching for all compatible sub-trees to replace. Due to the stochastic behavior, it may come to a case where there is no candidate to replace the spot node. In this case, the method returns std::nullopt (and has overloads so it can be used in a boolean context). If the cross succeeds, the child program can be accessed through the .value() attribute of the std::optional. This means that, if you use the cross as auto opt = mutate(parent, SS), either opt==false or opt.value() contains the child. T the program type root the root parent other the donating parent std::optional that may contain the child program of type T
References Brush::PARAMS, Brush::Util::r, Brush::Util::Rnd::select_randomly.
Referenced by bind_program, Brush::Program< PType >::cross.