Brush::Pop::Population
size_t Brush::Pop::Population< T >::pop_size
Referenced by Brush::Pop::Population< T >::add_offspring_indexes, Brush::Pop::Population< T >::init, Brush::Pop::Population< T >::init, Brush::Pop::Population< T >::migrate, Brush::Pop::Population< T >::Population, Brush::Pop::Population< T >::update.
int Brush::Pop::Population< T >::num_islands
Referenced by Brush::Pop::Population< T >::add_offspring_indexes, Brush::Pop::Population< T >::hall_of_fame, Brush::Pop::Archive< T >::init, Brush::Pop::Population< T >::init, Brush::Pop::Population< T >::init, Brush::Pop::Population< T >::migrate, Brush::Pop::Population< T >::Population, Brush::Pop::Population< T >::print_models, Brush::Pop::Population< T >::sorted_front, Brush::Pop::Archive< T >::update, Brush::Pop::Population< T >::update.
float Brush::Pop::Population< T >::mig_prob
Referenced by Brush::Pop::Population< T >::init, Brush::Pop::Population< T >::init, Brush::Pop::Population< T >::migrate, Brush::Pop::Population< T >::Population.
bool Brush::Pop::Population< T >::linear_complexity
Indicates if the user set linear_complexity instead of recursive complexity.
Referenced by Brush::Pop::Population< T >::hall_of_fame, Brush::Pop::Population< T >::init, Brush::Pop::Population< T >::init, Brush::Pop::Population< T >::Population, Brush::Pop::Population< T >::sorted_front.
vector<std::shared_ptr<Individual<T> > > Brush::Pop::Population< T >::individuals
Referenced by Brush::Sel::NSGA2< T >::crowding_distance, Brush::Sel::NSGA2< T >::fast_nds, Brush::Pop::Population< T >::hall_of_fame, Brush::Pop::Archive< T >::init, Brush::Pop::Population< T >::init, Brush::Pop::Population< T >::init, Brush::Pop::Population< T >::migrate, Brush::Pop::Population< T >::operator[], Brush::Pop::Population< T >::operator[], Brush::Pop::Population< T >::Population, Brush::Pop::Population< T >::print_models, Brush::Sel::Lexicase< T >::select, Brush::Pop::Population< T >::size, Brush::Pop::Population< T >::sorted_front, Brush::Pop::Archive< T >::update, Brush::Pop::Population< T >::update, Brush::Eval::Evaluation< T >::update_fitness, Brush::Var::Variation< T >::vary, Brush::Var::Variation< T >::vary_and_update.
vector<vector<size_t> > Brush::Pop::Population< T >::island_indexes
Referenced by Brush::Pop::Population< T >::add_offspring_indexes, Brush::Pop::Population< T >::get_island_indexes, Brush::Pop::Population< T >::hall_of_fame, Brush::Pop::Population< T >::init, Brush::Pop::Population< T >::init, Brush::Pop::Population< T >::migrate, Brush::Pop::Population< T >::print_models, Brush::Pop::Population< T >::sorted_front, Brush::Pop::Population< T >::update.
Brush::Pop::Population< T >::Population()
References Brush::Pop::Population< T >::individuals, Brush::Pop::Population< T >::linear_complexity, Brush::Pop::Population< T >::mig_prob, Brush::Pop::Population< T >::num_islands, Brush::Pop::Population< T >::pop_size.
Referenced by Brush::Pop::Population< T >::SameFitComplexity::SameFitComplexity, Brush::Pop::Population< T >::SortComplexity::SortComplexity, Brush::Pop::Population< T >::SortLinearComplexity::SortLinearComplexity.
Brush::Pop::Population< T >::~Population()
void Brush::Pop::Population< T >::init(SearchSpace &ss, const Parameters &params)
initialize population of programs with a starting model and/or from file
References Brush::Data::delta, Brush::Util::in, Brush::Pop::Population< T >::individuals, Brush::Pop::Population< T >::island_indexes, Brush::Pop::Population< T >::linear_complexity, Brush::Parameters::mig_prob, Brush::Pop::Population< T >::mig_prob, Brush::Parameters::num_islands, Brush::Pop::Population< T >::num_islands, Brush::Parameters::objectives, Brush::Parameters::pop_size, Brush::Pop::Population< T >::pop_size.
void Brush::Pop::Population< T >::init(vector< Individual< T > > &individuals, const Parameters &params)
References Brush::Data::delta, Brush::Util::in, Brush::Pop::Population< T >::individuals, Brush::Pop::Population< T >::island_indexes, Brush::Pop::Population< T >::linear_complexity, Brush::Parameters::mig_prob, Brush::Pop::Population< T >::mig_prob, Brush::Parameters::num_islands, Brush::Pop::Population< T >::num_islands, Brush::Parameters::objectives, Brush::Parameters::pop_size, Brush::Pop::Population< T >::pop_size, Brush::Util::to_string.
void Brush::Pop::Population< T >::save(string filename)
References Brush::Util::logger, Brush::Pop::to_json.
void Brush::Pop::Population< T >::load(string filename)
References Brush::Pop::from_json, HANDLE_ERROR_THROW, Brush::Util::logger, Brush::Pop::Population< T >::size, Brush::Util::to_string.
int Brush::Pop::Population< T >::size()
returns population size (the effective size of the individuals)
References Brush::Pop::Population< T >::individuals.
Referenced by Brush::Pop::Population< T >::load, Brush::Pop::Population< T >::migrate, Brush::Pop::Population< T >::print_models, Brush::Pop::Population< T >::update.
vector< size_t > Brush::Pop::Population< T >::get_island_indexes(int island)
References Brush::Pop::Population< T >::island_indexes.
Referenced by Brush::Pop::Archive< T >::init, Brush::Sel::Lexicase< T >::select, Brush::Sel::NSGA2< T >::select, Brush::Sel::NSGA2< T >::survive, Brush::Pop::Archive< T >::update, Brush::Eval::Evaluation< T >::update_fitness, Brush::Var::Variation< T >::vary, Brush::Var::Variation< T >::vary_and_update.
void Brush::Pop::Population< T >::add_offspring_indexes(int island)
update individual vector size, distributing the expressions in num_islands
update individual vector size and island indexes
References Brush::Data::delta, Brush::Pop::Population< T >::island_indexes, Brush::Pop::Population< T >::num_islands, Brush::Pop::Population< T >::pop_size.
void Brush::Pop::Population< T >::update(vector< vector< size_t > > survivors)
reduce programs to the indices in survivors. Not thread safe,as it removes elements
References Brush::Data::delta, Brush::Pop::Population< T >::individuals, Brush::Pop::Population< T >::island_indexes, Brush::Pop::Population< T >::num_islands, Brush::Pop::Population< T >::pop_size, Brush::Pop::Population< T >::size.
const Individual< T > & Brush::Pop::Population< T >::operator[](size_t i) const
setting and getting from individuals vector (will ignore islands)
References Brush::Pop::Population< T >::individuals.
const Individual< T > & Brush::Pop::Population< T >::operator[](size_t i)
References Brush::Pop::Population< T >::individuals.
string Brush::Pop::Population< T >::print_models(string sep="\n")
return population equations.
References Brush::Pop::Individual< T >::fitness, Brush::Pop::Individual< T >::get_model, Brush::Pop::Population< T >::individuals, Brush::Pop::Population< T >::island_indexes, Brush::Pop::Population< T >::num_islands, Brush::Pop::Population< T >::size, Brush::Util::to_string, Brush::Fitness::toString.
vector< vector< size_t > > Brush::Pop::Population< T >::sorted_front(unsigned rank=1)
return complexity-sorted Pareto front indices for each island
References Brush::Pop::Population< T >::individuals, Brush::Pop::Population< T >::island_indexes, Brush::Pop::Population< T >::linear_complexity, Brush::Pop::Population< T >::num_islands.
vector< size_t > Brush::Pop::Population< T >::hall_of_fame(unsigned rank=1)
References Brush::Fitness::dominates, Brush::Pop::Individual< T >::fitness, Brush::Pop::Population< T >::individuals, Brush::Pop::Population< T >::island_indexes, Brush::Pop::Population< T >::linear_complexity, Brush::Pop::Population< T >::num_islands.
void Brush::Pop::Population< T >::migrate()
References Brush::Data::delta, Brush::Pop::Population< T >::individuals, Brush::Pop::Population< T >::island_indexes, Brush::Pop::Population< T >::mig_prob, Brush::Pop::Population< T >::num_islands, Brush::Pop::Population< T >::pop_size, Brush::Util::r, Brush::Pop::Population< T >::size.