Brush::Util::Rnd
vector<std::mt19937> Brush::Util::Rnd::rg
Referenced by random_choice, Rnd, rnd_dbl, rnd_flt, rnd_int, select_randomly, select_randomly, set_seed, shuffle.
Rnd * Brush::Util::Rnd::instance
Referenced by destroy, initRand.
Rnd * Brush::Util::Rnd::initRand()
References instance, Rnd, set_seed.
void Brush::Util::Rnd::destroy()
References bind_engine, instance.
void Brush::Util::Rnd::set_seed(unsigned int seed)
References bind_engine, rg.
Referenced by Brush::Engine< T >::init, initRand.
int Brush::Util::Rnd::rnd_int(int lowerLimit, int upperLimit)
References bind_engine, omp_get_thread_num, rg.
Referenced by Brush::SearchSpace::make_program, Brush::Var::SubtreeMutation::mutate, Brush::RandomDequeue.
float Brush::Util::Rnd::rnd_flt(float min=0.0, float max=1.0)
References bind_engine, omp_get_thread_num, rg.
Referenced by gasdev, operator().
float Brush::Util::Rnd::rnd_dbl(float min=0.0, float max=1.0)
References bind_engine, omp_get_thread_num, rg.
Referenced by operator().
float Brush::Util::Rnd::operator()(unsigned i)
References bind_engine, rnd_dbl.
float Brush::Util::Rnd::operator()()
References rnd_flt.
void Brush::Util::Rnd::shuffle(RandomAccessIterator first, RandomAccessIterator last)
References bind_engine, omp_get_thread_num, rg.
Referenced by Brush::Sel::Lexicase< T >::select, shuffled_index.
vector< size_t > Brush::Util::Rnd::shuffled_index(size_t n)
returns a shuffled index vector of length n
References bind_engine, shuffle.
Referenced by Brush::Data::Dataset::get_batch, Brush::Data::Dataset::init.
Iter Brush::Util::Rnd::select_randomly(Iter start, Iter end)
References bind_engine, omp_get_thread_num, rg.
Referenced by Brush::Var::Variation< T >::cross, Brush::SearchSpace::get_node_like, Brush::Pop::Population< T >::migrate, Brush::Var::Variation< T >::mutate, random_choice, random_choice, Brush::SearchSpace::sample_op, Brush::SearchSpace::sample_op, Brush::SearchSpace::sample_op_with_arg, Brush::SearchSpace::sample_terminal, Brush::SearchSpace::sample_terminal, Brush::Sel::Lexicase< T >::select, Brush::Sel::NSGA2< T >::select, Brush::Var::Variation< T >::vary.
Iter Brush::Util::Rnd::select_randomly(Iter start, Iter end, Iter2 wstart, Iter2 wend)
select randomly with weighted distribution.
References bind_engine, omp_get_thread_num, rg.
T Brush::Util::Rnd::random_choice(const map< T, float > &m)
References bind_engine, select_randomly.
Referenced by Brush::Var::Variation< T >::mutate, random_choice.
T Brush::Util::Rnd::random_choice(const V &v)
References bind_engine, select_randomly.
T Brush::Util::Rnd::random_choice(const C< T, std::allocator< T > > &v, const vector< float > &w)
References bind_engine, omp_get_thread_num, random_choice, rg.
float Brush::Util::Rnd::gasdev()
References bind_engine, rnd_flt.
Brush::Util::Rnd::Rnd()
References omp_get_max_threads, rg.
Referenced by initRand.
Brush::Util::Rnd::~Rnd()