Brush::Var::Variation
SearchSpace Brush::Var::Variation< T >::search_space
Referenced by Brush::Var::Variation< T >::bandit_get_node_like, Brush::Var::Variation< T >::bandit_sample_op, Brush::Var::Variation< T >::bandit_sample_op_with_arg, Brush::Var::Variation< T >::bandit_sample_terminal, Brush::Var::SubtreeMutation::find_spots, Brush::Var::Variation< T >::init, Brush::Var::SubtreeMutation::mutate, Brush::Var::Variation< T >::update_ss, Brush::Var::Variation< T >::Variation, Brush::Var::Variation< T >::vary, Brush::Var::Variation< T >::vary_and_update.
Dataset& Brush::Var::Variation< T >::data
Referenced by Brush::Var::Variation< T >::init, Brush::Var::Variation< T >::Variation, Brush::Var::Variation< T >::vary_and_update.
Parameters Brush::Var::Variation< T >::parameters
Referenced by Brush::Var::Variation< T >::cross, Brush::Var::Variation< T >::init, Brush::Var::Variation< T >::mutate, Brush::Var::Variation< T >::update_ss, Brush::Var::Variation< T >::Variation, Brush::Var::Variation< T >::vary, Brush::Var::Variation< T >::vary_and_update.
Bandit Brush::Var::Variation< T >::variation_bandit
Referenced by Brush::Var::Variation< T >::init, Brush::Var::Variation< T >::update_ss, Brush::Var::Variation< T >::vary_and_update.
map<DataType, Bandit> Brush::Var::Variation< T >::terminal_bandits
Referenced by Brush::Var::Variation< T >::bandit_sample_terminal, Brush::Var::Variation< T >::init, Brush::Var::Variation< T >::update_ss, Brush::Var::Variation< T >::vary_and_update.
map<DataType, map<size_t, Bandit> > Brush::Var::Variation< T >::op_bandits
Referenced by Brush::Var::Variation< T >::bandit_get_node_like, Brush::Var::Variation< T >::bandit_sample_op, Brush::Var::Variation< T >::bandit_sample_op_with_arg, Brush::Var::Variation< T >::init, Brush::Var::Variation< T >::update_ss, Brush::Var::Variation< T >::vary_and_update.
Constants_simplifier Brush::Var::Variation< T >::constants_simplifier
Referenced by Brush::Var::Variation< T >::vary_and_update.
Inexact_simplifier Brush::Var::Variation< T >::inexact_simplifier
Referenced by Brush::Var::Variation< T >::init, Brush::Var::Variation< T >::vary_and_update.
Brush::Var::Variation< T >::Variation()=default
Default constructor.
Brush::Var::Variation< T >::Variation(Parameters &params, SearchSpace &ss, Dataset &d)
Constructor that initializes the Variation object with parameters and search space.
params The parameters for the variation operator. ss The search space for the variation operator.
References Brush::Var::Variation< T >::data, Brush::Var::Variation< T >::init, Brush::Var::Variation< T >::parameters, Brush::Var::Variation< T >::search_space.
Brush::Var::Variation< T >::~Variation()
Destructor.
void Brush::Var::Variation< T >::init()
Initializes the Variation object with parameters and search space.
params The parameters for the variation operator. ss The search space for the variation operator.
References Brush::Var::Variation< T >::data, Brush::Var::Variation< T >::inexact_simplifier, Brush::Var::Variation< T >::op_bandits, Brush::Var::Variation< T >::parameters, Brush::Var::Variation< T >::search_space, Brush::Var::Variation< T >::terminal_bandits, Brush::Var::Variation< T >::variation_bandit.
Referenced by Brush::Var::Variation< T >::Variation.
std::optional< Individual< T > > Brush::Var::Variation< T >::cross(const Individual< T > &mom, const Individual< T > &dad)
Performs croearch_spaceover operation on two individuals.
Stochastically swaps subtrees between root and other, returning a new program. mom The first parent individual. dad The second parent individual. An optional containing the offspring individual if the crossover is successful, or an empty optional otherwise. The spot where the cross will take place in the root parent is sampled based on attribute get_prob_change of each node in the tree. After selecting the cross spot, the program will iterate through the other parent searching for all compatible sub-trees to replace. Due to the stochastic behavior, it may come to a case where there is no candidate to replace the spot node. In this case, the method returns std::nullopt (and has overloads so it can be used in a boolean context). If the cross succeeds, the child program can be accessed through the .value() attribute of the std::optional. TODO: update this documentation (it doesnt take the program but the individual. also update mutation documentation) This means that, if you use the cross as auto opt = mutate(parent, SS), either opt==false or opt.value() contains the child. T the program type root the root parent other the donating parent std::optional that may contain the child program of type T
References Brush::Program< PType >::depth_to_reach, Brush::Var::Variation< T >::parameters, Brush::Pop::Individual< T >::program, Brush::Util::r, Brush::Pop::Individual< T >::set_variation, Brush::Program< PType >::size, Brush::Program< PType >::size_at, Brush::Program< PType >::Tree.
Referenced by Brush::Var::Variation< T >::vary, Brush::Var::Variation< T >::vary_and_update.
std::optional< Individual< T > > Brush::Var::Variation< T >::mutate(const Individual< T > &parent, string choice="")
Performs mutation operation on an individual.
Stochastically mutate a program. parent The parent individual. An optional containing the mutated individual if the mutation is successful, or an empty optional otherwise. Types of mutation: point mutation changes a single node. insertion mutation inserts a node as the parent of an existing node, and fills in the other arguments. deletion mutation deletes a node. subtree mutation inserts a new subtree into the program. toggle_weight_on mutation turns a node's weight ON. toggle_weight_off mutation turns a node's weight OFF. Every mutation has a probability (weight) based on global parameters. The spot where the mutation will take place is sampled based on attribute get_prob_change of each node in the tree. Inside each type of mutation, when a new node is inserted, it is sampled based on terminal_weights. Due to the stochastic behavior, and the several sampling steps, it may come to a case where the search space does not hold any possible modification to do in the program. In this case, the method returns std::nullopt (and has overloads so it can be used in a boolean context). If the mutation succeeds, the mutated program can be accessed through the .value() attribute of the std::optional. This means that, if you use the mutation as auto opt = mutate(parent, SS), either opt==false or opt.value() contains the child program. T program type parent the program to be mutated SS a search space std::optional that may contain the child program of type T
References Brush::Program< PType >::depth, Brush::Var::InsertMutation::find_spots, Brush::Var::MutationBase::find_spots, Brush::Var::SubtreeMutation::find_spots, Brush::Var::ToggleWeightOffMutation::find_spots, Brush::Var::ToggleWeightOnMutation::find_spots, HANDLE_ERROR_THROW, Brush::Var::DeleteMutation::mutate, Brush::Var::InsertMutation::mutate, Brush::Var::PointMutation::mutate, Brush::Var::SubtreeMutation::mutate, Brush::Var::ToggleWeightOffMutation::mutate, Brush::Var::ToggleWeightOnMutation::mutate, Brush::Var::Variation< T >::parameters, Brush::Pop::Individual< T >::program, Brush::Util::r, Brush::Pop::Individual< T >::set_sampled_nodes, Brush::Pop::Individual< T >::set_variation, Brush::Program< PType >::size, Brush::Program< PType >::Tree.
Referenced by Brush::Var::Variation< T >::vary, Brush::Var::Variation< T >::vary_and_update.
void Brush::Var::Variation< T >::vary(Population< T > &pop, int island, const vector< size_t > &parents)
Handles variation of a population.
pop The population to be varied. island The island index. parents The indices of the parent individuals. p The parameters for the variation operator.
References Brush::Var::Variation< T >::cross, Brush::Pop::Individual< T >::fitness, Brush::Fitness::get_complexity, Brush::Fitness::get_depth, Brush::Pop::Population< T >::get_island_indexes, Brush::Fitness::get_linear_complexity, Brush::Fitness::get_loss, Brush::Fitness::get_loss_v, Brush::Pop::Individual< T >::get_objectives, Brush::Fitness::get_size, Brush::Pop::Population< T >::individuals, Brush::Pop::Individual< T >::init, Brush::Pop::Individual< T >::is_fitted_, Brush::Var::Variation< T >::mutate, Brush::Var::Variation< T >::parameters, Brush::Pop::Individual< T >::program, Brush::Util::r, Brush::Var::Variation< T >::search_space, Brush::Fitness::set_complexity, Brush::Fitness::set_depth, Brush::Pop::Individual< T >::set_id, Brush::Fitness::set_linear_complexity, Brush::Fitness::set_loss, Brush::Fitness::set_loss_v, Brush::Pop::Individual< T >::set_objectives, Brush::Pop::Individual< T >::set_parents, Brush::Fitness::set_size, Brush::Program< PType >::size, Brush::Fitness::valid.
void Brush::Var::Variation< T >::update_ss()
Updates the probability distribution sampling for variation and nodes based on the given rewards. pop The population to update the selection strategy for. rewards The rewards obtained from the evaluation of individuals.
References Brush::Var::Variation< T >::op_bandits, Brush::Var::Variation< T >::parameters, Brush::Var::Variation< T >::search_space, Brush::Var::Variation< T >::terminal_bandits, Brush::Var::Variation< T >::variation_bandit.
Referenced by Brush::Engine< T >::run.
void Brush::Var::Variation< T >::vary_and_update(Population< T > &pop, int island, const vector< size_t > &parents, const Dataset &data, Evaluation< T > &evaluator, bool even_gen)
Varies a population and updates the selection strategy based on rewards.
This function performs variation on a population, calculates rewards, and updates the selection strategy based on the obtained rewards. pop The population to be varied and updated. island The island index. parents The indices of the parent individuals.
References Brush::Eval::Evaluation< T >::assign_fit, Brush::Var::Variation< T >::constants_simplifier, Brush::Var::Variation< T >::cross, Brush::Var::Variation< T >::data, Brush::Data::delta, Brush::Program< PType >::fit, Brush::Pop::Individual< T >::fitness, Brush::Fitness::get_complexity, Brush::Fitness::get_depth, Brush::Pop::Population< T >::get_island_indexes, Brush::Fitness::get_linear_complexity, Brush::Fitness::get_loss, Brush::Fitness::get_loss_v, Brush::Pop::Individual< T >::get_objectives, Brush::Fitness::get_prev_complexity, Brush::Fitness::get_prev_depth, Brush::Fitness::get_prev_linear_complexity, Brush::Fitness::get_prev_loss, Brush::Fitness::get_prev_size, Brush::Pop::Individual< T >::get_sampled_nodes, Brush::Fitness::get_size, Brush::Pop::Individual< T >::get_variation, HANDLE_ERROR_THROW, Brush::Pop::Population< T >::individuals, Brush::Var::Variation< T >::inexact_simplifier, Brush::Var::Variation< T >::mutate, Brush::Var::Variation< T >::op_bandits, Brush::Var::Variation< T >::parameters, Brush::Pop::Individual< T >::program, Brush::Util::r, Brush::Var::Variation< T >::search_space, Brush::Fitness::set_complexity, Brush::Fitness::set_depth, Brush::Pop::Individual< T >::set_id, Brush::Fitness::set_linear_complexity, Brush::Fitness::set_loss, Brush::Fitness::set_loss_v, Brush::Pop::Individual< T >::set_parents, Brush::Fitness::set_size, Brush::Program< PType >::size, Brush::Var::Variation< T >::terminal_bandits, Brush::Program< PType >::Tree, Brush::Fitness::valid, Brush::Pop::Individual< T >::variation, Brush::Var::Variation< T >::variation_bandit, Brush::Pop::Individual< T >::weightsMap.
Referenced by Brush::Engine< T >::run.
std::optional< Node > Brush::Var::Variation< T >::bandit_sample_terminal(DataType R)
References Brush::Var::Variation< T >::search_space, Brush::Var::Variation< T >::terminal_bandits.
Referenced by Brush::Var::Variation< T >::bandit_get_node_like, Brush::Var::DeleteMutation::mutate, Brush::Var::InsertMutation::mutate.
std::optional< Node > Brush::Var::Variation< T >::bandit_get_node_like(Node node)
References Brush::Node::args_type, Brush::Var::Variation< T >::bandit_sample_terminal, Brush::Is, Brush::Node::node_type, Brush::Var::Variation< T >::op_bandits, Brush::Node::ret_type, Brush::Var::Variation< T >::search_space.
Referenced by Brush::Var::PointMutation::mutate.
std::optional< Node > Brush::Var::Variation< T >::bandit_sample_op_with_arg(DataType ret, DataType arg, int max_args=0)
References Brush::Util::in, Brush::Var::Variation< T >::op_bandits, Brush::Util::r, Brush::Var::Variation< T >::search_space.
Referenced by Brush::Var::InsertMutation::mutate.
std::optional< Node > Brush::Var::Variation< T >::bandit_sample_op(DataType ret)
References Brush::Var::Variation< T >::op_bandits, Brush::Util::r, Brush::Var::Variation< T >::search_space.