Brush::Program
using Brush::Program< PType >::RetType = typename std::conditional_t<PType == PT::Regressor, ArrayXf, std::conditional_t<PType == PT::BinaryClassifier, ArrayXb, std::conditional_t<PType == PT::MulticlassClassifier, ArrayXi, std::conditional_t<PType == PT::Representer, ArrayXXf, ArrayXf > >> >
the return type of the tree when calling :func:predict.
using Brush::Program< PType >::TreeType = std::conditional_t<PType == PT::BinaryClassifier, ArrayXf, std::conditional_t<PType == PT::MulticlassClassifier, ArrayXXf, RetType> >
the type of output from the tree object
constexpr PT Brush::Program< PType >::program_type
an enum storing the program type.
bool Brush::Program< PType >::is_fitted_
whether fit has been called
Referenced by Brush::from_json, Brush::Program< PType >::predict, Brush::Program< PType >::predict_with_weights, Brush::to_json.
Fitness Brush::Program< PType >::fitness
fitness
tree<Node> Brush::Program< PType >::Tree
the underlying tree
Referenced by Brush::Program< PType >::depth, Brush::Program< PType >::depth_at, Brush::Program< PType >::depth_to_reach, Brush::Program< PType >::fit, Brush::from_json, Brush::Program< PType >::get_dot_model, Brush::Program< PType >::get_model, Brush::Program< PType >::get_n_weights, Brush::Program< PType >::get_weights, Brush::Program< PType >::linearize, Brush::Program< PType >::predict_with_weights, Brush::Program< PType >::set_weights, Brush::Program< PType >::size, Brush::to_json.
std::optional<std::reference_wrapper<SearchSpace> > Brush::Program< PType >::SSref
reference to search space
Referenced by Brush::Program< PType >::Program, Brush::Program< PType >::set_search_space.
TreeType Brush::Program< PType >::TreeType
ArrayXb Brush::Program< PType >::ArrayXb
ArrayXi Brush::Program< PType >::ArrayXi
TreeType Brush::Program< PType >::out
Referenced by Brush::Program< PType >::fit, Brush::Program< PType >::get_dot_model.
auto Brush::Program< PType >::argmax
Brush::Program< PType >::Program()=default
Brush::Program< PType >::Program(const std::reference_wrapper< SearchSpace > s, const tree< Node > t)
References Brush::Program< PType >::SSref.
void Brush::Program< PType >::set_search_space(const std::reference_wrapper< SearchSpace > s)
References Brush::Program< PType >::SSref.
int Brush::Program< PType >::size(bool include_weight=true) const
count the tree size of the program, including the weights in weighted nodes.
include_weight whether to include the node's weight in the count. int number of nodes.
References Brush::Program< PType >::Tree.
int Brush::Program< PType >::size_at(Iter &top, bool include_weight=true) const
count the size of a given subtree, optionally including the weights in weighted nodes. This function is not exposed to the python wrapper.
top root node of the subtree. include_weight whether to include the node's weight in the count. int number of nodes.
int Brush::Program< PType >::depth() const
count the tree depth of the program. The depth is not influenced by weighted nodes.
int tree depth.
References Brush::Program< PType >::Tree.
int Brush::Program< PType >::depth_at(Iter &top) const
count the depth of a given subtree. The depth is not influenced by weighted nodes. This function is not exposed to the python wrapper.
top root node of the subtree. int tree depth.
References Brush::Program< PType >::Tree.
int Brush::Program< PType >::depth_to_reach(Iter &top) const
count the depth until reaching the given subtree. The depth is not influenced by weighted nodes. This function is not exposed to the python wrapper.
top root node of the subtree. int tree depth.
References Brush::Program< PType >::Tree.
Program<PType>& Brush::Program< PType >::fit(const Dataset &d)
References Brush::Program< PType >::out, Brush::Program< PType >::Tree, Brush::Program< PType >::update_weights.
Referenced by Brush::Program< PType >::fit.
R Brush::Program< PType >::predict_with_weights(const Dataset &d, const W **weights)
References HANDLE_ERROR_THROW, Brush::Program< PType >::is_fitted_, Brush::Program< PType >::Tree, Brush::util::weights.
auto Brush::Program< PType >::predict_with_weights(const Dataset &d, const ArrayXf &weights)
References Brush::util::weights.
TreeType Brush::Program< PType >::predict(const Dataset &d) requires(is_same_v< R
the standard predict function. Returns the output of the Tree directly.
R return type, default d dataset
References HANDLE_ERROR_THROW, Brush::Program< PType >::is_fitted_.
Referenced by Brush::Program< PType >::predict.
return Tree Brush::Program< PType >::begin().node -> predict< TreeType >(d)
ArrayXb Brush::Program< PType >::predict(const Dataset &d) requires(is_same_v< R
Specialized predict function for binary classification.
R return type, typically left blank d : data out: binary labels
Brush::Program< PType >::return(Tree.begin().node->predict< TreeType >(d) > 0.5)
ArrayXi Brush::Program< PType >::predict(const Dataset &d) requires(is_same_v< R
Specialized predict function for multiclass classification.
R return type, typically left blank d : data out: integer labels
return Brush::Program< PType >::argmax(out)
Brush::Program< PType >::requires((P==PT::BinaryClassifier)||(P==PT::MulticlassClassifier)) TreeType predict_proba(const Dataset &d)
Program<PType>& Brush::Program< PType >::fit(const Ref< const ArrayXXf > &X, const Ref< const ArrayXf > &y)
Convenience function to call fit directly from X,y data.
X : Input features y : Labels : reference to program
References Brush::Program< PType >::fit.
RetType Brush::Program< PType >::predict(const Ref< const ArrayXXf > &X)
Convenience function to call predict directly from X data.
X : Input features : predictions
References Brush::Program< PType >::predict.
Brush::Program< PType >::requires((P==PT::BinaryClassifier)||(P==PT::MulticlassClassifier)) TreeType predict_proba(const Ref< const ArrayXXf > &X)
Predict probabilities from X.
Requires a BinaryClassifier or MulticlassClassifier. P parameter for type checking, typically left blank.
void Brush::Program< PType >::update_weights(const Dataset &d)
Updates the program's weights using non-linear least squares.
d the dataset
Referenced by Brush::Program< PType >::fit.
int Brush::Program< PType >::get_n_weights() const
returns the number of weights in the program.
References Brush::Program< PType >::Tree.
Referenced by Brush::Program< PType >::get_weights, Brush::Program< PType >::set_weights.
ArrayXf Brush::Program< PType >::get_weights()
Get the weights of the tree as an array.
ArrayXf of weights in the program, encoded in post-fix order.
References Brush::Program< PType >::get_n_weights, Brush::Program< PType >::Tree, Brush::util::weights.
void Brush::Program< PType >::set_weights(const ArrayXf &weights)
Set the weights in the tree from an array of weights.
weights an array of weights. The number of the weights in the tree must match the length of weights.
References Brush::Program< PType >::get_n_weights, HANDLE_ERROR_THROW, Brush::Program< PType >::Tree, Brush::util::weights.
string Brush::Program< PType >::get_model(string fmt="compact", bool pretty=false)
Get the model as a string.
fmt one of "compact", "tree", or "dot". Default "compact". compact : the program as an equation. tree : the program as a (small batch, artisinal) tree. dot : the program in the dot language for downstream visualization. pretty currently unused. string the model in string form.
References Brush::Program< PType >::get_dot_model, Brush::Program< PType >::Tree.
string Brush::Program< PType >::get_dot_model(string extras="")
Get the model as a dot object.
extras extra code passed to the beginning of the dot code. string the model in dot language.
References Brush::Program< PType >::out, Brush::Program< PType >::Tree.
Referenced by Brush::Program< PType >::get_model.
std::optional< Program< PType > > Brush::Program< PType >::mutate() const
convenience wrapper for :cpp:func:variation:mutate() in variation.h
a mutated version of this program
References variation::mutate.
std::optional< Program< PType > > Brush::Program< PType >::cross(Program< PType > other) const
convenience wrapper for :cpp:func:variation:cross in variation.h
swaps subtrees between this and other (note the pass by copy) other another program to cross with this one. a new version of this and the other program
References variation::cross.
vector<Node> Brush::Program< PType >::linearize() const
turns program tree into a linear program.
a vector of nodes encoding the program in reverse polish notation
References Brush::Program< PType >::Tree.