Brush::Operator
using Brush::Operator< NT, S, Fit, E >::ArgTypes = conditional_t< ((UnaryOp<NT> || NaryOp<NT>) && S::ArgCount > 1), Array<typename S::FirstArg::Scalar, -1, S::ArgCount>, typename S::ArgTypes>
set argument types to those of the signature unless:
a) the operator is unary and there are more than one arguments b) the operator is binary and associative In the case of a) or b), arguments to the operator are stacked into an array and the operator is applied to that array
using Brush::Operator< NT, S, Fit, E >::RetType = typename S::RetType
return type of the operator
using Brush::Operator< NT, S, Fit, E >::NthType = typename S::template NthType<N>
utility for returning the type of the Nth argument
using Brush::Operator< NT, S, Fit, E >::W = typename S::WeightType
set weight type
size_t Brush::Operator< NT, S, Fit, E >::ArgCount
stores the argument count of the operator
auto Brush::Operator< NT, S, Fit, E >::F
wrapper function for the node function
Referenced by Brush::Operator< NT, S, Fit, E >::apply.
Brush::Operator< NT, S, Fit, E >::Operator()=default
References Brush::is_eigen_array_v, Brush::is_std_array_v.
T Brush::Operator< NT, S, Fit, E >::get_kids(const Dataset &d, TreeNode &tn, const W **weights=nullptr) const
get a std::array or eigen array of kids
References Brush::is_eigen_array_v.
Referenced by Brush::Operator< NT, S, Fit, E >::eval.
NthType< I > Brush::Operator< NT, S, Fit, E >::get_kid(const Dataset &d, TreeNode &tn, const W **weights) const
gets one kid for a tuple of kids
T Brush::Operator< NT, S, Fit, E >::get_kids_seq(const Dataset &d, TreeNode &tn, const W **weights, std::index_sequence< Is... >) const
Makes and returns a tuple of child outputs.
T a tuple Is integer sequence d dataset tn a tree node a tuple with elements corresponding to each child node
Referenced by Brush::Operator< NT, S, Fit, E >::get_kids.
T Brush::Operator< NT, S, Fit, E >::get_kids(const Dataset &d, TreeNode &tn, const W **weights=nullptr) const
get a std::tuple of kids. Used when child arguments are different types.
T argument types d the dataset tn the tree node weights option pointer to a weight array, used in place of node weight a tuple of the child arguments
References Brush::Operator< NT, S, Fit, E >::get_kids_seq.
RetType Brush::Operator< NT, S, Fit, E >::apply(const T &inputs) const
Apply node function in a functional style.
T argument types inputs the child node outputs return values applying F to the inputs
References Brush::Operator< NT, S, Fit, E >::F.
Referenced by Brush::Operator< NT, S, Fit, E >::eval.
RetType Brush::Operator< NT, S, Fit, E >::apply(const T &inputs) const
Apply the node function like a function.
T argument types inputs the child node outputs return values applying F to the inputs
References Brush::Operator< NT, S, Fit, E >::F.
RetType Brush::Operator< NT, S, Fit, E >::eval(const Dataset &d, TreeNode &tn, const W **weights=nullptr) const
evaluate the operator on the data. main entry point.
T argument types Scalar the underlying scalar type of the return type d dataset tn tree node weights option pointer to a weight array, used in place of node weight output values from applying operator function
References Brush::Operator< NT, S, Fit, E >::apply, Brush::Operator< NT, S, Fit, E >::get_kids, Brush::util::get_weight, Brush::is_one_of_v.
Referenced by Brush::DispatchOp, Brush::DispatchOp.
RetType Brush::Operator< NT, S, Fit, E >::eval(const Dataset &d, TreeNode &tn, const W **weights=nullptr) const
References Brush::Operator< NT, S, Fit, E >::apply, Brush::Operator< NT, S, Fit, E >::get_kids, Brush::util::get_weight, Brush::is_one_of_v.