Brush::Pop::Archive
vector<Individual<T> > Brush::Pop::Archive< T >::individuals
individual programs in the archive
Referenced by Brush::Pop::Archive< T >::init, Brush::Pop::Archive< T >::update.
bool Brush::Pop::Archive< T >::sort_complexity
whether to sort archive by complexity
Referenced by Brush::Pop::Archive< T >::init, Brush::Pop::Archive< T >::set_objectives, Brush::Pop::Archive< T >::update.
bool Brush::Pop::Archive< T >::linear_complexity
Indicates if the user set linear_complexity instead of recursive complexity.
Referenced by Brush::Pop::Archive< T >::init, Brush::Pop::Archive< T >::set_objectives, Brush::Pop::Archive< T >::update.
NSGA2<T> Brush::Pop::Archive< T >::selector
using NSGA2 in survival mode (nsga2 does not implement selection)
Referenced by Brush::Pop::Archive< T >::Archive, Brush::Pop::Archive< T >::init, Brush::Pop::Archive< T >::update.
Brush::Pop::Archive< T >::Archive()
Default constructor for the Archive struct.
References Brush::Pop::Archive< T >::selector.
void Brush::Pop::Archive< T >::init(Population< T > &pop)
Initializes the archive with individuals from a population.
pop The population from which to initialize the archive.
References Brush::Pop::Population< T >::get_island_indexes, Brush::Pop::Archive< T >::individuals, Brush::Pop::Population< T >::individuals, Brush::Pop::Archive< T >::linear_complexity, Brush::Pop::Population< T >::num_islands, Brush::Pop::Archive< T >::selector, Brush::Pop::Archive< T >::sort_complexity, Brush::Pop::Archive< T >::sortComplexity, Brush::Pop::Archive< T >::sortLinearComplexity, Brush::Pop::Archive< T >::sortObj1.
void Brush::Pop::Archive< T >::update(Population< T > &pop, const Parameters &params)
Updates the archive with individuals from a population.
pop The population from which to update the archive. params The parameters for the update.
References Brush::Pop::Population< T >::get_island_indexes, Brush::Pop::Archive< T >::individuals, Brush::Pop::Population< T >::individuals, Brush::Pop::Archive< T >::linear_complexity, Brush::Pop::Population< T >::num_islands, Brush::Pop::Archive< T >::sameObjectives, Brush::Pop::Archive< T >::selector, Brush::Pop::Archive< T >::sort_complexity, Brush::Pop::Archive< T >::sortComplexity, Brush::Pop::Archive< T >::sortLinearComplexity, Brush::Pop::Archive< T >::sortObj1.
void Brush::Pop::Archive< T >::set_objectives(vector< string > objectives)
Sets the objectives for the archive.
This function sets the objectives for the archive. The objectives are used for sorting the archive. objectives The objectives to set for the archive.
References Brush::Util::in, Brush::Pop::Archive< T >::linear_complexity, Brush::Pop::Archive< T >::sort_complexity.
bool Brush::Pop::Archive< T >::sortComplexity(const Individual< T > &lhs, const Individual< T > &rhs)
Sorts the population in increasing complexity.
This static function is used to sort the population in increasing complexity. It is used as a comparison function for sorting algorithms. lhs The left-hand side individual to compare. rhs The right-hand side individual to compare.
References Brush::Fitness::complexity, Brush::Pop::Individual< T >::fitness.
Referenced by Brush::Pop::Archive< T >::init, Brush::Pop::Archive< T >::update.
bool Brush::Pop::Archive< T >::sortLinearComplexity(const Individual< T > &lhs, const Individual< T > &rhs)
References Brush::Pop::Individual< T >::fitness, Brush::Fitness::linear_complexity.
Referenced by Brush::Pop::Archive< T >::init, Brush::Pop::Archive< T >::update.
bool Brush::Pop::Archive< T >::sortObj1(const Individual< T > &lhs, const Individual< T > &rhs)
Sorts the population by the first objective.
This static function is used to sort the population by the first objective. It is used as a comparison function for sorting algorithms. lhs The left-hand side individual to compare. rhs The right-hand side individual to compare.
References Brush::Pop::Individual< T >::fitness, Brush::Fitness::wvalues.
Referenced by Brush::Pop::Archive< T >::init, Brush::Pop::Archive< T >::update.
bool Brush::Pop::Archive< T >::sameFitComplexity(const Individual< T > &lhs, const Individual< T > &rhs)
Checks if two individuals have the same fitness complexity.
This static function is used to check if two individuals have the same fitness complexity. It is used as a comparison function for finding duplicates in the population. lhs The left-hand side individual to compare. rhs The right-hand side individual to compare.
References Brush::Pop::Individual< T >::fitness.
bool Brush::Pop::Archive< T >::sameObjectives(const Individual< T > &lhs, const Individual< T > &rhs)
Checks if two individuals have the same objectives.
This static function is used to check if two individuals have the same objectives. It is used as a comparison function for finding duplicates in the population. lhs The left-hand side individual to compare. rhs The right-hand side individual to compare.
References Brush::Pop::Individual< T >::fitness.
Referenced by Brush::Pop::Archive< T >::update.