var files_dup =
[
    [ "__init__.py", "d3/d9a/____init_____8py.html", null ],
    [ "deap_api/__init__.py", "d6/d65/deap__api_2____init_____8py.html", null ],
    [ "bind_dataset.cpp", "d9/d40/bind__dataset_8cpp.html", "d9/d40/bind__dataset_8cpp" ],
    [ "bind_params.cpp", "da/dbf/bind__params_8cpp.html", "da/dbf/bind__params_8cpp" ],
    [ "bind_programs.cpp", "d9/d26/bind__programs_8cpp.html", "d9/d26/bind__programs_8cpp" ],
    [ "bind_programs.h", "d6/d3f/bind__programs_8h.html", "d6/d3f/bind__programs_8h" ],
    [ "bind_search_space.cpp", "d0/d94/bind__search__space_8cpp.html", "d0/d94/bind__search__space_8cpp" ],
    [ "data.cpp", "da/dc9/data_8cpp.html", "da/dc9/data_8cpp" ],
    [ "data.h", "d2/dbd/data_8h.html", "d2/dbd/data_8h" ],
    [ "dispatch_table.cpp", "df/d47/dispatch__table_8cpp.html", "df/d47/dispatch__table_8cpp" ],
    [ "dispatch_table.h", "df/d61/dispatch__table_8h.html", "df/d61/dispatch__table_8h" ],
    [ "error.cpp", "dd/db1/error_8cpp.html", "dd/db1/error_8cpp" ],
    [ "error.h", "da/d41/error_8h.html", "da/d41/error_8h" ],
    [ "estimator.py", "d3/dac/estimator_8py.html", [
      [ "BrushEstimator", "d0/dc4/classbrush_1_1estimator_1_1BrushEstimator.html", "d0/dc4/classbrush_1_1estimator_1_1BrushEstimator" ],
      [ "BrushClassifier", "d0/d6a/classbrush_1_1estimator_1_1BrushClassifier.html", "d0/d6a/classbrush_1_1estimator_1_1BrushClassifier" ],
      [ "BrushRegressor", "da/d81/classbrush_1_1estimator_1_1BrushRegressor.html", "da/d81/classbrush_1_1estimator_1_1BrushRegressor" ]
    ] ],
    [ "functions.h", "d8/d5c/functions_8h.html", "d8/d5c/functions_8h" ],
    [ "init.h", "d8/dc0/init_8h.html", "d8/dc0/init_8h" ],
    [ "io.cpp", "d5/d5a/io_8cpp.html", "d5/d5a/io_8cpp" ],
    [ "io.h", "dc/dac/io_8h.html", "dc/dac/io_8h" ],
    [ "logger.cpp", "d3/d30/logger_8cpp.html", null ],
    [ "logger.h", "d1/d8c/logger_8h.html", "d1/d8c/logger_8h" ],
    [ "module.cpp", "dd/d30/module_8cpp.html", "dd/d30/module_8cpp" ],
    [ "module.h", "d5/d16/module_8h.html", null ],
    [ "node.cpp", "d7/d70/node_8cpp.html", "d7/d70/node_8cpp" ],
    [ "node.h", "d1/d77/node_8h.html", "d1/d77/node_8h" ],
    [ "nodetype.cpp", "df/dfe/nodetype_8cpp.html", "df/dfe/nodetype_8cpp" ],
    [ "nodetype.h", "de/d26/nodetype_8h.html", "de/d26/nodetype_8h" ],
    [ "nsga2.py", "df/d62/nsga2_8py.html", "df/d62/nsga2_8py" ],
    [ "omop.cpp", "d2/d01/omop_8cpp.html", null ],
    [ "omop.h", "d0/dea/omop_8h.html", "d0/dea/omop_8h" ],
    [ "operator.h", "d7/de0/operator_8h.html", "d7/de0/operator_8h" ],
    [ "params.cpp", "dc/d4d/params_8cpp.html", "dc/d4d/params_8cpp" ],
    [ "params.h", "da/d33/params_8h.html", "da/d33/params_8h" ],
    [ "program.h", "d1/dea/program_8h.html", "d1/dea/program_8h" ],
    [ "rnd.cpp", "de/d67/rnd_8cpp.html", null ],
    [ "rnd.h", "d2/da9/rnd_8h.html", "d2/da9/rnd_8h" ],
    [ "search_space.cpp", "da/d48/search__space_8cpp.html", "da/d48/search__space_8cpp" ],
    [ "search_space.h", "d9/d99/search__space_8h.html", "d9/d99/search__space_8h" ],
    [ "signatures.h", "d8/d8b/signatures_8h.html", "d8/d8b/signatures_8h" ],
    [ "split.cpp", "d4/d59/split_8cpp.html", "d4/d59/split_8cpp" ],
    [ "split.h", "d4/df2/split_8h.html", "d4/df2/split_8h" ],
    [ "timeseries.cpp", "d2/dee/timeseries_8cpp.html", "d2/dee/timeseries_8cpp" ],
    [ "timeseries.h", "d9/df7/timeseries_8h.html", "d9/df7/timeseries_8h" ],
    [ "tiny_cost_function.h", "dd/d1b/tiny__cost__function_8h.html", "dd/d1b/tiny__cost__function_8h" ],
    [ "tree_node.cpp", "dd/d06/tree__node_8cpp.html", "dd/d06/tree__node_8cpp" ],
    [ "tree_node.h", "d1/da6/tree__node_8h.html", "d1/da6/tree__node_8h" ],
    [ "tuples.h", "d8/de0/tuples_8h.html", null ],
    [ "types.h", "d9/d49/types_8h.html", "d9/d49/types_8h" ],
    [ "utils.cpp", "de/d06/utils_8cpp.html", "de/d06/utils_8cpp" ],
    [ "utils.h", "d5/d60/utils_8h.html", "d5/d60/utils_8h" ],
    [ "utils.py", "d9/d9f/utils_8py.html", [
      [ "DeapIndividual", "d5/dca/classbrush_1_1deap__api_1_1utils_1_1DeapIndividual.html", "d5/dca/classbrush_1_1deap__api_1_1utils_1_1DeapIndividual" ]
    ] ],
    [ "variation.h", "d4/d1f/variation_8h.html", "d4/d1f/variation_8h" ],
    [ "weight_optimizer.h", "d7/de3/weight__optimizer_8h.html", [
      [ "OptimizerSummary", "dc/d91/structBrush_1_1OptimizerSummary.html", "dc/d91/structBrush_1_1OptimizerSummary" ],
      [ "ResidualEvaluator", "d4/d70/structBrush_1_1ResidualEvaluator.html", "d4/d70/structBrush_1_1ResidualEvaluator" ],
      [ "WeightOptimizer", "d7/d79/structBrush_1_1WeightOptimizer.html", "d7/d79/structBrush_1_1WeightOptimizer" ]
    ] ]
];