var hierarchy =
[
    [ "nlohmann::adl_serializer&lt; std::shared_ptr&lt; T &gt; &gt;", "d8/d3c/structnlohmann_1_1adl__serializer_3_01std_1_1shared__ptr_3_01T_01_4_01_4.html", null ],
    [ "Brush::all_same&lt; First, Next &gt;", "db/d64/structBrush_1_1all__same.html", null ],
    [ "Brush::Pop::Archive&lt; T &gt;", "d1/d30/structBrush_1_1Pop_1_1Archive.html", null ],
    [ "array&lt; T &gt;", "d2/d41/classarray.html", null ],
    [ "Brush::MAB::Bandit", "d4/d90/structBrush_1_1MAB_1_1Bandit.html", null ],
    [ "Brush::MAB::BanditOperator", "df/dde/classBrush_1_1MAB_1_1BanditOperator.html", [
      [ "Brush::MAB::DummyBandit", "dd/d41/classBrush_1_1MAB_1_1DummyBandit.html", null ],
      [ "Brush::MAB::ThompsonSamplingBandit", "db/d10/classBrush_1_1MAB_1_1ThompsonSamplingBandit.html", null ]
    ] ],
    [ "Brush::Sel::NSGA2&lt; T &gt;::comparator_obj", "dd/dc3/structBrush_1_1Sel_1_1NSGA2_1_1comparator__obj.html", null ],
    [ "array&lt; T &gt;::const_iterator", "dc/d95/classarray_1_1const__iterator.html", null ],
    [ "map&lt; K, T &gt;::const_iterator", "d8/d46/classmap_1_1const__iterator.html", null ],
    [ "set&lt; K &gt;::const_iterator", "d2/da2/classset_1_1const__iterator.html", null ],
    [ "string::const_iterator", "d1/df2/classstring_1_1const__iterator.html", null ],
    [ "vector&lt; T &gt;::const_iterator", "d4/df5/classvector_1_1const__iterator.html", null ],
    [ "array&lt; T &gt;::const_reverse_iterator", "d3/d18/classarray_1_1const__reverse__iterator.html", null ],
    [ "map&lt; K, T &gt;::const_reverse_iterator", "dd/da0/classmap_1_1const__reverse__iterator.html", null ],
    [ "set&lt; K &gt;::const_reverse_iterator", "d0/d6a/classset_1_1const__reverse__iterator.html", null ],
    [ "string::const_reverse_iterator", "dc/dda/classstring_1_1const__reverse__iterator.html", null ],
    [ "vector&lt; T &gt;::const_reverse_iterator", "dd/d51/classvector_1_1const__reverse__iterator.html", null ],
    [ "Brush::Simpl::Constants_simplifier", "d6/df2/classBrush_1_1Simpl_1_1Constants__simplifier.html", null ],
    [ "Brush::DataEnumType&lt; D &gt;", "d8/d17/structBrush_1_1DataEnumType.html", null ],
    [ "Brush::DataEnumType&lt; DT::ArrayB &gt;", "d6/d53/structBrush_1_1DataEnumType_3_01DT_1_1ArrayB_01_4.html", null ],
    [ "Brush::DataEnumType&lt; DT::ArrayBJet &gt;", "d4/dcb/structBrush_1_1DataEnumType_3_01DT_1_1ArrayBJet_01_4.html", null ],
    [ "Brush::DataEnumType&lt; DT::ArrayF &gt;", "df/dc3/structBrush_1_1DataEnumType_3_01DT_1_1ArrayF_01_4.html", null ],
    [ "Brush::DataEnumType&lt; DT::ArrayFJet &gt;", "d4/d9c/structBrush_1_1DataEnumType_3_01DT_1_1ArrayFJet_01_4.html", null ],
    [ "Brush::DataEnumType&lt; DT::ArrayI &gt;", "db/d06/structBrush_1_1DataEnumType_3_01DT_1_1ArrayI_01_4.html", null ],
    [ "Brush::DataEnumType&lt; DT::ArrayIJet &gt;", "dc/db4/structBrush_1_1DataEnumType_3_01DT_1_1ArrayIJet_01_4.html", null ],
    [ "Brush::DataEnumType&lt; DT::MatrixB &gt;", "de/dd1/structBrush_1_1DataEnumType_3_01DT_1_1MatrixB_01_4.html", null ],
    [ "Brush::DataEnumType&lt; DT::MatrixBJet &gt;", "dd/d86/structBrush_1_1DataEnumType_3_01DT_1_1MatrixBJet_01_4.html", null ],
    [ "Brush::DataEnumType&lt; DT::MatrixF &gt;", "d9/df1/structBrush_1_1DataEnumType_3_01DT_1_1MatrixF_01_4.html", null ],
    [ "Brush::DataEnumType&lt; DT::MatrixFJet &gt;", "d0/d7c/structBrush_1_1DataEnumType_3_01DT_1_1MatrixFJet_01_4.html", null ],
    [ "Brush::DataEnumType&lt; DT::MatrixI &gt;", "d6/de7/structBrush_1_1DataEnumType_3_01DT_1_1MatrixI_01_4.html", null ],
    [ "Brush::DataEnumType&lt; DT::MatrixIJet &gt;", "dc/ded/structBrush_1_1DataEnumType_3_01DT_1_1MatrixIJet_01_4.html", null ],
    [ "Brush::DataEnumType&lt; DT::TimeSeriesB &gt;", "dc/dd6/structBrush_1_1DataEnumType_3_01DT_1_1TimeSeriesB_01_4.html", null ],
    [ "Brush::DataEnumType&lt; DT::TimeSeriesF &gt;", "d2/db8/structBrush_1_1DataEnumType_3_01DT_1_1TimeSeriesF_01_4.html", null ],
    [ "Brush::DataEnumType&lt; DT::TimeSeriesI &gt;", "dd/dff/structBrush_1_1DataEnumType_3_01DT_1_1TimeSeriesI_01_4.html", null ],
    [ "Brush::Data::Dataset", "d2/d36/classBrush_1_1Data_1_1Dataset.html", null ],
    [ "Dataset", "d7/da5/classDataset.html", null ],
    [ "Brush::DataTypeEnum&lt; T &gt;", "df/d3e/structBrush_1_1DataTypeEnum.html", null ],
    [ "Brush::DataTypeEnum&lt; ArrayXb &gt;", "d7/d9a/structBrush_1_1DataTypeEnum_3_01ArrayXb_01_4.html", null ],
    [ "Brush::DataTypeEnum&lt; ArrayXbJet &gt;", "d7/d76/structBrush_1_1DataTypeEnum_3_01ArrayXbJet_01_4.html", null ],
    [ "Brush::DataTypeEnum&lt; ArrayXf &gt;", "d9/d96/structBrush_1_1DataTypeEnum_3_01ArrayXf_01_4.html", null ],
    [ "Brush::DataTypeEnum&lt; ArrayXfJet &gt;", "d4/d46/structBrush_1_1DataTypeEnum_3_01ArrayXfJet_01_4.html", null ],
    [ "Brush::DataTypeEnum&lt; ArrayXi &gt;", "d7/d35/structBrush_1_1DataTypeEnum_3_01ArrayXi_01_4.html", null ],
    [ "Brush::DataTypeEnum&lt; ArrayXiJet &gt;", "d4/dd1/structBrush_1_1DataTypeEnum_3_01ArrayXiJet_01_4.html", null ],
    [ "Brush::DataTypeEnum&lt; ArrayXXb &gt;", "d7/d17/structBrush_1_1DataTypeEnum_3_01ArrayXXb_01_4.html", null ],
    [ "Brush::DataTypeEnum&lt; ArrayXXbJet &gt;", "da/d1f/structBrush_1_1DataTypeEnum_3_01ArrayXXbJet_01_4.html", null ],
    [ "Brush::DataTypeEnum&lt; ArrayXXf &gt;", "df/dc9/structBrush_1_1DataTypeEnum_3_01ArrayXXf_01_4.html", null ],
    [ "Brush::DataTypeEnum&lt; ArrayXXfJet &gt;", "d7/d70/structBrush_1_1DataTypeEnum_3_01ArrayXXfJet_01_4.html", null ],
    [ "Brush::DataTypeEnum&lt; ArrayXXi &gt;", "de/dcc/structBrush_1_1DataTypeEnum_3_01ArrayXXi_01_4.html", null ],
    [ "Brush::DataTypeEnum&lt; ArrayXXiJet &gt;", "dc/d84/structBrush_1_1DataTypeEnum_3_01ArrayXXiJet_01_4.html", null ],
    [ "Brush::DataTypeEnum&lt; Data::TimeSeriesb &gt;", "d6/d27/structBrush_1_1DataTypeEnum_3_01Data_1_1TimeSeriesb_01_4.html", null ],
    [ "Brush::DataTypeEnum&lt; Data::TimeSeriesbJet &gt;", "d6/d3c/structBrush_1_1DataTypeEnum_3_01Data_1_1TimeSeriesbJet_01_4.html", null ],
    [ "Brush::DataTypeEnum&lt; Data::TimeSeriesf &gt;", "df/d37/structBrush_1_1DataTypeEnum_3_01Data_1_1TimeSeriesf_01_4.html", null ],
    [ "Brush::DataTypeEnum&lt; Data::TimeSeriesfJet &gt;", "d1/d94/structBrush_1_1DataTypeEnum_3_01Data_1_1TimeSeriesfJet_01_4.html", null ],
    [ "Brush::DataTypeEnum&lt; Data::TimeSeriesi &gt;", "d5/d29/structBrush_1_1DataTypeEnum_3_01Data_1_1TimeSeriesi_01_4.html", null ],
    [ "Brush::DataTypeEnum&lt; Data::TimeSeriesiJet &gt;", "da/d56/structBrush_1_1DataTypeEnum_3_01Data_1_1TimeSeriesiJet_01_4.html", null ],
    [ "Brush::DispatchTable&lt; Fit &gt;", "d3/da8/structBrush_1_1DispatchTable.html", null ],
    [ "Brush::Engine&lt; T &gt;", "d0/d75/classBrush_1_1Engine.html", null ],
    [ "Brush::Eval::Evaluation&lt; T &gt;", "d1/de5/classBrush_1_1Eval_1_1Evaluation.html", null ],
    [ "std::false_type", null, [
      [ "Brush::is_std_array< std::array< V, n > >", "d4/df1/structBrush_1_1is__std__array_3_01std_1_1array_3_01V_00_01n_01_4_01_4.html", null ],
      [ "Brush::is_tuple< std::tuple< T... > >", "df/d54/structBrush_1_1is__tuple_3_01std_1_1tuple_3_01T_8_8_8_01_4_01_4.html", null ],
      [ "Brush::is_std_array< T >", "d6/dfa/structBrush_1_1is__std__array.html", null ],
      [ "Brush::is_tuple< typename >", "d0/d4c/structBrush_1_1is__tuple.html", null ]
    ] ],
    [ "Brush::Fitness", "d6/dd0/structBrush_1_1Fitness.html", null ],
    [ "formatter", null, [
      [ "fmt::formatter< Brush::Data::TimeSeriesb >", "db/d20/structfmt_1_1formatter_3_01Brush_1_1Data_1_1TimeSeriesb_01_4.html", null ],
      [ "fmt::formatter< Brush::Data::TimeSeriesf >", "d5/dd4/structfmt_1_1formatter_3_01Brush_1_1Data_1_1TimeSeriesf_01_4.html", null ],
      [ "fmt::formatter< Brush::Data::TimeSeriesi >", "dd/dc8/structfmt_1_1formatter_3_01Brush_1_1Data_1_1TimeSeriesi_01_4.html", null ],
      [ "fmt::formatter< Brush::DataType >", "de/d6b/structfmt_1_1formatter_3_01Brush_1_1DataType_01_4.html", null ],
      [ "fmt::formatter< Brush::Node >", "d4/d63/structfmt_1_1formatter_3_01Brush_1_1Node_01_4.html", null ],
      [ "fmt::formatter< Brush::NodeType >", "d4/d42/structfmt_1_1formatter_3_01Brush_1_1NodeType_01_4.html", null ],
      [ "fmt::formatter< Brush::SearchSpace >", "d7/de7/structfmt_1_1formatter_3_01Brush_1_1SearchSpace_01_4.html", null ]
    ] ],
    [ "Brush::Function&lt; N &gt;", "d9/d1b/structBrush_1_1Function.html", null ],
    [ "Brush::Function&lt; NodeType::Abs &gt;", "d0/de7/structBrush_1_1Function_3_01NodeType_1_1Abs_01_4.html", null ],
    [ "Brush::Function&lt; NodeType::Acos &gt;", "d3/d84/structBrush_1_1Function_3_01NodeType_1_1Acos_01_4.html", null ],
    [ "Brush::Function&lt; NodeType::Add &gt;", "de/d7a/structBrush_1_1Function_3_01NodeType_1_1Add_01_4.html", null ],
    [ "Brush::Function&lt; NodeType::After &gt;", "d8/dca/structBrush_1_1Function_3_01NodeType_1_1After_01_4.html", null ],
    [ "Brush::Function&lt; NodeType::And &gt;", "de/d19/structBrush_1_1Function_3_01NodeType_1_1And_01_4.html", null ],
    [ "Brush::Function&lt; NodeType::ArgMax &gt;", "d6/da6/structBrush_1_1Function_3_01NodeType_1_1ArgMax_01_4.html", null ],
    [ "Brush::Function&lt; NodeType::Asin &gt;", "d5/d79/structBrush_1_1Function_3_01NodeType_1_1Asin_01_4.html", null ],
    [ "Brush::Function&lt; NodeType::Atan &gt;", "d7/d62/structBrush_1_1Function_3_01NodeType_1_1Atan_01_4.html", null ],
    [ "Brush::Function&lt; NodeType::Before &gt;", "dc/dd3/structBrush_1_1Function_3_01NodeType_1_1Before_01_4.html", null ],
    [ "Brush::Function&lt; NodeType::Ceil &gt;", "db/d67/structBrush_1_1Function_3_01NodeType_1_1Ceil_01_4.html", null ],
    [ "Brush::Function&lt; NodeType::Cos &gt;", "d5/d44/structBrush_1_1Function_3_01NodeType_1_1Cos_01_4.html", null ],
    [ "Brush::Function&lt; NodeType::Cosh &gt;", "d2/de4/structBrush_1_1Function_3_01NodeType_1_1Cosh_01_4.html", null ],
    [ "Brush::Function&lt; NodeType::Count &gt;", "d5/d32/structBrush_1_1Function_3_01NodeType_1_1Count_01_4.html", null ],
    [ "Brush::Function&lt; NodeType::Div &gt;", "d3/d6e/structBrush_1_1Function_3_01NodeType_1_1Div_01_4.html", null ],
    [ "Brush::Function&lt; NodeType::During &gt;", "de/da7/structBrush_1_1Function_3_01NodeType_1_1During_01_4.html", null ],
    [ "Brush::Function&lt; NodeType::Equals &gt;", "d2/d02/structBrush_1_1Function_3_01NodeType_1_1Equals_01_4.html", null ],
    [ "Brush::Function&lt; NodeType::Exp &gt;", "d8/d59/structBrush_1_1Function_3_01NodeType_1_1Exp_01_4.html", null ],
    [ "Brush::Function&lt; NodeType::Floor &gt;", "d9/d4c/structBrush_1_1Function_3_01NodeType_1_1Floor_01_4.html", null ],
    [ "Brush::Function&lt; NodeType::Geq &gt;", "d7/d11/structBrush_1_1Function_3_01NodeType_1_1Geq_01_4.html", null ],
    [ "Brush::Function&lt; NodeType::Log &gt;", "d4/db0/structBrush_1_1Function_3_01NodeType_1_1Log_01_4.html", null ],
    [ "Brush::Function&lt; NodeType::Log1p &gt;", "d6/d39/structBrush_1_1Function_3_01NodeType_1_1Log1p_01_4.html", null ],
    [ "Brush::Function&lt; NodeType::Logabs &gt;", "d3/d95/structBrush_1_1Function_3_01NodeType_1_1Logabs_01_4.html", null ],
    [ "Brush::Function&lt; NodeType::Logistic &gt;", "d5/db7/structBrush_1_1Function_3_01NodeType_1_1Logistic_01_4.html", null ],
    [ "Brush::Function&lt; NodeType::Max &gt;", "d0/d4d/structBrush_1_1Function_3_01NodeType_1_1Max_01_4.html", null ],
    [ "Brush::Function&lt; NodeType::Mean &gt;", "d1/d36/structBrush_1_1Function_3_01NodeType_1_1Mean_01_4.html", null ],
    [ "Brush::Function&lt; NodeType::Median &gt;", "d2/d84/structBrush_1_1Function_3_01NodeType_1_1Median_01_4.html", null ],
    [ "Brush::Function&lt; NodeType::Min &gt;", "d8/d4a/structBrush_1_1Function_3_01NodeType_1_1Min_01_4.html", null ],
    [ "Brush::Function&lt; NodeType::Mul &gt;", "d7/dd7/structBrush_1_1Function_3_01NodeType_1_1Mul_01_4.html", null ],
    [ "Brush::Function&lt; NodeType::Not &gt;", "d4/d67/structBrush_1_1Function_3_01NodeType_1_1Not_01_4.html", null ],
    [ "Brush::Function&lt; NodeType::OffsetSum &gt;", "dc/dcc/structBrush_1_1Function_3_01NodeType_1_1OffsetSum_01_4.html", null ],
    [ "Brush::Function&lt; NodeType::Or &gt;", "d4/d1b/structBrush_1_1Function_3_01NodeType_1_1Or_01_4.html", null ],
    [ "Brush::Function&lt; NodeType::Pow &gt;", "da/d0e/structBrush_1_1Function_3_01NodeType_1_1Pow_01_4.html", null ],
    [ "Brush::Function&lt; NodeType::Prod &gt;", "d7/d7e/structBrush_1_1Function_3_01NodeType_1_1Prod_01_4.html", null ],
    [ "Brush::Function&lt; NodeType::Sin &gt;", "d7/d76/structBrush_1_1Function_3_01NodeType_1_1Sin_01_4.html", null ],
    [ "Brush::Function&lt; NodeType::Sinh &gt;", "d5/d7d/structBrush_1_1Function_3_01NodeType_1_1Sinh_01_4.html", null ],
    [ "Brush::Function&lt; NodeType::Softmax &gt;", "d3/def/structBrush_1_1Function_3_01NodeType_1_1Softmax_01_4.html", null ],
    [ "Brush::Function&lt; NodeType::Sqrt &gt;", "d1/dc4/structBrush_1_1Function_3_01NodeType_1_1Sqrt_01_4.html", null ],
    [ "Brush::Function&lt; NodeType::Sqrtabs &gt;", "db/d25/structBrush_1_1Function_3_01NodeType_1_1Sqrtabs_01_4.html", null ],
    [ "Brush::Function&lt; NodeType::Square &gt;", "db/dba/structBrush_1_1Function_3_01NodeType_1_1Square_01_4.html", null ],
    [ "Brush::Function&lt; NodeType::Sub &gt;", "d0/d24/structBrush_1_1Function_3_01NodeType_1_1Sub_01_4.html", null ],
    [ "Brush::Function&lt; NodeType::Sum &gt;", "d8/d9c/structBrush_1_1Function_3_01NodeType_1_1Sum_01_4.html", null ],
    [ "Brush::Function&lt; NodeType::Tan &gt;", "d7/d8e/structBrush_1_1Function_3_01NodeType_1_1Tan_01_4.html", null ],
    [ "Brush::Function&lt; NodeType::Tanh &gt;", "dc/d5d/structBrush_1_1Function_3_01NodeType_1_1Tanh_01_4.html", null ],
    [ "std::hash&lt; std::tuple&lt; TT... &gt; &gt;", "de/d30/structstd_1_1hash_3_01std_1_1tuple_3_01TT_8_8_8_01_4_01_4.html", null ],
    [ "std::hash&lt; std::vector&lt; float &gt; &gt;", "d4/d0d/structstd_1_1hash_3_01std_1_1vector_3_01float_01_4_01_4.html", null ],
    [ "Brush::Simpl::HashStorage", "d4/d71/classBrush_1_1Simpl_1_1HashStorage.html", null ],
    [ "Brush::Pop::Individual&lt; T &gt;", "de/d83/classBrush_1_1Pop_1_1Individual.html", null ],
    [ "Brush::Simpl::Inexact_simplifier", "de/dc5/classBrush_1_1Simpl_1_1Inexact__simplifier.html", null ],
    [ "is_any&lt; T, Ts &gt;", "d2/d17/structis__any.html", null ],
    [ "std::is_base_of", null, [
      [ "Brush::is_eigen_array< T >", "df/d72/structBrush_1_1is__eigen__array.html", null ]
    ] ],
    [ "is_in&lt; T, Ts &gt;", "d0/d80/structis__in.html", null ],
    [ "Brush::is_one_of&lt; First, Next &gt;", "d3/d0e/structBrush_1_1is__one__of.html", null ],
    [ "array&lt; T &gt;::iterator", "d9/dcc/classarray_1_1iterator.html", null ],
    [ "map&lt; K, T &gt;::iterator", "dd/d7b/classmap_1_1iterator.html", null ],
    [ "set&lt; K &gt;::iterator", "dd/d43/classset_1_1iterator.html", null ],
    [ "string::iterator", "d5/d16/classstring_1_1iterator.html", null ],
    [ "vector&lt; T &gt;::iterator", "d0/d05/classvector_1_1iterator.html", null ],
    [ "Brush::Jetify&lt; T &gt;", "de/d30/structBrush_1_1Jetify.html", null ],
    [ "Brush::Jetify&lt; ArrayXb &gt;", "da/dd5/structBrush_1_1Jetify_3_01ArrayXb_01_4.html", null ],
    [ "Brush::Jetify&lt; ArrayXf &gt;", "d4/d10/structBrush_1_1Jetify_3_01ArrayXf_01_4.html", null ],
    [ "Brush::Jetify&lt; ArrayXi &gt;", "dc/d2f/structBrush_1_1Jetify_3_01ArrayXi_01_4.html", null ],
    [ "Brush::Jetify&lt; ArrayXXb &gt;", "d9/d13/structBrush_1_1Jetify_3_01ArrayXXb_01_4.html", null ],
    [ "Brush::Jetify&lt; ArrayXXf &gt;", "da/d99/structBrush_1_1Jetify_3_01ArrayXXf_01_4.html", null ],
    [ "Brush::Jetify&lt; ArrayXXi &gt;", "d2/d53/structBrush_1_1Jetify_3_01ArrayXXi_01_4.html", null ],
    [ "Brush::Jetify&lt; Data::TimeSeriesb &gt;", "d4/d01/structBrush_1_1Jetify_3_01Data_1_1TimeSeriesb_01_4.html", null ],
    [ "Brush::Jetify&lt; Data::TimeSeriesf &gt;", "da/dc3/structBrush_1_1Jetify_3_01Data_1_1TimeSeriesf_01_4.html", null ],
    [ "Brush::Jetify&lt; Data::TimeSeriesi &gt;", "d9/da6/structBrush_1_1Jetify_3_01Data_1_1TimeSeriesi_01_4.html", null ],
    [ "Brush::Util::Log_Stats", "db/d7e/structBrush_1_1Util_1_1Log__Stats.html", null ],
    [ "Brush::Util::Logger", "dd/d56/classBrush_1_1Util_1_1Logger.html", null ],
    [ "map&lt; K, T &gt;", "d9/d28/classmap.html", null ],
    [ "Brush::Var::MutationBase", "d0/dec/classBrush_1_1Var_1_1MutationBase.html", [
      [ "Brush::Var::DeleteMutation", "d0/d6d/classBrush_1_1Var_1_1DeleteMutation.html", null ],
      [ "Brush::Var::InsertMutation", "dc/de3/classBrush_1_1Var_1_1InsertMutation.html", null ],
      [ "Brush::Var::PointMutation", "d4/d46/classBrush_1_1Var_1_1PointMutation.html", null ],
      [ "Brush::Var::SubtreeMutation", "de/d23/classBrush_1_1Var_1_1SubtreeMutation.html", null ],
      [ "Brush::Var::ToggleWeightOffMutation", "dd/d55/classBrush_1_1Var_1_1ToggleWeightOffMutation.html", null ],
      [ "Brush::Var::ToggleWeightOnMutation", "d2/d1a/classBrush_1_1Var_1_1ToggleWeightOnMutation.html", null ]
    ] ],
    [ "Brush::NarySignature&lt; R, Arg, ArgCount, Indices &gt;", "d6/df7/structBrush_1_1NarySignature.html", null ],
    [ "Brush::NarySignatures&lt; R, Arg, MaxArgCount &gt;", "d9/da6/structBrush_1_1NarySignatures.html", null ],
    [ "Brush::Node", "d1/d3a/structBrush_1_1Node.html", null ],
    [ "Node", "d8/d49/structNode.html", null ],
    [ "Brush::NodeTypes", "db/d53/structBrush_1_1NodeTypes.html", null ],
    [ "Brush::Util::Normalizer", "d2/df8/structBrush_1_1Util_1_1Normalizer.html", null ],
    [ "Brush::Data::OmopData", "dc/d67/structBrush_1_1Data_1_1OmopData.html", null ],
    [ "Brush::Operator&lt; NT, S, Fit, E &gt;", "dc/d31/structBrush_1_1Operator.html", null ],
    [ "Brush::Operator&lt; NodeType::Constant, S, Fit &gt;", "df/dc1/structBrush_1_1Operator_3_01NodeType_1_1Constant_00_01S_00_01Fit_01_4.html", null ],
    [ "Brush::Operator&lt; NodeType::MeanLabel, S, Fit &gt;", "d9/d5e/structBrush_1_1Operator_3_01NodeType_1_1MeanLabel_00_01S_00_01Fit_01_4.html", null ],
    [ "Brush::Operator&lt; NodeType::Terminal, S, Fit &gt;", "dd/d88/structBrush_1_1Operator_3_01NodeType_1_1Terminal_00_01S_00_01Fit_01_4.html", null ],
    [ "Brush::Operator&lt; NT, S, Fit, enable_if_t&lt; is_in_v&lt; NT, NodeType::SplitOn, NodeType::SplitBest &gt; &gt; &gt;", "db/d1f/structBrush_1_1Operator_3_01NT_00_01S_00_01Fit_00_01enable__if__t_3_01is__in__v_3_01NT_00_01Node0d34d2b97afea7b3bb37b94bd97cbb86.html", null ],
    [ "Operator&lt; NT, S, Fit, enable_if_t&lt; is_in_v&lt; NT, NodeType::SplitOn, NodeType::SplitBest &gt; &gt; &gt;", "d3/df2/structOperator_3_01NT_00_01S_00_01Fit_00_01enable__if__t_3_01is__in__v_3_01NT_00_01NodeType_1_1Se4750a8ecc1d24ba81c8da2bd5c73a14.html", null ],
    [ "Brush::OptimizerSummary", "dc/d91/structBrush_1_1OptimizerSummary.html", null ],
    [ "Brush::Parameters", "de/deb/structBrush_1_1Parameters.html", null ],
    [ "Brush::Pop::Population&lt; T &gt;", "da/da3/classBrush_1_1Pop_1_1Population.html", null ],
    [ "Brush::Program&lt; PType &gt;", "db/d88/structBrush_1_1Program.html", null ],
    [ "Brush::ResidualEvaluator&lt; PT &gt;", "d4/d70/structBrush_1_1ResidualEvaluator.html", null ],
    [ "array&lt; T &gt;::reverse_iterator", "dd/d20/classarray_1_1reverse__iterator.html", null ],
    [ "map&lt; K, T &gt;::reverse_iterator", "dc/ddc/classmap_1_1reverse__iterator.html", null ],
    [ "set&lt; K &gt;::reverse_iterator", "d8/d5a/classset_1_1reverse__iterator.html", null ],
    [ "string::reverse_iterator", "d0/d8d/classstring_1_1reverse__iterator.html", null ],
    [ "vector&lt; T &gt;::reverse_iterator", "dd/d96/classvector_1_1reverse__iterator.html", null ],
    [ "Brush::Util::Rnd", "d2/d2d/classBrush_1_1Util_1_1Rnd.html", null ],
    [ "Brush::Pop::Population&lt; T &gt;::SameFitComplexity", "d4/de2/structBrush_1_1Pop_1_1Population_1_1SameFitComplexity.html", null ],
    [ "Brush::Eval::Scorer&lt; P &gt;", "da/d4c/classBrush_1_1Eval_1_1Scorer.html", null ],
    [ "Brush::Eval::Scorer&lt; P &gt;", "d1/d73/classBrush_1_1Eval_1_1Scorer_3_01P_01_4.html", null ],
    [ "Brush::SearchSpace", "d4/dc3/structBrush_1_1SearchSpace.html", null ],
    [ "SearchSpace", "de/d87/structSearchSpace.html", null ],
    [ "Brush::Sel::Selection&lt; T &gt;", "dd/d0f/structBrush_1_1Sel_1_1Selection.html", null ],
    [ "Brush::Sel::SelectionOperator&lt; T &gt;", "de/db9/classBrush_1_1Sel_1_1SelectionOperator.html", [
      [ "Brush::Sel::Lexicase< T >", "d2/dd0/classBrush_1_1Sel_1_1Lexicase.html", null ],
      [ "Brush::Sel::NSGA2< T >", "d3/d7d/classBrush_1_1Sel_1_1NSGA2.html", null ]
    ] ],
    [ "set&lt; K &gt;", "d0/d59/classset.html", null ],
    [ "shared_ptr&lt; T &gt;", "d4/d67/classshared__ptr.html", null ],
    [ "Brush::SigBase&lt; R, Args &gt;", "da/dd5/structBrush_1_1SigBase.html", null ],
    [ "Brush::SigBase&lt; R &gt;", "dc/da5/structBrush_1_1SigBase_3_01R_01_4.html", null ],
    [ "Brush::SigBase&lt; R, Args... &gt;", "da/dd5/structBrush_1_1SigBase.html", [
      [ "Brush::Signature< R(Args...)>", "d5/d7d/structBrush_1_1Signature_3_01R_07Args_8_8_8_08_4.html", null ]
    ] ],
    [ "Brush::Signature&lt; T &gt;", "d2/d75/structBrush_1_1Signature.html", null ],
    [ "Brush::Signatures&lt; N, T &gt;", "d1/d9a/structBrush_1_1Signatures.html", null ],
    [ "Brush::Signatures&lt; N, enable_if_t&lt; is_in_v&lt; N, NodeType::Abs, NodeType::Acos, NodeType::Asin, NodeType::Atan, NodeType::Cos, NodeType::Cosh, NodeType::Sin, NodeType::Sinh, NodeType::Tan, NodeType::Tanh, NodeType::Ceil, NodeType::Floor, NodeType::Exp, NodeType::Log, NodeType::Logabs, NodeType::Log1p, NodeType::Sqrt, NodeType::Sqrtabs, NodeType::Square, NodeType::Logistic &gt; &gt; &gt;", "d6/d13/structBrush_1_1Signatures_3_01N_00_01enable__if__t_3_01is__in__v_3_01N_00_01NodeType_1_1Abs_00_041c8b69233b6ea6ea1dff31c8b98dd13.html", null ],
    [ "Brush::Signatures&lt; N, enable_if_t&lt; is_in_v&lt; N, NodeType::Add, NodeType::Sub, NodeType::Mul, NodeType::Div, NodeType::Pow &gt; &gt; &gt;", "d2/d82/structBrush_1_1Signatures_3_01N_00_01enable__if__t_3_01is__in__v_3_01N_00_01NodeType_1_1Add_00_02ae8c79e1c3eb458e9c5f6f94e9a9b11.html", null ],
    [ "Brush::Signatures&lt; N, enable_if_t&lt; is_in_v&lt; N, NodeType::And, NodeType::Or &gt; &gt; &gt;", "d6/d2d/structBrush_1_1Signatures_3_01N_00_01enable__if__t_3_01is__in__v_3_01N_00_01NodeType_1_1And_00_01NodeType_1_1Or_01_4_01_4_01_4.html", null ],
    [ "Brush::Signatures&lt; N, enable_if_t&lt; is_in_v&lt; N, NodeType::ArgMax &gt; &gt; &gt;", "dd/d56/structBrush_1_1Signatures_3_01N_00_01enable__if__t_3_01is__in__v_3_01N_00_01NodeType_1_1ArgMax_01_4_01_4_01_4.html", null ],
    [ "Brush::Signatures&lt; N, enable_if_t&lt; is_in_v&lt; N, NodeType::Before, NodeType::After, NodeType::During &gt; &gt; &gt;", "d8/de1/structBrush_1_1Signatures_3_01N_00_01enable__if__t_3_01is__in__v_3_01N_00_01NodeType_1_1Before_086362e8a3357214e4d1e7ae6488defd0.html", null ],
    [ "Brush::Signatures&lt; N, enable_if_t&lt; is_in_v&lt; N, NodeType::Constant, NodeType::Terminal &gt; &gt; &gt;", "d6/d46/structBrush_1_1Signatures_3_01N_00_01enable__if__t_3_01is__in__v_3_01N_00_01NodeType_1_1Constant596b719ae2fbdba032d4d7caf610588d.html", null ],
    [ "Brush::Signatures&lt; N, enable_if_t&lt; is_in_v&lt; N, NodeType::OffsetSum &gt; &gt; &gt;", "d8/d1c/structBrush_1_1Signatures_3_01N_00_01enable__if__t_3_01is__in__v_3_01N_00_01NodeType_1_1OffsetSum_01_4_01_4_01_4.html", null ],
    [ "Brush::Signatures&lt; N, enable_if_t&lt; is_in_v&lt; N, NodeType::SplitBest, NodeType::CustomSplit &gt; &gt; &gt;", "d2/d1e/structBrush_1_1Signatures_3_01N_00_01enable__if__t_3_01is__in__v_3_01N_00_01NodeType_1_1SplitBesd813f162f676219afb7a127e3ee4a443.html", null ],
    [ "Brush::Signatures&lt; N, enable_if_t&lt; is_in_v&lt; N, NodeType::Sum, NodeType::Prod, NodeType::Min, NodeType::Max, NodeType::Mean, NodeType::Median &gt; &gt; &gt;", "d6/da3/structBrush_1_1Signatures_3_01N_00_01enable__if__t_3_01is__in__v_3_01N_00_01NodeType_1_1Sum_00_083e8a3a604402dec7f5377fa9aae58ea.html", null ],
    [ "Brush::Signatures&lt; NodeType::Count &gt;", "d9/d74/structBrush_1_1Signatures_3_01NodeType_1_1Count_01_4.html", null ],
    [ "Brush::Signatures&lt; NodeType::Equals &gt;", "d4/d61/structBrush_1_1Signatures_3_01NodeType_1_1Equals_01_4.html", null ],
    [ "Brush::Signatures&lt; NodeType::Geq &gt;", "d9/d54/structBrush_1_1Signatures_3_01NodeType_1_1Geq_01_4.html", null ],
    [ "Brush::Signatures&lt; NodeType::MeanLabel &gt;", "da/dca/structBrush_1_1Signatures_3_01NodeType_1_1MeanLabel_01_4.html", null ],
    [ "Brush::Signatures&lt; NodeType::Not &gt;", "d3/d91/structBrush_1_1Signatures_3_01NodeType_1_1Not_01_4.html", null ],
    [ "Brush::Signatures&lt; NodeType::Softmax &gt;", "db/d1c/structBrush_1_1Signatures_3_01NodeType_1_1Softmax_01_4.html", null ],
    [ "Brush::Signatures&lt; NodeType::SplitOn &gt;", "dd/d50/structBrush_1_1Signatures_3_01NodeType_1_1SplitOn_01_4.html", null ],
    [ "Brush::Sel::NSGA2&lt; T &gt;::sort_n", "d1/d20/structBrush_1_1Sel_1_1NSGA2_1_1sort__n.html", null ],
    [ "Brush::Pop::Population&lt; T &gt;::SortComplexity", "d6/dd9/structBrush_1_1Pop_1_1Population_1_1SortComplexity.html", null ],
    [ "Brush::Pop::Population&lt; T &gt;::SortLinearComplexity", "d6/d21/structBrush_1_1Pop_1_1Population_1_1SortLinearComplexity.html", null ],
    [ "string", "d5/d92/classstring.html", null ],
    [ "Brush::Util::Timer", "d8/da4/classBrush_1_1Util_1_1Timer.html", null ],
    [ "Brush::Data::TimeSeries&lt; T &gt;", "d7/d56/structBrush_1_1Data_1_1TimeSeries.html", null ],
    [ "TimeSeries&lt; T &gt;", "d0/d8e/structTimeSeries.html", null ],
    [ "Brush::TinyCostFunction&lt; CostFunctor, DualType, ScalarType, StorageOrder &gt;", "df/d09/structBrush_1_1TinyCostFunction.html", null ],
    [ "tree_node_&lt; T &gt;", "d0/d0e/classtree__node__.html", null ],
    [ "tree_node_&lt; Node &gt;", "dc/d90/classtree__node___3_01Node_01_4.html", null ],
    [ "std::true_type", null, [
      [ "Brush::is_std_array< std::array< V, n > >", "d4/df1/structBrush_1_1is__std__array_3_01std_1_1array_3_01V_00_01n_01_4_01_4.html", null ],
      [ "Brush::is_tuple< std::tuple< T... > >", "df/d54/structBrush_1_1is__tuple_3_01std_1_1tuple_3_01T_8_8_8_01_4_01_4.html", null ]
    ] ],
    [ "Brush::uint32_vector_hasher", "d1/ddf/structBrush_1_1uint32__vector__hasher.html", null ],
    [ "unique_ptr&lt; T &gt;", "dd/d67/classunique__ptr.html", null ],
    [ "Brush::UnJetify&lt; T &gt;", "dd/dc6/structBrush_1_1UnJetify.html", null ],
    [ "Brush::UnJetify&lt; ArrayXbJet &gt;", "d7/dae/structBrush_1_1UnJetify_3_01ArrayXbJet_01_4.html", null ],
    [ "Brush::UnJetify&lt; ArrayXfJet &gt;", "d6/d5c/structBrush_1_1UnJetify_3_01ArrayXfJet_01_4.html", null ],
    [ "Brush::UnJetify&lt; ArrayXiJet &gt;", "db/d0f/structBrush_1_1UnJetify_3_01ArrayXiJet_01_4.html", null ],
    [ "Brush::UnJetify&lt; ArrayXXbJet &gt;", "d4/d8b/structBrush_1_1UnJetify_3_01ArrayXXbJet_01_4.html", null ],
    [ "Brush::UnJetify&lt; ArrayXXfJet &gt;", "d3/d4f/structBrush_1_1UnJetify_3_01ArrayXXfJet_01_4.html", null ],
    [ "Brush::UnJetify&lt; ArrayXXiJet &gt;", "dd/d0d/structBrush_1_1UnJetify_3_01ArrayXXiJet_01_4.html", null ],
    [ "Brush::UnJetify&lt; Data::TimeSeriesbJet &gt;", "da/de1/structBrush_1_1UnJetify_3_01Data_1_1TimeSeriesbJet_01_4.html", null ],
    [ "Brush::UnJetify&lt; Data::TimeSeriesfJet &gt;", "df/d76/structBrush_1_1UnJetify_3_01Data_1_1TimeSeriesfJet_01_4.html", null ],
    [ "Brush::UnJetify&lt; Data::TimeSeriesiJet &gt;", "dc/d96/structBrush_1_1UnJetify_3_01Data_1_1TimeSeriesiJet_01_4.html", null ],
    [ "Brush::Var::Variation&lt; T &gt;", "d5/d14/classBrush_1_1Var_1_1Variation.html", null ],
    [ "vector&lt; T &gt;", "d7/dfc/classvector.html", null ],
    [ "Brush::WeightOptimizer", "d7/d79/structBrush_1_1WeightOptimizer.html", null ],
    [ "Brush::WeightType&lt; T &gt;", "da/d54/structBrush_1_1WeightType.html", null ]
];