var hierarchy =
[
    [ "nlohmann::adl_serializer< std::shared_ptr< T > >", "d8/d3c/structnlohmann_1_1adl__serializer_3_01std_1_1shared__ptr_3_01T_01_4_01_4.html", null ],
    [ "Brush::all_same< First, Next >", "db/d64/structBrush_1_1all__same.html", null ],
    [ "Brush::Pop::Archive< T >", "d1/d30/structBrush_1_1Pop_1_1Archive.html", null ],
    [ "array< T >", "d2/d41/classarray.html", null ],
    [ "Brush::Sel::NSGA2< T >::comparator_obj", "dd/dc3/structBrush_1_1Sel_1_1NSGA2_1_1comparator__obj.html", null ],
    [ "array< T >::const_iterator", "dc/d95/classarray_1_1const__iterator.html", null ],
    [ "map< K, T >::const_iterator", "d8/d46/classmap_1_1const__iterator.html", null ],
    [ "set< K >::const_iterator", "d2/da2/classset_1_1const__iterator.html", null ],
    [ "string::const_iterator", "d1/df2/classstring_1_1const__iterator.html", null ],
    [ "vector< T >::const_iterator", "d4/df5/classvector_1_1const__iterator.html", null ],
    [ "array< T >::const_reverse_iterator", "d3/d18/classarray_1_1const__reverse__iterator.html", null ],
    [ "map< K, T >::const_reverse_iterator", "dd/da0/classmap_1_1const__reverse__iterator.html", null ],
    [ "set< K >::const_reverse_iterator", "d0/d6a/classset_1_1const__reverse__iterator.html", null ],
    [ "string::const_reverse_iterator", "dc/dda/classstring_1_1const__reverse__iterator.html", null ],
    [ "vector< T >::const_reverse_iterator", "dd/d51/classvector_1_1const__reverse__iterator.html", null ],
    [ "Brush::DataEnumType< D >", "d8/d17/structBrush_1_1DataEnumType.html", null ],
    [ "Brush::DataEnumType< DT::ArrayB >", "d6/d53/structBrush_1_1DataEnumType_3_01DT_1_1ArrayB_01_4.html", null ],
    [ "Brush::DataEnumType< DT::ArrayBJet >", "d4/dcb/structBrush_1_1DataEnumType_3_01DT_1_1ArrayBJet_01_4.html", null ],
    [ "Brush::DataEnumType< DT::ArrayF >", "df/dc3/structBrush_1_1DataEnumType_3_01DT_1_1ArrayF_01_4.html", null ],
    [ "Brush::DataEnumType< DT::ArrayFJet >", "d4/d9c/structBrush_1_1DataEnumType_3_01DT_1_1ArrayFJet_01_4.html", null ],
    [ "Brush::DataEnumType< DT::ArrayI >", "db/d06/structBrush_1_1DataEnumType_3_01DT_1_1ArrayI_01_4.html", null ],
    [ "Brush::DataEnumType< DT::ArrayIJet >", "dc/db4/structBrush_1_1DataEnumType_3_01DT_1_1ArrayIJet_01_4.html", null ],
    [ "Brush::DataEnumType< DT::MatrixB >", "de/dd1/structBrush_1_1DataEnumType_3_01DT_1_1MatrixB_01_4.html", null ],
    [ "Brush::DataEnumType< DT::MatrixBJet >", "dd/d86/structBrush_1_1DataEnumType_3_01DT_1_1MatrixBJet_01_4.html", null ],
    [ "Brush::DataEnumType< DT::MatrixF >", "d9/df1/structBrush_1_1DataEnumType_3_01DT_1_1MatrixF_01_4.html", null ],
    [ "Brush::DataEnumType< DT::MatrixFJet >", "d0/d7c/structBrush_1_1DataEnumType_3_01DT_1_1MatrixFJet_01_4.html", null ],
    [ "Brush::DataEnumType< DT::MatrixI >", "d6/de7/structBrush_1_1DataEnumType_3_01DT_1_1MatrixI_01_4.html", null ],
    [ "Brush::DataEnumType< DT::MatrixIJet >", "dc/ded/structBrush_1_1DataEnumType_3_01DT_1_1MatrixIJet_01_4.html", null ],
    [ "Brush::DataEnumType< DT::TimeSeriesB >", "dc/dd6/structBrush_1_1DataEnumType_3_01DT_1_1TimeSeriesB_01_4.html", null ],
    [ "Brush::DataEnumType< DT::TimeSeriesF >", "d2/db8/structBrush_1_1DataEnumType_3_01DT_1_1TimeSeriesF_01_4.html", null ],
    [ "Brush::DataEnumType< DT::TimeSeriesI >", "dd/dff/structBrush_1_1DataEnumType_3_01DT_1_1TimeSeriesI_01_4.html", null ],
    [ "Brush::Data::Dataset", "d2/d36/classBrush_1_1Data_1_1Dataset.html", null ],
    [ "Dataset", "d7/da5/classDataset.html", null ],
    [ "Brush::DataTypeEnum< T >", "df/d3e/structBrush_1_1DataTypeEnum.html", null ],
    [ "Brush::DataTypeEnum< ArrayXb >", "d7/d9a/structBrush_1_1DataTypeEnum_3_01ArrayXb_01_4.html", null ],
    [ "Brush::DataTypeEnum< ArrayXbJet >", "d7/d76/structBrush_1_1DataTypeEnum_3_01ArrayXbJet_01_4.html", null ],
    [ "Brush::DataTypeEnum< ArrayXf >", "d9/d96/structBrush_1_1DataTypeEnum_3_01ArrayXf_01_4.html", null ],
    [ "Brush::DataTypeEnum< ArrayXfJet >", "d4/d46/structBrush_1_1DataTypeEnum_3_01ArrayXfJet_01_4.html", null ],
    [ "Brush::DataTypeEnum< ArrayXi >", "d7/d35/structBrush_1_1DataTypeEnum_3_01ArrayXi_01_4.html", null ],
    [ "Brush::DataTypeEnum< ArrayXiJet >", "d4/dd1/structBrush_1_1DataTypeEnum_3_01ArrayXiJet_01_4.html", null ],
    [ "Brush::DataTypeEnum< ArrayXXb >", "d7/d17/structBrush_1_1DataTypeEnum_3_01ArrayXXb_01_4.html", null ],
    [ "Brush::DataTypeEnum< ArrayXXbJet >", "da/d1f/structBrush_1_1DataTypeEnum_3_01ArrayXXbJet_01_4.html", null ],
    [ "Brush::DataTypeEnum< ArrayXXf >", "df/dc9/structBrush_1_1DataTypeEnum_3_01ArrayXXf_01_4.html", null ],
    [ "Brush::DataTypeEnum< ArrayXXfJet >", "d7/d70/structBrush_1_1DataTypeEnum_3_01ArrayXXfJet_01_4.html", null ],
    [ "Brush::DataTypeEnum< ArrayXXi >", "de/dcc/structBrush_1_1DataTypeEnum_3_01ArrayXXi_01_4.html", null ],
    [ "Brush::DataTypeEnum< ArrayXXiJet >", "dc/d84/structBrush_1_1DataTypeEnum_3_01ArrayXXiJet_01_4.html", null ],
    [ "Brush::DataTypeEnum< Data::TimeSeriesb >", "d6/d27/structBrush_1_1DataTypeEnum_3_01Data_1_1TimeSeriesb_01_4.html", null ],
    [ "Brush::DataTypeEnum< Data::TimeSeriesbJet >", "d6/d3c/structBrush_1_1DataTypeEnum_3_01Data_1_1TimeSeriesbJet_01_4.html", null ],
    [ "Brush::DataTypeEnum< Data::TimeSeriesf >", "df/d37/structBrush_1_1DataTypeEnum_3_01Data_1_1TimeSeriesf_01_4.html", null ],
    [ "Brush::DataTypeEnum< Data::TimeSeriesfJet >", "d1/d94/structBrush_1_1DataTypeEnum_3_01Data_1_1TimeSeriesfJet_01_4.html", null ],
    [ "Brush::DataTypeEnum< Data::TimeSeriesi >", "d5/d29/structBrush_1_1DataTypeEnum_3_01Data_1_1TimeSeriesi_01_4.html", null ],
    [ "Brush::DataTypeEnum< Data::TimeSeriesiJet >", "da/d56/structBrush_1_1DataTypeEnum_3_01Data_1_1TimeSeriesiJet_01_4.html", null ],
    [ "Brush::DispatchTable< Fit >", "d3/da8/structBrush_1_1DispatchTable.html", null ],
    [ "Brush::Engine< T >", "d0/d75/classBrush_1_1Engine.html", null ],
    [ "Brush::Eval::Evaluation< T >", "d1/de5/classBrush_1_1Eval_1_1Evaluation.html", null ],
    [ "std::false_type", null, [
      [ "Brush::is_std_array< std::array< V, n > >", "d4/df1/structBrush_1_1is__std__array_3_01std_1_1array_3_01V_00_01n_01_4_01_4.html", null ],
      [ "Brush::is_tuple< std::tuple< T... > >", "df/d54/structBrush_1_1is__tuple_3_01std_1_1tuple_3_01T_8_8_8_01_4_01_4.html", null ],
      [ "Brush::is_std_array< T >", "d6/dfa/structBrush_1_1is__std__array.html", null ],
      [ "Brush::is_tuple< typename >", "d0/d4c/structBrush_1_1is__tuple.html", null ]
    ] ],
    [ "Brush::Fitness", "d6/dd0/structBrush_1_1Fitness.html", null ],
    [ "formatter", null, [
      [ "fmt::formatter< Brush::Data::TimeSeriesb >", "db/d20/structfmt_1_1formatter_3_01Brush_1_1Data_1_1TimeSeriesb_01_4.html", null ],
      [ "fmt::formatter< Brush::Data::TimeSeriesf >", "d5/dd4/structfmt_1_1formatter_3_01Brush_1_1Data_1_1TimeSeriesf_01_4.html", null ],
      [ "fmt::formatter< Brush::Data::TimeSeriesi >", "dd/dc8/structfmt_1_1formatter_3_01Brush_1_1Data_1_1TimeSeriesi_01_4.html", null ],
      [ "fmt::formatter< Brush::DataType >", "de/d6b/structfmt_1_1formatter_3_01Brush_1_1DataType_01_4.html", null ],
      [ "fmt::formatter< Brush::Node >", "d4/d63/structfmt_1_1formatter_3_01Brush_1_1Node_01_4.html", null ],
      [ "fmt::formatter< Brush::NodeType >", "d4/d42/structfmt_1_1formatter_3_01Brush_1_1NodeType_01_4.html", null ],
      [ "fmt::formatter< Brush::SearchSpace >", "d7/de7/structfmt_1_1formatter_3_01Brush_1_1SearchSpace_01_4.html", null ]
    ] ],
    [ "Brush::Function< N >", "d9/d1b/structBrush_1_1Function.html", null ],
    [ "Brush::Function< NodeType::Abs >", "d0/de7/structBrush_1_1Function_3_01NodeType_1_1Abs_01_4.html", null ],
    [ "Brush::Function< NodeType::Acos >", "d3/d84/structBrush_1_1Function_3_01NodeType_1_1Acos_01_4.html", null ],
    [ "Brush::Function< NodeType::Add >", "de/d7a/structBrush_1_1Function_3_01NodeType_1_1Add_01_4.html", null ],
    [ "Brush::Function< NodeType::After >", "d8/dca/structBrush_1_1Function_3_01NodeType_1_1After_01_4.html", null ],
    [ "Brush::Function< NodeType::And >", "de/d19/structBrush_1_1Function_3_01NodeType_1_1And_01_4.html", null ],
    [ "Brush::Function< NodeType::ArgMax >", "d6/da6/structBrush_1_1Function_3_01NodeType_1_1ArgMax_01_4.html", null ],
    [ "Brush::Function< NodeType::Asin >", "d5/d79/structBrush_1_1Function_3_01NodeType_1_1Asin_01_4.html", null ],
    [ "Brush::Function< NodeType::Atan >", "d7/d62/structBrush_1_1Function_3_01NodeType_1_1Atan_01_4.html", null ],
    [ "Brush::Function< NodeType::Before >", "dc/dd3/structBrush_1_1Function_3_01NodeType_1_1Before_01_4.html", null ],
    [ "Brush::Function< NodeType::Ceil >", "db/d67/structBrush_1_1Function_3_01NodeType_1_1Ceil_01_4.html", null ],
    [ "Brush::Function< NodeType::Cos >", "d5/d44/structBrush_1_1Function_3_01NodeType_1_1Cos_01_4.html", null ],
    [ "Brush::Function< NodeType::Cosh >", "d2/de4/structBrush_1_1Function_3_01NodeType_1_1Cosh_01_4.html", null ],
    [ "Brush::Function< NodeType::Count >", "d5/d32/structBrush_1_1Function_3_01NodeType_1_1Count_01_4.html", null ],
    [ "Brush::Function< NodeType::Div >", "d3/d6e/structBrush_1_1Function_3_01NodeType_1_1Div_01_4.html", null ],
    [ "Brush::Function< NodeType::During >", "de/da7/structBrush_1_1Function_3_01NodeType_1_1During_01_4.html", null ],
    [ "Brush::Function< NodeType::Exp >", "d8/d59/structBrush_1_1Function_3_01NodeType_1_1Exp_01_4.html", null ],
    [ "Brush::Function< NodeType::Floor >", "d9/d4c/structBrush_1_1Function_3_01NodeType_1_1Floor_01_4.html", null ],
    [ "Brush::Function< NodeType::Log >", "d4/db0/structBrush_1_1Function_3_01NodeType_1_1Log_01_4.html", null ],
    [ "Brush::Function< NodeType::Log1p >", "d6/d39/structBrush_1_1Function_3_01NodeType_1_1Log1p_01_4.html", null ],
    [ "Brush::Function< NodeType::Logabs >", "d3/d95/structBrush_1_1Function_3_01NodeType_1_1Logabs_01_4.html", null ],
    [ "Brush::Function< NodeType::Logistic >", "d5/db7/structBrush_1_1Function_3_01NodeType_1_1Logistic_01_4.html", null ],
    [ "Brush::Function< NodeType::Max >", "d0/d4d/structBrush_1_1Function_3_01NodeType_1_1Max_01_4.html", null ],
    [ "Brush::Function< NodeType::Mean >", "d1/d36/structBrush_1_1Function_3_01NodeType_1_1Mean_01_4.html", null ],
    [ "Brush::Function< NodeType::Median >", "d2/d84/structBrush_1_1Function_3_01NodeType_1_1Median_01_4.html", null ],
    [ "Brush::Function< NodeType::Min >", "d8/d4a/structBrush_1_1Function_3_01NodeType_1_1Min_01_4.html", null ],
    [ "Brush::Function< NodeType::Mul >", "d7/dd7/structBrush_1_1Function_3_01NodeType_1_1Mul_01_4.html", null ],
    [ "Brush::Function< NodeType::Not >", "d4/d67/structBrush_1_1Function_3_01NodeType_1_1Not_01_4.html", null ],
    [ "Brush::Function< NodeType::OffsetSum >", "dc/dcc/structBrush_1_1Function_3_01NodeType_1_1OffsetSum_01_4.html", null ],
    [ "Brush::Function< NodeType::Or >", "d4/d1b/structBrush_1_1Function_3_01NodeType_1_1Or_01_4.html", null ],
    [ "Brush::Function< NodeType::Pow >", "da/d0e/structBrush_1_1Function_3_01NodeType_1_1Pow_01_4.html", null ],
    [ "Brush::Function< NodeType::Prod >", "d7/d7e/structBrush_1_1Function_3_01NodeType_1_1Prod_01_4.html", null ],
    [ "Brush::Function< NodeType::Sin >", "d7/d76/structBrush_1_1Function_3_01NodeType_1_1Sin_01_4.html", null ],
    [ "Brush::Function< NodeType::Sinh >", "d5/d7d/structBrush_1_1Function_3_01NodeType_1_1Sinh_01_4.html", null ],
    [ "Brush::Function< NodeType::Softmax >", "d3/def/structBrush_1_1Function_3_01NodeType_1_1Softmax_01_4.html", null ],
    [ "Brush::Function< NodeType::SplitOn >", "d8/d1f/structBrush_1_1Function_3_01NodeType_1_1SplitOn_01_4.html", null ],
    [ "Brush::Function< NodeType::Sqrt >", "d1/dc4/structBrush_1_1Function_3_01NodeType_1_1Sqrt_01_4.html", null ],
    [ "Brush::Function< NodeType::Sqrtabs >", "db/d25/structBrush_1_1Function_3_01NodeType_1_1Sqrtabs_01_4.html", null ],
    [ "Brush::Function< NodeType::Square >", "db/dba/structBrush_1_1Function_3_01NodeType_1_1Square_01_4.html", null ],
    [ "Brush::Function< NodeType::Sub >", "d0/d24/structBrush_1_1Function_3_01NodeType_1_1Sub_01_4.html", null ],
    [ "Brush::Function< NodeType::Sum >", "d8/d9c/structBrush_1_1Function_3_01NodeType_1_1Sum_01_4.html", null ],
    [ "Brush::Function< NodeType::Tan >", "d7/d8e/structBrush_1_1Function_3_01NodeType_1_1Tan_01_4.html", null ],
    [ "Brush::Function< NodeType::Tanh >", "dc/d5d/structBrush_1_1Function_3_01NodeType_1_1Tanh_01_4.html", null ],
    [ "std::hash< std::tuple< TT... > >", "de/d30/structstd_1_1hash_3_01std_1_1tuple_3_01TT_8_8_8_01_4_01_4.html", null ],
    [ "std::hash< std::vector< float > >", "d4/d0d/structstd_1_1hash_3_01std_1_1vector_3_01float_01_4_01_4.html", null ],
    [ "Brush::Pop::Individual< T >", "de/d83/classBrush_1_1Pop_1_1Individual.html", null ],
    [ "std::is_base_of", null, [
      [ "Brush::is_eigen_array< T >", "df/d72/structBrush_1_1is__eigen__array.html", null ]
    ] ],
    [ "is_in< T, Ts >", "d0/d80/structis__in.html", null ],
    [ "Brush::is_one_of< First, Next >", "d3/d0e/structBrush_1_1is__one__of.html", null ],
    [ "array< T >::iterator", "d9/dcc/classarray_1_1iterator.html", null ],
    [ "map< K, T >::iterator", "dd/d7b/classmap_1_1iterator.html", null ],
    [ "set< K >::iterator", "dd/d43/classset_1_1iterator.html", null ],
    [ "string::iterator", "d5/d16/classstring_1_1iterator.html", null ],
    [ "vector< T >::iterator", "d0/d05/classvector_1_1iterator.html", null ],
    [ "Brush::Jetify< T >", "de/d30/structBrush_1_1Jetify.html", null ],
    [ "Brush::Jetify< ArrayXb >", "da/dd5/structBrush_1_1Jetify_3_01ArrayXb_01_4.html", null ],
    [ "Brush::Jetify< ArrayXf >", "d4/d10/structBrush_1_1Jetify_3_01ArrayXf_01_4.html", null ],
    [ "Brush::Jetify< ArrayXi >", "dc/d2f/structBrush_1_1Jetify_3_01ArrayXi_01_4.html", null ],
    [ "Brush::Jetify< ArrayXXb >", "d9/d13/structBrush_1_1Jetify_3_01ArrayXXb_01_4.html", null ],
    [ "Brush::Jetify< ArrayXXf >", "da/d99/structBrush_1_1Jetify_3_01ArrayXXf_01_4.html", null ],
    [ "Brush::Jetify< ArrayXXi >", "d2/d53/structBrush_1_1Jetify_3_01ArrayXXi_01_4.html", null ],
    [ "Brush::Jetify< Data::TimeSeriesb >", "d4/d01/structBrush_1_1Jetify_3_01Data_1_1TimeSeriesb_01_4.html", null ],
    [ "Brush::Jetify< Data::TimeSeriesf >", "da/dc3/structBrush_1_1Jetify_3_01Data_1_1TimeSeriesf_01_4.html", null ],
    [ "Brush::Jetify< Data::TimeSeriesi >", "d9/da6/structBrush_1_1Jetify_3_01Data_1_1TimeSeriesi_01_4.html", null ],
    [ "Brush::Util::Log_Stats", "db/d7e/structBrush_1_1Util_1_1Log__Stats.html", null ],
    [ "Brush::Util::Logger", "dd/d56/classBrush_1_1Util_1_1Logger.html", null ],
    [ "map< K, T >", "d9/d28/classmap.html", null ],
    [ "Brush::Var::MutationBase", "d0/dec/classBrush_1_1Var_1_1MutationBase.html", [
      [ "Brush::Var::DeleteMutation", "d0/d6d/classBrush_1_1Var_1_1DeleteMutation.html", null ],
      [ "Brush::Var::InsertMutation", "dc/de3/classBrush_1_1Var_1_1InsertMutation.html", null ],
      [ "Brush::Var::PointMutation", "d4/d46/classBrush_1_1Var_1_1PointMutation.html", null ],
      [ "Brush::Var::SubtreeMutation", "de/d23/classBrush_1_1Var_1_1SubtreeMutation.html", null ],
      [ "Brush::Var::ToggleWeightOffMutation", "dd/d55/classBrush_1_1Var_1_1ToggleWeightOffMutation.html", null ],
      [ "Brush::Var::ToggleWeightOnMutation", "d2/d1a/classBrush_1_1Var_1_1ToggleWeightOnMutation.html", null ]
    ] ],
    [ "Brush::NarySignature< R, Arg, ArgCount, Indices >", "d6/df7/structBrush_1_1NarySignature.html", null ],
    [ "Brush::NarySignatures< R, Arg, MaxArgCount >", "d9/da6/structBrush_1_1NarySignatures.html", null ],
    [ "Brush::Node", "d1/d3a/structBrush_1_1Node.html", null ],
    [ "Node", "d8/d49/structNode.html", null ],
    [ "Brush::NodeTypes", "db/d53/structBrush_1_1NodeTypes.html", null ],
    [ "Brush::Util::Normalizer", "d2/df8/structBrush_1_1Util_1_1Normalizer.html", null ],
    [ "Brush::Data::OmopData", "dc/d67/structBrush_1_1Data_1_1OmopData.html", null ],
    [ "Brush::Operator< NT, S, Fit, E >", "dc/d31/structBrush_1_1Operator.html", null ],
    [ "Brush::Operator< NodeType::Constant, S, Fit >", "df/dc1/structBrush_1_1Operator_3_01NodeType_1_1Constant_00_01S_00_01Fit_01_4.html", null ],
    [ "Brush::Operator< NodeType::MeanLabel, S, Fit >", "d9/d5e/structBrush_1_1Operator_3_01NodeType_1_1MeanLabel_00_01S_00_01Fit_01_4.html", null ],
    [ "Brush::Operator< NodeType::Terminal, S, Fit >", "dd/d88/structBrush_1_1Operator_3_01NodeType_1_1Terminal_00_01S_00_01Fit_01_4.html", null ],
    [ "Brush::Operator< NT, S, Fit, enable_if_t< is_in_v< NT, NodeType::SplitOn, NodeType::SplitBest > > >", "db/d1f/structBrush_1_1Operator_3_01NT_00_01S_00_01Fit_00_01enable__if__t_3_01is__in__v_3_01NT_00_01Node0d34d2b97afea7b3bb37b94bd97cbb86.html", null ],
    [ "Operator< NT, S, Fit, enable_if_t< is_in_v< NT, NodeType::SplitOn, NodeType::SplitBest > > >", "d3/df2/structOperator_3_01NT_00_01S_00_01Fit_00_01enable__if__t_3_01is__in__v_3_01NT_00_01NodeType_1_1Se4750a8ecc1d24ba81c8da2bd5c73a14.html", null ],
    [ "Brush::OptimizerSummary", "dc/d91/structBrush_1_1OptimizerSummary.html", null ],
    [ "Brush::Parameters", "de/deb/structBrush_1_1Parameters.html", null ],
    [ "Brush::Pop::Population< T >", "da/da3/classBrush_1_1Pop_1_1Population.html", null ],
    [ "Brush::Program< PType >", "db/d88/structBrush_1_1Program.html", null ],
    [ "Brush::ResidualEvaluator< PT >", "d4/d70/structBrush_1_1ResidualEvaluator.html", null ],
    [ "array< T >::reverse_iterator", "dd/d20/classarray_1_1reverse__iterator.html", null ],
    [ "map< K, T >::reverse_iterator", "dc/ddc/classmap_1_1reverse__iterator.html", null ],
    [ "set< K >::reverse_iterator", "d8/d5a/classset_1_1reverse__iterator.html", null ],
    [ "string::reverse_iterator", "d0/d8d/classstring_1_1reverse__iterator.html", null ],
    [ "vector< T >::reverse_iterator", "dd/d96/classvector_1_1reverse__iterator.html", null ],
    [ "Brush::Util::Rnd", "d2/d2d/classBrush_1_1Util_1_1Rnd.html", null ],
    [ "Brush::Pop::Population< T >::SameFitComplexity", "d4/de2/structBrush_1_1Pop_1_1Population_1_1SameFitComplexity.html", null ],
    [ "Brush::Eval::Scorer< P >", "da/d4c/classBrush_1_1Eval_1_1Scorer.html", null ],
    [ "Brush::Eval::Scorer< P >", "d1/d73/classBrush_1_1Eval_1_1Scorer_3_01P_01_4.html", null ],
    [ "Brush::SearchSpace", "d4/dc3/structBrush_1_1SearchSpace.html", null ],
    [ "SearchSpace", "de/d87/structSearchSpace.html", null ],
    [ "Brush::Sel::Selection< T >", "dd/d0f/structBrush_1_1Sel_1_1Selection.html", null ],
    [ "Brush::Sel::SelectionOperator< T >", "de/db9/classBrush_1_1Sel_1_1SelectionOperator.html", [
      [ "Brush::Sel::Lexicase< T >", "d2/dd0/classBrush_1_1Sel_1_1Lexicase.html", null ],
      [ "Brush::Sel::NSGA2< T >", "d3/d7d/classBrush_1_1Sel_1_1NSGA2.html", null ]
    ] ],
    [ "set< K >", "d0/d59/classset.html", null ],
    [ "shared_ptr< T >", "d4/d67/classshared__ptr.html", null ],
    [ "Brush::SigBase< R, Args >", "da/dd5/structBrush_1_1SigBase.html", null ],
    [ "Brush::SigBase< R >", "dc/da5/structBrush_1_1SigBase_3_01R_01_4.html", null ],
    [ "Brush::SigBase< R, Args... >", "da/dd5/structBrush_1_1SigBase.html", [
      [ "Brush::Signature< R(Args...)>", "d5/d7d/structBrush_1_1Signature_3_01R_07Args_8_8_8_08_4.html", null ]
    ] ],
    [ "Brush::Signature< T >", "d2/d75/structBrush_1_1Signature.html", null ],
    [ "Brush::Signatures< N, T >", "d1/d9a/structBrush_1_1Signatures.html", null ],
    [ "Brush::Signatures< N, enable_if_t< is_in_v< N, NodeType::Abs, NodeType::Acos, NodeType::Asin, NodeType::Atan, NodeType::Cos, NodeType::Cosh, NodeType::Sin, NodeType::Sinh, NodeType::Tan, NodeType::Tanh, NodeType::Ceil, NodeType::Floor, NodeType::Exp, NodeType::Log, NodeType::Logabs, NodeType::Log1p, NodeType::Sqrt, NodeType::Sqrtabs, NodeType::Square, NodeType::Logistic, NodeType::OffsetSum > > >", "d2/def/structBrush_1_1Signatures_3_01N_00_01enable__if__t_3_01is__in__v_3_01N_00_01NodeType_1_1Abs_00_0aeef5405a01257b84f9033923028819e.html", null ],
    [ "Brush::Signatures< N, enable_if_t< is_in_v< N, NodeType::Add, NodeType::Sub, NodeType::Mul, NodeType::Div, NodeType::Pow > > >", "d2/d82/structBrush_1_1Signatures_3_01N_00_01enable__if__t_3_01is__in__v_3_01N_00_01NodeType_1_1Add_00_02ae8c79e1c3eb458e9c5f6f94e9a9b11.html", null ],
    [ "Brush::Signatures< N, enable_if_t< is_in_v< N, NodeType::And, NodeType::Or > > >", "d6/d2d/structBrush_1_1Signatures_3_01N_00_01enable__if__t_3_01is__in__v_3_01N_00_01NodeType_1_1And_00_01NodeType_1_1Or_01_4_01_4_01_4.html", null ],
    [ "Brush::Signatures< N, enable_if_t< is_in_v< N, NodeType::ArgMax > > >", "dd/d56/structBrush_1_1Signatures_3_01N_00_01enable__if__t_3_01is__in__v_3_01N_00_01NodeType_1_1ArgMax_01_4_01_4_01_4.html", null ],
    [ "Brush::Signatures< N, enable_if_t< is_in_v< N, NodeType::Before, NodeType::After, NodeType::During > > >", "d8/de1/structBrush_1_1Signatures_3_01N_00_01enable__if__t_3_01is__in__v_3_01N_00_01NodeType_1_1Before_086362e8a3357214e4d1e7ae6488defd0.html", null ],
    [ "Brush::Signatures< N, enable_if_t< is_in_v< N, NodeType::Constant, NodeType::Terminal > > >", "d6/d46/structBrush_1_1Signatures_3_01N_00_01enable__if__t_3_01is__in__v_3_01N_00_01NodeType_1_1Constant596b719ae2fbdba032d4d7caf610588d.html", null ],
    [ "Brush::Signatures< N, enable_if_t< is_in_v< N, NodeType::SplitBest, NodeType::CustomSplit > > >", "d2/d1e/structBrush_1_1Signatures_3_01N_00_01enable__if__t_3_01is__in__v_3_01N_00_01NodeType_1_1SplitBesd813f162f676219afb7a127e3ee4a443.html", null ],
    [ "Brush::Signatures< N, enable_if_t< is_in_v< N, NodeType::Sum, NodeType::Prod, NodeType::Min, NodeType::Max, NodeType::Mean, NodeType::Median > > >", "d6/da3/structBrush_1_1Signatures_3_01N_00_01enable__if__t_3_01is__in__v_3_01N_00_01NodeType_1_1Sum_00_083e8a3a604402dec7f5377fa9aae58ea.html", null ],
    [ "Brush::Signatures< NodeType::Count >", "d9/d74/structBrush_1_1Signatures_3_01NodeType_1_1Count_01_4.html", null ],
    [ "Brush::Signatures< NodeType::MeanLabel >", "da/dca/structBrush_1_1Signatures_3_01NodeType_1_1MeanLabel_01_4.html", null ],
    [ "Brush::Signatures< NodeType::Not >", "d3/d91/structBrush_1_1Signatures_3_01NodeType_1_1Not_01_4.html", null ],
    [ "Brush::Signatures< NodeType::Softmax >", "db/d1c/structBrush_1_1Signatures_3_01NodeType_1_1Softmax_01_4.html", null ],
    [ "Brush::Signatures< NodeType::SplitOn >", "dd/d50/structBrush_1_1Signatures_3_01NodeType_1_1SplitOn_01_4.html", null ],
    [ "Brush::Sel::NSGA2< T >::sort_n", "d1/d20/structBrush_1_1Sel_1_1NSGA2_1_1sort__n.html", null ],
    [ "Brush::Pop::Population< T >::SortComplexity", "d6/dd9/structBrush_1_1Pop_1_1Population_1_1SortComplexity.html", null ],
    [ "string", "d5/d92/classstring.html", null ],
    [ "Brush::Util::Timer", "d8/da4/classBrush_1_1Util_1_1Timer.html", null ],
    [ "Brush::Data::TimeSeries< T >", "d7/d56/structBrush_1_1Data_1_1TimeSeries.html", null ],
    [ "TimeSeries< T >", "d0/d8e/structTimeSeries.html", null ],
    [ "Brush::TinyCostFunction< CostFunctor, DualType, ScalarType, StorageOrder >", "df/d09/structBrush_1_1TinyCostFunction.html", null ],
    [ "tree_node_< T >", "d0/d0e/classtree__node__.html", null ],
    [ "tree_node_< Node >", "dc/d90/classtree__node___3_01Node_01_4.html", null ],
    [ "std::true_type", null, [
      [ "Brush::is_std_array< std::array< V, n > >", "d4/df1/structBrush_1_1is__std__array_3_01std_1_1array_3_01V_00_01n_01_4_01_4.html", null ],
      [ "Brush::is_tuple< std::tuple< T... > >", "df/d54/structBrush_1_1is__tuple_3_01std_1_1tuple_3_01T_8_8_8_01_4_01_4.html", null ]
    ] ],
    [ "Brush::uint32_vector_hasher", "d1/ddf/structBrush_1_1uint32__vector__hasher.html", null ],
    [ "unique_ptr< T >", "dd/d67/classunique__ptr.html", null ],
    [ "Brush::UnJetify< T >", "dd/dc6/structBrush_1_1UnJetify.html", null ],
    [ "Brush::UnJetify< ArrayXbJet >", "d7/dae/structBrush_1_1UnJetify_3_01ArrayXbJet_01_4.html", null ],
    [ "Brush::UnJetify< ArrayXfJet >", "d6/d5c/structBrush_1_1UnJetify_3_01ArrayXfJet_01_4.html", null ],
    [ "Brush::UnJetify< ArrayXiJet >", "db/d0f/structBrush_1_1UnJetify_3_01ArrayXiJet_01_4.html", null ],
    [ "Brush::UnJetify< ArrayXXbJet >", "d4/d8b/structBrush_1_1UnJetify_3_01ArrayXXbJet_01_4.html", null ],
    [ "Brush::UnJetify< ArrayXXfJet >", "d3/d4f/structBrush_1_1UnJetify_3_01ArrayXXfJet_01_4.html", null ],
    [ "Brush::UnJetify< ArrayXXiJet >", "dd/d0d/structBrush_1_1UnJetify_3_01ArrayXXiJet_01_4.html", null ],
    [ "Brush::UnJetify< Data::TimeSeriesbJet >", "da/de1/structBrush_1_1UnJetify_3_01Data_1_1TimeSeriesbJet_01_4.html", null ],
    [ "Brush::UnJetify< Data::TimeSeriesfJet >", "df/d76/structBrush_1_1UnJetify_3_01Data_1_1TimeSeriesfJet_01_4.html", null ],
    [ "Brush::UnJetify< Data::TimeSeriesiJet >", "dc/d96/structBrush_1_1UnJetify_3_01Data_1_1TimeSeriesiJet_01_4.html", null ],
    [ "Brush::Var::Variation< T >", "d5/d14/classBrush_1_1Var_1_1Variation.html", null ],
    [ "vector< T >", "d7/dfc/classvector.html", null ],
    [ "Brush::WeightOptimizer", "d7/d79/structBrush_1_1WeightOptimizer.html", null ],
    [ "Brush::WeightType< T >", "da/d54/structBrush_1_1WeightType.html", null ]
];