Split
ArrayXb Split::threshold_mask(const T &x, const float &threshold)
Applies a learned threshold to a feature, returning a mask.
Referenced by best_threshold, Operator< NT, S, Fit, enable_if_t< is_in_v< NT, NodeType::SplitOn, NodeType::SplitBest > > >::predict, Brush::Split::threshold_mask< State >.
requires same_as<typename T::Scalar, bool> ArrayXb Split::threshold_mask(const T &x, const float &threshold)
Applies a learned threshold to a feature, returning a mask.
requires same_as<typename T::Scalar, bJet> ArrayXb Split::threshold_mask(const T &x, const float &threshold)
Applies a learned threshold to a feature, returning a mask.
requires same_as<typename T::Scalar, float> ArrayXb Split::threshold_mask(const T &x, const float &threshold)
Applies a learned threshold to a feature, returning a mask.
requires same_as<typename T::Scalar, fJet> ArrayXb Split::threshold_mask(const T &x, const float &threshold)
Applies a learned threshold to a feature, returning a mask.
requires same_as<typename T::Scalar, int> ArrayXb Split::threshold_mask(const T &x, const float &threshold)
Applies a learned threshold to a feature, returning a mask.
requires same_as<typename T::Scalar, iJet> ArrayXb Split::threshold_mask(const T &x, const float &threshold)
Applies a learned threshold to a feature, returning a mask.
Referenced by best_threshold, Operator< NT, S, Fit, enable_if_t< is_in_v< NT, NodeType::SplitOn, NodeType::SplitBest > > >::predict, Brush::Split::threshold_mask< State >.
float Split::gini_impurity_index(const ArrayXf &classes, const vector< float > &uc)
float Split::gain(const ArrayXf &lsplit, const ArrayXf &rsplit, bool classification, vector< float > unique_classes)
Referenced by best_threshold.
vector<float> Split::get_thresholds(const T &x)
Referenced by best_threshold.
tuple<string,float> Split::get_best_variable_and_threshold(const Dataset &d, TreeNode &tn)
Referenced by Operator< NT, S, Fit, enable_if_t< is_in_v< NT, NodeType::SplitOn, NodeType::SplitBest > > >::fit.
tuple<float,float> Split::best_threshold(const T &x, const ArrayXf &y, bool classification)
References gain, get_thresholds, Brush::Util::mask_to_indices, MAX_FLT, threshold_mask, Brush::Util::unique.
Referenced by Operator< NT, S, Fit, enable_if_t< is_in_v< NT, NodeType::SplitOn, NodeType::SplitBest > > >::fit, get_best_threshold_by_type.
void Split::get_best_threshold_by_type(const Dataset &d, auto &results)
References best_threshold, MAX_FLT.
auto Split::get_best_thresholds(const Dataset &d, std::index_sequence< Is... >)
T Split::stitch(array< T, 2 > &child_outputs, const ArrayXb &mask)
Stitches together outputs from left or right child based on threshold.
References Brush::Util::mask_to_indices.
Referenced by Operator< NT, S, Fit, enable_if_t< is_in_v< NT, NodeType::SplitOn, NodeType::SplitBest > > >::predict.