Brush::Eval::Scorer< P >
using Brush::Eval::Scorer< P >::RetType = ArrayXf
typedef float(* Brush::Eval::Scorer< P >::funcPointer) (const VectorXf &, const VectorXf &, VectorXf &, const vector< float > &))(const VectorXf &, const VectorXf &, VectorXf &, const vector< float > &)
using Brush::Eval::Scorer< P >::RetType = ArrayXXf
typedef float(* Brush::Eval::Scorer< P >::funcPointer) (const VectorXf &, const ArrayXXf &, VectorXf &, const vector< float > &))(const VectorXf &, const ArrayXXf &, VectorXf &, const vector< float > &)
using Brush::Eval::Scorer< P >::RetType =
typedef float(* Brush::Eval::Scorer< P >::funcPointer) (const VectorXf &, const VectorXf &, VectorXf &, const vector< float > &))(const VectorXf &, const VectorXf &, VectorXf &, const vector< float > &)
std::map< string, funcPointer > Brush::Eval::Scorer< P >::score_hash
Referenced by score, score, Scorer, Scorer.
string Brush::Eval::Scorer< P >::scorer
Referenced by Scorer, Scorer, set_scorer.
std::map<string, funcPointer> Brush::Eval::Scorer< P >::score_hash
string Brush::Eval::Scorer< P >::scorer
Brush::Eval::Scorer< P >::Scorer(string scorer="log")
References Brush::Eval::average_precision_score, Brush::Eval::bal_zero_one_loss, Brush::Eval::mean_log_loss, score_hash, scorer, set_scorer, Brush::Eval::zero_one_loss.
void Brush::Eval::Scorer< P >::set_scorer(string scorer)
References scorer.
Referenced by Scorer, Scorer.
string Brush::Eval::Scorer< P >::get_scorer()
float Brush::Eval::Scorer< P >::score(const VectorXf &y_true, const VectorXf &y_pred, VectorXf &loss, const vector< float > &w)
References HANDLE_ERROR_THROW, score_hash.
Referenced by score.
float Brush::Eval::Scorer< P >::score(Individual< P > &ind, Dataset &data, VectorXf &loss, const Parameters &params)
References Brush::Parameters::class_weights, Brush::Parameters::n_classes, Brush::Pop::Individual< T >::predict_proba, score, Dataset::y.
Brush::Eval::Scorer< P >::Scorer(string scorer="multi_log")
References Brush::Eval::mean_multi_log_loss, Brush::Eval::multi_zero_one_loss, score_hash, scorer, set_scorer.
void Brush::Eval::Scorer< P >::set_scorer(string scorer)
References scorer.
string Brush::Eval::Scorer< P >::get_scorer()
float Brush::Eval::Scorer< P >::score(const VectorXf &y_true, const ArrayXXf &y_pred, VectorXf &loss, const vector< float > &w)
References HANDLE_ERROR_THROW, score_hash.
float Brush::Eval::Scorer< P >::score(Individual< P > &ind, Dataset &data, VectorXf &loss, const Parameters &params)
References Brush::Parameters::class_weights, Brush::Parameters::n_classes, Brush::Pop::Individual< T >::predict_proba, score, Dataset::y.
Brush::Eval::Scorer< P >::Scorer(string scorer="mse")
void Brush::Eval::Scorer< P >::set_scorer(string scorer)
string Brush::Eval::Scorer< P >::get_scorer()
float Brush::Eval::Scorer< P >::score(const VectorXf &y_true, const VectorXf &y_pred, VectorXf &loss, const vector< float > &w)
float Brush::Eval::Scorer< P >::score(Individual< P > &ind, Dataset &data, VectorXf &loss, const Parameters &params)