Brush::Pop::Individual
Program<T> Brush::Pop::Individual< T >::program
executable data structure
Referenced by Brush::Var::Variation< T >::cross, Brush::Pop::from_json, Brush::Var::Variation< T >::mutate, Brush::Engine< T >::set_population, Brush::Pop::to_json, Brush::Eval::Evaluation< T >::update_fitness, Brush::Var::Variation< T >::vary, Brush::Var::Variation< T >::vary_and_update.
bool Brush::Pop::Individual< T >::is_fitted_
Referenced by Brush::Pop::from_json, Brush::Pop::to_json, Brush::Var::Variation< T >::vary.
unsigned Brush::Pop::Individual< T >::id
tracking id
Referenced by Brush::Pop::from_json, Brush::Engine< T >::predict_archive, Brush::Engine< T >::predict_proba_archive, Brush::Pop::to_json.
vector<unsigned> Brush::Pop::Individual< T >::parent_id
ids of parents
Referenced by Brush::Pop::from_json, Brush::Pop::to_json.
string Brush::Pop::Individual< T >::variation
Referenced by Brush::Pop::from_json, Brush::Pop::to_json, Brush::Var::Variation< T >::vary_and_update.
vector<Node> Brush::Pop::Individual< T >::sampled_nodes
VectorXf Brush::Pop::Individual< T >::error
training error (used in lexicase selectors)
Referenced by Brush::Eval::Evaluation< T >::assign_fit, Brush::Eval::Evaluation< T >::update_fitness.
Fitness Brush::Pop::Individual< T >::fitness
aggregate fitness score
Referenced by Brush::Eval::Evaluation< T >::assign_fit, Brush::Sel::NSGA2< T >::fast_nds, Brush::Pop::from_json, Brush::Pop::Population< T >::hall_of_fame, Brush::Pop::Population< T >::print_models, Brush::Pop::Archive< T >::sameFitComplexity, Brush::Pop::Archive< T >::sameObjectives, Brush::Pop::Archive< T >::sortComplexity, Brush::Pop::Archive< T >::sortLinearComplexity, Brush::Pop::Archive< T >::sortObj1, Brush::Pop::to_json, Brush::Sel::NSGA2< T >::tournament, Brush::Eval::Evaluation< T >::update_fitness, Brush::Var::Variation< T >::vary, Brush::Var::Variation< T >::vary_and_update.
vector<string> Brush::Pop::Individual< T >::objectives
objectives for use with Pareto selection
Referenced by Brush::Pop::from_json, Brush::Pop::to_json.
std::map<std::string, float> Brush::Pop::Individual< T >::weightsMap
set parent ids using id values
Referenced by Brush::Eval::Evaluation< T >::assign_fit, Brush::Engine< PT::Regressor >::log_stats, Brush::Var::Variation< T >::vary_and_update.
Brush::Pop::Individual< T >::Individual()
Brush::Pop::Individual< T >::Individual(Program< T > &prg)
void Brush::Pop::Individual< T >::init(SearchSpace &ss, const Parameters &params)
Referenced by Brush::Var::Variation< T >::vary.
Individual< T > & Brush::Pop::Individual< T >::fit(const Dataset &data)
Referenced by Brush::Pop::Individual< PT::Regressor >::fit.
Individual< T > & Brush::Pop::Individual< T >::fit(const Ref< const ArrayXXf > &X, const Ref< const ArrayXf > &y)
auto Brush::Pop::Individual< T >::predict(const Dataset &data)
Referenced by Brush::Pop::Individual< PT::Regressor >::predict, Brush::Engine< T >::predict_archive, Brush::Eval::Scorer< P >::score.
auto Brush::Pop::Individual< T >::predict(const Ref< const ArrayXXf > &X)
auto Brush::Pop::Individual< T >::predict_proba(const Dataset &d)
Referenced by Brush::Pop::Individual< PT::Regressor >::predict_proba, Brush::Engine< T >::predict_proba_archive, Brush::Eval::Scorer< P >::score.
auto Brush::Pop::Individual< T >::predict_proba(const Ref< const ArrayXXf > &X)
unsigned int Brush::Pop::Individual< T >::get_size() const
Referenced by Brush::Eval::Evaluation< T >::assign_fit.
unsigned int Brush::Pop::Individual< T >::get_depth() const
Referenced by Brush::Eval::Evaluation< T >::assign_fit.
unsigned int Brush::Pop::Individual< T >::get_complexity() const
Referenced by Brush::Eval::Evaluation< T >::assign_fit.
unsigned int Brush::Pop::Individual< T >::get_linear_complexity() const
Referenced by Brush::Eval::Evaluation< T >::assign_fit.
Program< T > & Brush::Pop::Individual< T >::get_program()
string Brush::Pop::Individual< T >::get_model(string fmt="compact", bool pretty=false)
Referenced by Brush::Pop::Population< T >::print_models.
string Brush::Pop::Individual< T >::get_dot_model(string extras="")
void Brush::Pop::Individual< T >::set_fitness(Fitness &f)
Fitness & Brush::Pop::Individual< T >::get_fitness()
void Brush::Pop::Individual< T >::set_variation(string v)
Referenced by Brush::Var::Variation< T >::cross, Brush::Var::Variation< T >::mutate.
string Brush::Pop::Individual< T >::get_variation() const
Referenced by Brush::Var::Variation< T >::vary_and_update.
bool Brush::Pop::Individual< T >::get_is_fitted() const
Referenced by Brush::Eval::Evaluation< T >::update_fitness.
void Brush::Pop::Individual< T >::set_is_fitted(bool fitted)
void Brush::Pop::Individual< T >::set_sampled_nodes(const vector< Node > &nodes)
Referenced by Brush::Var::Variation< T >::mutate.
vector< Node > Brush::Pop::Individual< T >::get_sampled_nodes() const
Referenced by Brush::Var::Variation< T >::vary_and_update.
void Brush::Pop::Individual< T >::set_id(unsigned i)
Referenced by Brush::Var::Variation< T >::vary, Brush::Var::Variation< T >::vary_and_update.
void Brush::Pop::Individual< T >::set_parents(const vector< Individual< T > > &parents)
Referenced by Brush::Var::Variation< T >::vary, Brush::Var::Variation< T >::vary_and_update.
void Brush::Pop::Individual< T >::set_parents(const vector< unsigned > &parents)
set parent ids using parents
vector< string > Brush::Pop::Individual< T >::get_objectives() const
Referenced by Brush::Eval::Evaluation< T >::assign_fit, Brush::Var::Variation< T >::vary, Brush::Var::Variation< T >::vary_and_update.
void Brush::Pop::Individual< T >::set_objectives(vector< string > objs)
Referenced by Brush::Eval::Evaluation< T >::assign_fit, Brush::Var::Variation< T >::vary.