Brush::Sel::NSGA2
Brush::Sel::NSGA2< T >::NSGA2(bool surv=false)
NSGA-II based selection and survival methods.
References Brush::Sel::SelectionOperator< T >::name, Brush::Sel::SelectionOperator< T >::survival.
Brush::Sel::NSGA2< T >::~NSGA2()
vector< size_t > Brush::Sel::NSGA2< T >::select(Population< T > &pop, int island, const Parameters &p)
selection according to the survival scheme of NSGA-II
References Brush::Sel::NSGA2< T >::crowding_distance, Brush::Parameters::current_gen, Brush::Sel::NSGA2< T >::fast_nds, Brush::Pop::Population< T >::get_island_indexes, Brush::Util::r, Brush::Sel::NSGA2< T >::tournament.
vector< size_t > Brush::Sel::NSGA2< T >::survive(Population< T > &pop, int island, const Parameters &p)
survival according to the survival scheme of NSGA-II
References Brush::Sel::NSGA2< T >::crowding_distance, Brush::Sel::NSGA2< T >::fast_nds, Brush::Pop::Population< T >::get_island_indexes, Brush::Parameters::num_islands, Brush::Parameters::pop_size.
vector< vector< int > > Brush::Sel::NSGA2< T >::fast_nds(Population< T > &, vector< size_t > &)
References Brush::Fitness::dominated, Brush::Pop::Individual< T >::fitness, Brush::Pop::Population< T >::individuals.
Referenced by Brush::Sel::NSGA2< T >::select, Brush::Sel::NSGA2< T >::survive.
void Brush::Sel::NSGA2< T >::crowding_distance(Population< T > &, vector< vector< int > > &, int)
References Brush::Pop::Population< T >::individuals.
Referenced by Brush::Sel::NSGA2< T >::select, Brush::Sel::NSGA2< T >::survive.
size_t Brush::Sel::NSGA2< T >::tournament(Population< T > &pop, size_t i, size_t j) const
References Brush::Fitness::crowding_dist, Brush::Fitness::dominates, Brush::Pop::Individual< T >::fitness.
Referenced by Brush::Sel::NSGA2< T >::select.