Brush::Eval::Scorer
using Brush::Eval::Scorer< P >::RetType = typename std::conditional_t<P == PT::Regressor, ArrayXf, std::conditional_t<P == PT::Representer, ArrayXXf, ArrayXf >>
typedef float(* Brush::Eval::Scorer< P >::funcPointer) (const VectorXf &, const VectorXf &, VectorXf &, const vector< float > &))(const VectorXf &, const VectorXf &, VectorXf &, const vector< float > &)
std::map<string, funcPointer> Brush::Eval::Scorer< P >::score_hash
Referenced by Brush::Eval::Scorer< P >::score, Brush::Eval::Scorer< P >::Scorer.
string Brush::Eval::Scorer< P >::scorer
Referenced by Brush::Eval::Scorer< P >::Scorer, Brush::Eval::Scorer< P >::set_scorer.
Brush::Eval::Scorer< P >::Scorer(string scorer="mse")
References Brush::Eval::mse, Brush::Eval::Scorer< P >::score_hash, Brush::Eval::Scorer< P >::scorer, Brush::Eval::Scorer< P >::set_scorer.
void Brush::Eval::Scorer< P >::set_scorer(string scorer)
References Brush::Eval::Scorer< P >::scorer.
Referenced by Brush::Eval::Evaluation< T >::Evaluation, Brush::Eval::Scorer< P >::Scorer, Brush::Eval::Evaluation< T >::set_scorer.
string Brush::Eval::Scorer< P >::get_scorer()
Referenced by Brush::Eval::Evaluation< T >::get_scorer.
float Brush::Eval::Scorer< P >::score(const VectorXf &y_true, const VectorXf &y_pred, VectorXf &loss, const vector< float > &w)
References HANDLE_ERROR_THROW, Brush::Eval::Scorer< P >::score_hash.
Referenced by Brush::Eval::Scorer< P >::score.
float Brush::Eval::Scorer< P >::score(Individual< P > &ind, Dataset &data, VectorXf &loss, const Parameters &params)
References Brush::Parameters::class_weights, Brush::Pop::Individual< T >::predict, Brush::Eval::Scorer< P >::score, Dataset::y.