Brush::Node
using Brush::Node::HashTuple = std::tuple< UnderlyingNodeType, size_t, bool, string, bool, bool, int >
tuple type for hashing
string Brush::Node::name
full name of the node, with types
Referenced by Brush::from_json, get_name, Node, Brush::to_json.
NodeType Brush::Node::node_type
the node type
Referenced by Brush::Var::Variation< T >::bandit_get_node_like, Brush::from_json, get_model, get_name, get_node_hash, Brush::SearchSpace::get_node_like, init, Brush::init_node_with_default_signature, Node, Brush::SearchSpace::PTC2, Brush::Simpl::Constants_simplifier::simplify_tree, Brush::to_json.
DataType Brush::Node::ret_type
return data type
Referenced by Brush::Var::Variation< T >::bandit_get_node_like, Brush::from_json, Brush::SearchSpace::get_node_like, get_ret_type, Node, Brush::SearchSpace::sample_subtree, set_signature, Brush::Simpl::Constants_simplifier::simplify_tree, Brush::to_json.
std::vector<DataType> Brush::Node::arg_types
argument data types
Referenced by Brush::from_json, get_arg_count, get_arg_types, get_model, Node, Brush::SearchSpace::PTC2, set_signature, Brush::to_json.
std::size_t Brush::Node::sig_hash
a hash of the signature
Referenced by args_type, Brush::from_json, get_node_hash, Node, set_signature, Brush::to_json.
std::size_t Brush::Node::sig_dual_hash
a hash of the dual of the signature (for NLS)
Referenced by Brush::from_json, Node, set_signature, Brush::to_json.
bool Brush::Node::node_is_fixed
whether the node is replaceable. Weights are still optimized.
Referenced by Brush::from_json, get_node_hash, get_prob_change, get_prob_keep, init, Brush::SearchSpace::make_program, Brush::to_json.
bool Brush::Node::weight_is_fixed
whether the weight should be kept during variation. Notice that weight_is_fixed alows us to fix the weight of certain nodes.
Referenced by Brush::Var::Variation< T >::cross, Brush::from_json, get_node_hash, init, Brush::SearchSpace::make_program, Brush::Var::InsertMutation::mutate, Brush::Var::SubtreeMutation::mutate, Brush::to_json.
bool Brush::Node::is_weighted
whether this node is weighted (ignored in nodes that must have weights, such as meanLabel, constants, splits)
Referenced by Brush::from_json, get_model, get_name, Node, set_is_weighted, Brush::to_json.
float Brush::Node::prob_change
chance of node being selected for variation. This will take into account if the node is fixed, but not the weight (a fixed weight just gets propagated). Can be affected by node_is_fixed. should not be accessed directly.
Referenced by Brush::from_json, Brush::to_json.
float Brush::Node::W
the weights of the node. also used for splitting thresholds.
Referenced by Brush::Var::Variation< T >::cross, Brush::from_json, get_model, get_name, get_node_hash, init, Brush::Var::InsertMutation::mutate, Brush::Var::SubtreeMutation::mutate, Brush::Simpl::Constants_simplifier::simplify_tree, Brush::to_json.
bool Brush::Node::center_op
whether to center the operator in pretty printing
Referenced by Brush::from_json, Brush::to_json.
string Brush::Node::feature
feature name for terminals or splitting nodes
Referenced by Brush::from_json, get_feature, get_model, get_name, get_node_hash, Brush::init_node_with_default_signature, Node, set_feature.
DataType Brush::Node::feature_type
feature type for terminals or splitting nodes
Referenced by Brush::from_json, get_feature_type, set_feature_type.
bool Brush::Node::keep_split_feature
fix the SplitBest feature when the node is fixed
Referenced by get_keep_split_feature, set_keep_split_feature.
Brush::Node::Node()=default
Referenced by operator!=, operator<, operator<=, operator==, operator>, operator>=.
Brush::Node::Node(NodeType type, S signature, bool weighted=false, string feature_name="") noexcept
Constructor used by search space.
S signature type node type feature_name name of the terminal signature signature
References arg_types, feature, get_arg_types, get_ret_type, init, is_weighted, name, node_type, Brush::NodeTypeName, ret_type, sig_dual_hash, sig_hash.
void Brush::Node::set_signature()
References arg_types, ret_type, sig_dual_hash, sig_hash.
Referenced by Brush::init_node_with_default_signature.
void Brush::Node::init()
References Brush::IsWeighable, node_is_fixed, node_type, Brush::OffsetSum, set_prob_change, W, weight_is_fixed.
Referenced by Brush::from_json, Node.
auto Brush::Node::get_name(bool include_weight=true) const noexcept
gets a string version of the node for printing.
get the name of the node. include_weight whether to include the node's weight in the output. Multiplications by one are omitted. string version of the node. name
References feature, Brush::Is, is_weighted, name, node_type, W.
Referenced by fmt::formatter< Brush::Node >::format, get_model, Brush::operator<<.
string Brush::Node::get_model(const vector< string > &) const noexcept
References arg_types, Brush::ArrayB, feature, get_name, Brush::Is, is_weighted, node_type, W.
DataType Brush::Node::get_ret_type() const
References get_ret_type, ret_type.
Referenced by get_ret_type, Node.
std::size_t Brush::Node::args_type() const
References sig_hash.
Referenced by Brush::Var::Variation< T >::bandit_get_node_like, Brush::SearchSpace::get_node_like.
auto Brush::Node::get_arg_types() const
References arg_types.
Referenced by Node.
size_t Brush::Node::get_arg_count() const
References arg_types.
size_t Brush::Node::get_node_hash(bool include_const=true) const
References feature, get_is_weighted, Brush::NodeTypes::GetIndex, node_is_fixed, node_type, sig_hash, W, weight_is_fixed.
Referenced by operator<, operator==.
bool Brush::Node::operator==(const Node &rhs) const noexcept
References get_node_hash, Node.
bool Brush::Node::operator!=(const Node &rhs) const noexcept
References Node.
bool Brush::Node::operator<(const Node &rhs) const noexcept
References get_node_hash, Node.
bool Brush::Node::operator<=(const Node &rhs) const noexcept
References Node.
bool Brush::Node::operator>(const Node &rhs) const noexcept
References Node.
bool Brush::Node::operator>=(const Node &rhs) const noexcept
References Node.
float Brush::Node::get_prob_change() const
References node_is_fixed.
Referenced by Brush::Simpl::Constants_simplifier::simplify_tree.
void Brush::Node::set_prob_change(float w)
Referenced by Brush::generate_terminals, init, Brush::SearchSpace::make_program.
float Brush::Node::get_prob_keep() const
References node_is_fixed.
void Brush::Node::set_feature(string f)
References feature.
string Brush::Node::get_feature() const
References feature.
Referenced by Brush::to_json.
void Brush::Node::set_feature_type(DataType ft)
References feature_type.
DataType Brush::Node::get_feature_type() const
References feature_type.
Referenced by Brush::init_node_with_default_signature, Brush::to_json.
void Brush::Node::set_keep_split_feature(bool keep)
References keep_split_feature.
bool Brush::Node::get_keep_split_feature() const
References keep_split_feature.
bool Brush::Node::get_is_weighted() const
References Brush::IsWeighable.
Referenced by get_node_hash, Brush::SearchSpace::PTC2.
void Brush::Node::set_is_weighted(bool is_weighted)
References is_weighted, Brush::IsWeighable.
Referenced by Brush::Var::Variation< T >::cross, Brush::SearchSpace::make_program, Brush::Var::InsertMutation::mutate, Brush::Var::SubtreeMutation::mutate.