Brush::Operator< NodeType::MeanLabel, S, Fit >
using Brush::Operator< NodeType::MeanLabel, S, Fit >::RetType = typename S::RetType
using Brush::Operator< NodeType::MeanLabel, S, Fit >::W = typename S::WeightType
using Brush::Operator< NT, S, Fit, void >::ArgTypes =
set argument types to those of the signature unless:
a) the operator is unary and there are more than one arguments b) the operator is binary and associative In the case of a) or b), arguments to the operator are stacked into an array and the operator is applied to that array
using Brush::Operator< NT, S, Fit, void >::RetType =
return type of the operator
using Brush::Operator< NT, S, Fit, void >::NthType =
utility for returning the type of the Nth argument
using Brush::Operator< NT, S, Fit, void >::W =
set weight type
RetType Brush::Operator< NodeType::MeanLabel, S, Fit >::fit(const Dataset &d, TreeNode &tn) const
References Brush::Data::Dataset::classification, predict, Brush::Data::Dataset::y.
Referenced by eval.
RetType Brush::Operator< NodeType::MeanLabel, S, Fit >::predict(const Dataset &d, TreeNode &tn, const W **weights=nullptr) const
References Brush::Data::Dataset::get_n_features, Brush::Data::Dataset::get_n_samples, Brush::util::get_weight.
Referenced by eval, fit.
RetType Brush::Operator< NodeType::MeanLabel, S, Fit >::eval(const Dataset &d, TreeNode &tn, const W **weights=nullptr) const
References fit, predict.
Brush::Operator< NT, S, Fit, void >::Operator()=default
T Brush::Operator< NT, S, Fit, void >::get_kids(const Dataset &d, TreeNode &tn, const W **weights=nullptr) const
get a std::array or eigen array of kids
T Brush::Operator< NT, S, Fit, void >::get_kids(const Dataset &d, TreeNode &tn, const W **weights=nullptr) const
get a std::tuple of kids. Used when child arguments are different types.
T argument types d the dataset tn the tree node weights option pointer to a weight array, used in place of node weight a tuple of the child arguments
NthType< I > Brush::Operator< NT, S, Fit, void >::get_kid(const Dataset &d, TreeNode &tn, const W **weights) const
gets one kid for a tuple of kids
T Brush::Operator< NT, S, Fit, void >::get_kids_seq(const Dataset &d, TreeNode &tn, const W **weights, std::index_sequence< Is... >) const
Makes and returns a tuple of child outputs.
T a tuple Is integer sequence d dataset tn a tree node a tuple with elements corresponding to each child node
RetType Brush::Operator< NT, S, Fit, void >::apply(const T &inputs) const
Apply node function in a functional style.
T argument types inputs the child node outputs return values applying F to the inputs
RetType Brush::Operator< NT, S, Fit, void >::apply(const T &inputs) const
Apply the node function like a function.
T argument types inputs the child node outputs return values applying F to the inputs
RetType Brush::Operator< NT, S, Fit, void >::eval(const Dataset &d, TreeNode &tn, const W **weights=nullptr) const
evaluate the operator on the data. main entry point.
T argument types Scalar the underlying scalar type of the return type d dataset tn tree node weights option pointer to a weight array, used in place of node weight output values from applying operator function
RetType Brush::Operator< NT, S, Fit, void >::eval(const Dataset &d, TreeNode &tn, const W **weights=nullptr) const
size_t Brush::Operator< NT, S, Fit, void >::ArgCount
stores the argument count of the operator
auto Brush::Operator< NT, S, Fit, void >::F
wrapper function for the node function