Brush::MAB::Bandit
using Brush::MAB::Bandit< T >::Iter = tree<Node>::pre_order_iterator
std::shared_ptr<BanditOperator<T> > Brush::MAB::Bandit< T >::pbandit
A shared pointer to the bandit operator (policy).
Referenced by Brush::MAB::Bandit< T >::set_bandit, Brush::MAB::Bandit< T >::update.
std::string Brush::MAB::Bandit< T >::type
The type of the bandit.
Referenced by Brush::MAB::Bandit< T >::Bandit, Brush::MAB::Bandit< T >::Bandit, Brush::MAB::Bandit< T >::get_type, Brush::MAB::Bandit< T >::set_bandit, Brush::MAB::Bandit< T >::set_type.
vector<T> Brush::MAB::Bandit< T >::arms
The arms of the bandit.
Referenced by Brush::MAB::Bandit< T >::Bandit, Brush::MAB::Bandit< T >::set_arms.
std::map<T, float> Brush::MAB::Bandit< T >::probabilities
The probabilities associated with each arm.
Referenced by Brush::MAB::Bandit< T >::set_bandit.
Brush::MAB::Bandit< T >::Bandit()
References Brush::MAB::Bandit< T >::set_arms, Brush::MAB::Bandit< T >::set_bandit, Brush::MAB::Bandit< T >::set_probs, Brush::MAB::Bandit< T >::set_type.
Brush::MAB::Bandit< T >::~Bandit()
Brush::MAB::Bandit< T >::Bandit(string type, vector< T > arms)
Constructor for the Bandit struct.
type The type of the bandit. arms The arms of the bandit.
References Brush::MAB::Bandit< T >::arms, Brush::MAB::Bandit< T >::set_arms, Brush::MAB::Bandit< T >::set_bandit, Brush::MAB::Bandit< T >::set_probs, Brush::MAB::Bandit< T >::type.
Brush::MAB::Bandit< T >::Bandit(string type, map< T, float > arms_probs)
Constructor for the Bandit struct.
type The type of the bandit. arms_probs The arms and their associated probabilities.
References Brush::MAB::Bandit< T >::set_arms, Brush::MAB::Bandit< T >::set_bandit, Brush::MAB::Bandit< T >::set_probs, Brush::MAB::Bandit< T >::type.
void Brush::MAB::Bandit< T >::set_bandit()
Sets the bandit operator (policy).
References Brush::MAB::Bandit< T >::pbandit, Brush::MAB::Bandit< T >::probabilities, Brush::MAB::Bandit< T >::type.
Referenced by Brush::MAB::Bandit< T >::Bandit, Brush::MAB::Bandit< T >::Bandit, Brush::MAB::Bandit< T >::Bandit.
void Brush::MAB::Bandit< T >::set_arms(vector< T > arms)
Sets the arms of the bandit.
References Brush::MAB::Bandit< T >::arms.
Referenced by Brush::MAB::Bandit< T >::Bandit, Brush::MAB::Bandit< T >::Bandit, Brush::MAB::Bandit< T >::Bandit.
vector< T > Brush::MAB::Bandit< T >::get_arms()
Gets the arms of the bandit.
string Brush::MAB::Bandit< T >::get_type()
Gets the type of the bandit.
References Brush::MAB::Bandit< T >::type.
void Brush::MAB::Bandit< T >::set_type(string type)
Sets the type of the bandit.
References Brush::MAB::Bandit< T >::type.
Referenced by Brush::MAB::Bandit< T >::Bandit.
map< T, float > Brush::MAB::Bandit< T >::get_probs()
Gets the probabilities associated with each arm.
void Brush::MAB::Bandit< T >::set_probs(map< T, float > arms_probs)
Sets the probabilities associated with each arm.
arms_probs The arms and their associated probabilities.
Referenced by Brush::MAB::Bandit< T >::Bandit, Brush::MAB::Bandit< T >::Bandit, Brush::MAB::Bandit< T >::Bandit.
map< T, float > Brush::MAB::Bandit< T >::sample_probs(bool update=false)
Samples the probabilities associated with each arm using the policy.
update Flag indicating whether to update the bandit's state, or just return the current probabilities. The sampled probabilities associated with each arm.
References Brush::MAB::Bandit< T >::update.
T Brush::MAB::Bandit< T >::choose(const VectorXf &context)
Selects an arm using the tree and fitness as context.
T The type of the arms the bandit has. tree The tree structure containing nodes of type T. f The fitness function used to evaluate and select nodes. T The selected arm from the tree.
void Brush::MAB::Bandit< T >::update(T arm, float reward, VectorXf &context={})
Updates the bandit's state based on the chosen arm and the received reward.
arm The chosen arm. reward The received reward.
References Brush::MAB::Bandit< T >::pbandit.
Referenced by Brush::MAB::Bandit< T >::sample_probs.
VectorXf Brush::MAB::Bandit< T >::get_context(const Program< PT > &program, Iter spot, const SearchSpace &ss, const Dataset &d)