Brush::ResidualEvaluator
typedef float Brush::ResidualEvaluator< PT >::Scalar
std::reference_wrapper<PT> Brush::ResidualEvaluator< PT >::program_
Referenced by Brush::ResidualEvaluator< PT >::GetProgram, Brush::ResidualEvaluator< PT >::ResidualEvaluator.
std::reference_wrapper<Dataset const> Brush::ResidualEvaluator< PT >::dataset_
Referenced by Brush::ResidualEvaluator< PT >::GetDataset, Brush::ResidualEvaluator< PT >::ResidualEvaluator.
std::reference_wrapper<ArrayXf const> Brush::ResidualEvaluator< PT >::y_true_
Referenced by Brush::ResidualEvaluator< PT >::GetTarget, Brush::ResidualEvaluator< PT >::NumResiduals, Brush::ResidualEvaluator< PT >::ResidualEvaluator.
size_t Brush::ResidualEvaluator< PT >::numParameters_
Referenced by Brush::ResidualEvaluator< PT >::NumParameters, Brush::ResidualEvaluator< PT >::ResidualEvaluator.
Brush::ResidualEvaluator< PT >::ResidualEvaluator(PT &program, Dataset const &dataset)
References Brush::ResidualEvaluator< PT >::dataset_, Brush::ResidualEvaluator< PT >::numParameters_, Brush::ResidualEvaluator< PT >::program_, Brush::ResidualEvaluator< PT >::y_true_.
void Brush::ResidualEvaluator< PT >::operator()(Eigen::DenseBase< T > &parameters, Eigen::DenseBase< T > &residuals) const noexcept
bool Brush::ResidualEvaluator< PT >::operator()(T const *parameters, T *residuals) const
References Brush::ResidualEvaluator< PT >::GetDataset, Brush::ResidualEvaluator< PT >::GetProgram, Brush::ResidualEvaluator< PT >::GetTarget.
size_t Brush::ResidualEvaluator< PT >::NumParameters() const
References Brush::ResidualEvaluator< PT >::numParameters_.
size_t Brush::ResidualEvaluator< PT >::NumResiduals() const
References Brush::ResidualEvaluator< PT >::y_true_.
auto Brush::ResidualEvaluator< PT >::GetProgram() const
References Brush::ResidualEvaluator< PT >::program_.
Referenced by Brush::ResidualEvaluator< PT >::operator().
auto Brush::ResidualEvaluator< PT >::GetDataset() const
References Brush::ResidualEvaluator< PT >::dataset_.
Referenced by Brush::ResidualEvaluator< PT >::operator().
auto Brush::ResidualEvaluator< PT >::GetTarget() const
References Brush::ResidualEvaluator< PT >::y_true_.
Referenced by Brush::ResidualEvaluator< PT >::operator().