name: install, test, docs
on: [push, pull_request]

env: 
  CACHE_NUMBER: 0

defaults:
  run:
    shell: bash -l {0}

jobs:
########################################
# tests
########################################
  tests:
    runs-on: ubuntu-latest
    steps:
      - 
        name: Checkout code
        uses: actions/checkout@v3
      - 
        name: Mamba Environment
        uses: mamba-org/provision-with-micromamba@main
        with:
          environment-file: environment.yml
          cache-env: true
          cache-downloads: true
      - 
        name: Install
        run: | 
          micromamba env list
          export CMAKE_BUILD_PARALLEL_LEVEL=4
          pip install .
      - 
        name: Test Import
        run: |
          cd ..
          which python
          # micromamba info
          python -c "import brush"
      - 
        name: Wrapper Test 
        run: |
          pytest
########################################
# docs
########################################
  docs:
    runs-on: ubuntu-latest
    steps:
      - 
        name: Checkout code
        uses: actions/checkout@v3
      - 
        name: Mamba Environment
        uses: mamba-org/provision-with-micromamba@main
        with:
          environment-file: environment.yml
          cache-env: true
          cache-downloads: true
      - 
        name: Install
        run: | 
          micromamba env list
          export CMAKE_BUILD_PARALLEL_LEVEL=4
          pip install .
      -
        name: build docs
        run: |
          cd docs
          sudo apt-get install doxygen graphviz

          micromamba info
          # micromamba install pandoc
          pip install -r requirements.txt
          make html
      - 
        name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        if: ${{ github.ref == 'refs/heads/master' }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: docs/_build/html