Brush::Parameters
int Brush::Parameters::random_state
Referenced by get_random_state, set_random_state.
int Brush::Parameters::verbosity
Referenced by get_verbosity, set_verbosity.
string Brush::Parameters::mode
unsigned int Brush::Parameters::current_gen
Referenced by get_current_gen, Brush::Sel::Lexicase< T >::select, Brush::Sel::NSGA2< T >::select, set_current_gen.
int Brush::Parameters::pop_size
Referenced by bind_variation, get_pop_size, Brush::Pop::Population< T >::init, Brush::Pop::Population< T >::init, set_pop_size, Brush::Sel::NSGA2< T >::survive.
int Brush::Parameters::max_gens
Referenced by get_max_gens, set_max_gens.
int Brush::Parameters::max_stall
Referenced by get_max_stall, set_max_stall.
int Brush::Parameters::max_time
Referenced by get_max_time, set_max_time.
unsigned int Brush::Parameters::max_depth
Referenced by get_max_depth, Brush::SearchSpace::make_program, Brush::Var::SubtreeMutation::mutate, set_max_depth.
unsigned int Brush::Parameters::max_size
Referenced by Brush::Var::SubtreeMutation::find_spots, Brush::Var::ToggleWeightOnMutation::find_spots, get_max_size, Brush::SearchSpace::make_program, Brush::Var::InsertMutation::mutate, Brush::Var::SubtreeMutation::mutate, set_max_size.
vector<string> Brush::Parameters::objectives
Referenced by get_objectives, Brush::Pop::Population< T >::init, Brush::Pop::Population< T >::init, set_objectives.
string Brush::Parameters::bandit
Referenced by get_bandit, set_bandit.
string Brush::Parameters::sel
Referenced by get_sel, set_sel.
string Brush::Parameters::surv
Referenced by get_surv, set_surv.
std::unordered_map<string, float> Brush::Parameters::functions
Referenced by get_functions, set_functions.
int Brush::Parameters::num_islands
Referenced by bind_selection, bind_variation, get_num_islands, Brush::Pop::Population< T >::init, Brush::Pop::Population< T >::init, set_num_islands, Brush::Sel::NSGA2< T >::survive.
bool Brush::Parameters::use_arch
Referenced by get_use_arch, set_use_arch.
bool Brush::Parameters::val_from_arch
Referenced by get_val_from_arch, set_val_from_arch.
bool Brush::Parameters::constants_simplification
Referenced by get_constants_simplification, set_constants_simplification.
bool Brush::Parameters::inexact_simplification
Referenced by get_inexact_simplification, set_inexact_simplification.
std::map<std::string, float> Brush::Parameters::mutation_probs
Referenced by get_mutation_probs, set_mutation_probs.
float Brush::Parameters::cx_prob
cross rate for variation
Referenced by get_cx_prob, set_cx_prob.
float Brush::Parameters::mig_prob
Referenced by get_mig_prob, Brush::Pop::Population< T >::init, Brush::Pop::Population< T >::init, set_mig_prob.
string Brush::Parameters::scorer
actual loss function used, determined by error
Referenced by Brush::Eval::Evaluation< T >::assign_fit, get_objectives, get_scorer, Brush::Sel::Lexicase< T >::select, set_scorer.
vector<int> Brush::Parameters::classes
class labels
vector<float> Brush::Parameters::class_weights
weights for each class
Referenced by get_class_weights, Brush::Eval::Scorer< P >::score, Brush::Sel::Lexicase< T >::select, set_class_weights, set_sample_weights.
vector<float> Brush::Parameters::sample_weights
weights for each sample
Referenced by get_sample_weights, Brush::Sel::Lexicase< T >::select, set_sample_weights.
bool Brush::Parameters::classification
Referenced by get_classification, Brush::Sel::Lexicase< T >::select, set_classification, set_n_classes.
unsigned int Brush::Parameters::n_classes
Referenced by get_n_classes, Brush::Eval::Scorer< P >::score, set_class_weights, set_n_classes.
bool Brush::Parameters::shuffle_split
Referenced by get_shuffle_split, set_shuffle_split.
float Brush::Parameters::validation_size
Referenced by get_validation_size, set_validation_size.
vector<string> Brush::Parameters::feature_names
Referenced by get_feature_names, set_feature_names.
vector<string> Brush::Parameters::feature_types
Referenced by get_feature_types, set_feature_types.
float Brush::Parameters::batch_size
Referenced by get_batch_size, set_batch_size.
bool Brush::Parameters::weights_init
Referenced by get_weights_init, set_weights_init.
string Brush::Parameters::load_population
Referenced by get_load_population, set_load_population.
string Brush::Parameters::save_population
Referenced by get_save_population, set_save_population.
string Brush::Parameters::logfile
Referenced by get_logfile, set_logfile.
int Brush::Parameters::n_jobs
number of parallel jobs -1 use all threads; 0 use same as number of islands; positive number specify the amouut of threads
Referenced by get_n_jobs, set_n_jobs.
Brush::Parameters::Parameters()
Brush::Parameters::~Parameters()
void Brush::Parameters::set_verbosity(int new_verbosity)
References Brush::Util::logger, verbosity.
Referenced by bind_params.
int Brush::Parameters::get_verbosity()
References verbosity.
Referenced by bind_params.
void Brush::Parameters::set_random_state(int new_random_state)
References random_state.
Referenced by bind_params.
int Brush::Parameters::get_random_state()
References random_state.
Referenced by bind_params.
void Brush::Parameters::set_pop_size(int new_pop_size)
References pop_size.
Referenced by bind_params.
int Brush::Parameters::get_pop_size()
References pop_size.
Referenced by bind_params.
void Brush::Parameters::set_max_gens(int new_max_gens)
References max_gens.
Referenced by bind_params.
int Brush::Parameters::get_max_gens()
References max_gens.
Referenced by bind_params.
void Brush::Parameters::set_bandit(string new_bandit)
References bandit.
Referenced by bind_params.
string Brush::Parameters::get_bandit()
References bandit.
Referenced by bind_params.
void Brush::Parameters::set_max_stall(int new_max_stall)
References max_stall.
Referenced by bind_params.
int Brush::Parameters::get_max_stall()
References max_stall.
Referenced by bind_params.
void Brush::Parameters::set_max_time(int new_max_time)
References max_time.
Referenced by bind_params.
int Brush::Parameters::get_max_time()
References max_time.
Referenced by bind_params.
void Brush::Parameters::set_scorer(string new_scorer)
References scorer.
Referenced by bind_params.
string Brush::Parameters::get_scorer()
References scorer.
Referenced by bind_params.
void Brush::Parameters::set_load_population(string new_load_population)
References load_population.
Referenced by bind_params.
string Brush::Parameters::get_load_population()
References load_population.
Referenced by bind_params.
void Brush::Parameters::set_save_population(string new_save_population)
References save_population.
Referenced by bind_params.
string Brush::Parameters::get_save_population()
References save_population.
Referenced by bind_params.
string Brush::Parameters::get_logfile()
References logfile.
Referenced by bind_params.
void Brush::Parameters::set_logfile(string s)
References logfile.
Referenced by bind_params.
void Brush::Parameters::set_current_gen(unsigned int gen)
References current_gen.
Referenced by bind_params.
unsigned int Brush::Parameters::get_current_gen()
References current_gen.
Referenced by bind_params.
void Brush::Parameters::set_num_islands(int new_num_islands)
References num_islands.
Referenced by bind_params.
int Brush::Parameters::get_num_islands()
References num_islands.
Referenced by bind_params.
void Brush::Parameters::set_max_depth(unsigned new_max_depth)
References max_depth.
Referenced by bind_params.
unsigned Brush::Parameters::get_max_depth() const
References max_depth.
Referenced by bind_params.
void Brush::Parameters::set_n_jobs(int new_n_jobs)
References n_jobs.
Referenced by bind_params.
int Brush::Parameters::get_n_jobs()
References n_jobs.
Referenced by bind_params.
void Brush::Parameters::set_max_size(unsigned new_max_size)
References max_size.
Referenced by bind_params.
unsigned Brush::Parameters::get_max_size() const
References max_size.
Referenced by bind_params, Brush::Var::InsertMutation::find_spots, Brush::Var::SplitMutation::find_spots.
void Brush::Parameters::set_objectives(vector< string > new_objectives)
References objectives.
Referenced by bind_params.
vector< string > Brush::Parameters::get_objectives() const
References objectives, scorer.
Referenced by Brush::Eval::Evaluation< T >::assign_fit, bind_params, Brush::Pop::Individual< PT::Regressor >::init.
void Brush::Parameters::set_sel(string new_sel)
References sel.
Referenced by bind_params.
string Brush::Parameters::get_sel()
References sel.
Referenced by bind_params.
void Brush::Parameters::set_surv(string new_surv)
References surv.
Referenced by bind_params.
string Brush::Parameters::get_surv()
References surv.
Referenced by bind_params.
void Brush::Parameters::set_cx_prob(float new_cx_prob)
References cx_prob.
Referenced by bind_params.
float Brush::Parameters::get_cx_prob()
References cx_prob.
Referenced by bind_params.
void Brush::Parameters::set_mig_prob(float new_mig_prob)
References mig_prob.
Referenced by bind_params.
float Brush::Parameters::get_mig_prob()
References mig_prob.
Referenced by bind_params.
void Brush::Parameters::set_use_arch(bool new_use_arch)
References use_arch.
Referenced by bind_params.
bool Brush::Parameters::get_use_arch()
References use_arch.
Referenced by bind_params.
void Brush::Parameters::set_val_from_arch(bool new_val_from_arch)
References val_from_arch.
Referenced by bind_params.
bool Brush::Parameters::get_val_from_arch()
References val_from_arch.
Referenced by bind_params.
void Brush::Parameters::set_classification(bool c)
References classification.
Referenced by bind_params.
bool Brush::Parameters::get_classification()
References classification.
Referenced by bind_params.
void Brush::Parameters::set_shuffle_split(bool shuff)
References shuffle_split.
Referenced by bind_params.
bool Brush::Parameters::get_shuffle_split()
References shuffle_split.
Referenced by bind_params.
void Brush::Parameters::set_constants_simplification(bool cs)
References constants_simplification.
Referenced by bind_params.
bool Brush::Parameters::get_constants_simplification()
References constants_simplification.
Referenced by bind_params.
void Brush::Parameters::set_inexact_simplification(bool is)
References inexact_simplification.
Referenced by bind_params.
bool Brush::Parameters::get_inexact_simplification()
References inexact_simplification.
Referenced by bind_params.
void Brush::Parameters::set_weights_init(bool init)
References weights_init.
Referenced by bind_params.
bool Brush::Parameters::get_weights_init()
References weights_init.
Referenced by bind_params.
void Brush::Parameters::set_n_classes(const ArrayXf &y)
References classification, HANDLE_ERROR_THROW, n_classes, Brush::Util::unique.
Referenced by bind_params.
void Brush::Parameters::set_class_weights(const ArrayXf &y)
References class_weights, n_classes.
Referenced by bind_params.
void Brush::Parameters::set_sample_weights(const ArrayXf &y)
References class_weights, sample_weights.
Referenced by bind_params.
unsigned int Brush::Parameters::get_n_classes()
References n_classes.
Referenced by bind_params.
vector< float > Brush::Parameters::get_class_weights()
References class_weights.
Referenced by bind_params.
vector< float > Brush::Parameters::get_sample_weights()
References sample_weights.
Referenced by bind_params.
void Brush::Parameters::set_validation_size(float s)
References validation_size.
Referenced by bind_params.
float Brush::Parameters::get_validation_size()
References validation_size.
Referenced by bind_params.
void Brush::Parameters::set_feature_names(vector< string > vn)
References feature_names.
Referenced by bind_params.
vector< string > Brush::Parameters::get_feature_names()
References feature_names.
Referenced by bind_params.
void Brush::Parameters::set_feature_types(vector< string > ft)
References feature_types.
vector< string > Brush::Parameters::get_feature_types()
References feature_types.
void Brush::Parameters::set_batch_size(float c)
References batch_size.
Referenced by bind_params.
float Brush::Parameters::get_batch_size()
References batch_size.
Referenced by bind_params.
void Brush::Parameters::set_mutation_probs(std::map< std::string, float > new_mutation_probs)
References mutation_probs.
Referenced by bind_params.
std::map< std::string, float > Brush::Parameters::get_mutation_probs()
References mutation_probs.
Referenced by bind_params.
void Brush::Parameters::set_functions(std::unordered_map< std::string, float > new_functions)
References functions.
Referenced by bind_params.
std::unordered_map< std::string, float > Brush::Parameters::get_functions()
References functions.
Referenced by bind_params.