bind_engines.h
using Reg = Brush::RegressorEngine
using Cls = Brush::ClassifierEngine
using Rep = Brush::RepresenterEngine
using MCls = Brush::MulticlassClassifierEngine
using stream_redirect = py::call_guard<py::scoped_ostream_redirect, py::scoped_estream_redirect>
void bind_engine(py::module &m, string name)
References bind_engine.
Referenced by Brush::Data::TimeSeries< T >::abs, Brush::Data::TimeSeries< T >::acos, Brush::Pop::Population< T >::add_offspring_indexes, Brush::SearchSpace::AddNode, Brush::SearchSpace::AddNodes, Brush::DispatchTable< Fit >::AddOperator, Brush::Util::apply, Brush::Util::argmiddle, Brush::Util::argsort, Brush::Data::TimeSeries< T >::asin, Brush::Eval::Evaluation< T >::assign_fit, Brush::Data::TimeSeries< T >::atan, Brush::detail::Autodiff, Brush::Eval::average_precision_score, Split::best_threshold, bind_engine, bind_engines, bind_evaluator, bind_evaluators, bind_fitness, bind_individual, bind_individuals, bind_params, bind_program, bind_programs, bind_search_space, bind_selection, bind_selections, bind_variation, bind_variations, Brush::calc_initial_weight, Brush::Engine< T >::calculate_stats, Brush::Data::TimeSeries< T >::cast, Brush::Data::cast_type, Brush::Data::TimeSeries< T >::ceil, Brush::SearchSpace::check, Brush::SearchSpace::check, Brush::SearchSpace::check, Brush::Data::check_type, Brush::Util::clean, Brush::Data::TimeSeries< T >::cols, Brush::Program< PType >::complexity, Brush::Util::condition_number, Brush::SigBase< R, Args >::contains, Brush::Program< PType >::copy, Brush::Data::Dataset::copy_and_make_features, Brush::Util::corrcoef, Brush::Data::TimeSeries< T >::cos, Brush::Data::TimeSeries< T >::cosh, Brush::Data::TimeSeries< T >::count, Brush::Util::covariance, Brush::SearchSpace::CreateNode, Brush::Var::Variation< T >::cross, Brush::Sel::NSGA2< T >::crowding_distance, Brush::Data::Dataset::Dataset, Brush::Program< PType >::depth_at, Brush::Program< PType >::depth_to_reach, Brush::Util::Logger::destroy, Brush::Util::Rnd::destroy, Brush::TinyCostFunction< CostFunctor, DualType, ScalarType, StorageOrder >::df, Brush::DispatchOp, Brush::DispatchOp, Brush::Fitness::dominates, Brush::Operator< NodeType::Terminal, S, Fit >::eval, Brush::Operator< NT, S, Fit, E >::eval, Brush::Operator< NodeType::Constant, S, Fit >::eval, Brush::Operator< NodeType::MeanLabel, S, Fit >::eval, Operator< NT, S, Fit, enable_if_t< is_in_v< NT, NodeType::SplitOn, NodeType::SplitBest > > >::eval, Brush::TinyCostFunction< CostFunctor, DualType, ScalarType, StorageOrder >::Evaluate, Brush::Data::TimeSeries< T >::exp, Brush::Sel::NSGA2< T >::fast_nds, Brush::Var::InsertMutation::find_spots, Brush::Var::ToggleWeightOnMutation::find_spots, Brush::Var::ToggleWeightOffMutation::find_spots, Brush::Var::SubtreeMutation::find_spots, Brush::Var::MutationBase::find_spots, Brush::Program< PType >::fit, Brush::Operator< NodeType::MeanLabel, S, Fit >::fit, Operator< NT, S, Fit, enable_if_t< is_in_v< NT, NodeType::SplitOn, NodeType::SplitBest > > >::fit, Brush::Engine< T >::fit, Brush::Pop::Individual< T >::fit, Brush::Program< PType >::fit, Brush::Util::Normalizer::fit, Brush::Util::Normalizer::fit_normalize, Brush::Data::TimeSeries< T >::floor, fmt::formatter< Brush::Data::TimeSeriesb >::format, fmt::formatter< Brush::Data::TimeSeriesf >::format, fmt::formatter< Brush::Data::TimeSeriesi >::format, fmt::formatter< Brush::DataType >::format, fmt::formatter< Brush::Node >::format, fmt::formatter< Brush::NodeType >::format, fmt::formatter< Brush::SearchSpace >::format, Brush::from_json, Brush::Pop::from_json, Brush::from_json, Brush::from_json, nlohmann::adl_serializer< std::shared_ptr< T > >::from_json, from_json, Brush::Split::gain, Brush::Util::Rnd::gasdev, Brush::generate_terminals, Brush::SearchSpace::GenerateNodeMap, Brush::Operator< NodeType::Terminal, S, Fit >::get, Brush::DispatchTable< Fit >::Get, Brush::SearchSpace::get, Brush::SearchSpace::get, Brush::Engine< T >::get_archive, Brush::SigBase< R, Args >::get_arg_types, Brush::Data::Dataset::get_batch, Split::get_best_threshold_by_type, Split::get_best_thresholds, Brush::Split::get_best_variable_and_threshold, Brush::Pop::Individual< T >::get_dot_model, Brush::Program< PType >::get_dot_model, Brush::Util::get_dtypes, Brush::Pop::Population< T >::get_island_indexes, Brush::Operator< NT, S, Fit, E >::get_kid, Operator< NT, S, Fit, enable_if_t< is_in_v< NT, NodeType::SplitOn, NodeType::SplitBest > > >::get_kids, Brush::Operator< NT, S, Fit, E >::get_kids, Brush::Operator< NT, S, Fit, E >::get_kids_seq, Brush::Node::get_model, Brush::Pop::Individual< T >::get_model, Brush::Program< PType >::get_model, Brush::Data::Dataset::get_n_samples, Brush::Program< PType >::get_n_weights, Brush::Node::get_name, Brush::Node::get_node_hash, Brush::SearchSpace::get_node_like, Brush::util::get_weight, Brush::Program< PType >::get_weights, Brush::SearchSpace::get_weights, Brush::SearchSpace::get_weights, Brush::SearchSpace::get_weights, Brush::Split::gini_impurity_index, Brush::Pop::Population< T >::hall_of_fame, Brush::Util::HandleErrorNoThrow, Brush::Util::HandleErrorThrow, Brush::SearchSpace::has_solution_space, Brush::SigBase< R, Args >::hash, Brush::SigBase< R >::hash, Brush::Fitness::hash, Brush::SigBase< R, Args >::hash_args, Brush::Util::in, Brush::Pop::Individual< T >::Individual, Brush::Data::Dataset::init, Brush::Engine< T >::init, Brush::SearchSpace::init, Brush::Pop::Archive< T >::init, Brush::Pop::Population< T >::init, Brush::Pop::Population< T >::init, Brush::init_node_with_default_signature, Brush::DispatchTable< Fit >::InitMap, Brush::Is, Brush::IsCommutative, Brush::IsDifferentiable, Brush::IsLeaf, Brush::Isnt, Brush::Isnt, Brush::IsWeighable, Brush::IsWeighable, Brush::Util::kurtosis, Brush::Util::limited, Brush::Program< PType >::linearize, Brush::Pop::Population< T >::load, Brush::Data::TimeSeries< T >::log, Brush::Util::Logger::log, Brush::Data::TimeSeries< T >::log1p, Brush::Eval::log_loss, Brush::Engine< T >::log_stats, Brush::Data::TimeSeries< T >::logabs, Brush::Util::ltrim, Brush::Util::mad, Brush::SearchSpace::make_classifier, Brush::Data::Dataset::make_features, Brush::SearchSpace::make_multiclass_classifier, Brush::SearchSpace::make_program, Brush::SearchSpace::make_regressor, Brush::SearchSpace::make_representer, Brush::NarySignature< R, Arg, ArgCount, Indices >::make_signature, Brush::NarySignatures< R, Arg, MaxArgCount >::make_signatures, Brush::DispatchTable< Fit >::MakeCallable, Brush::SearchSpace::MakeNodes, Brush::DispatchTable< Fit >::MakeOperators, Brush::Util::mask_to_index, Brush::Util::mask_to_indices, Brush::Data::TimeSeries< T >::max, Brush::Data::TimeSeries< T >::mean, Brush::Util::mean_square_corrcoef, Brush::Data::TimeSeries< T >::median, Brush::Function< NodeType::Median >::median, Brush::Util::median, Brush::Function< NodeType::Median >::median, Brush::Pop::Population< T >::migrate, Brush::Data::TimeSeries< T >::min, Brush::Eval::mse, Brush::Var::Variation< T >::mutate, Brush::Var::PointMutation::mutate, Brush::Var::InsertMutation::mutate, Brush::Var::DeleteMutation::mutate, Brush::Var::ToggleWeightOnMutation::mutate, Brush::Var::ToggleWeightOffMutation::mutate, Brush::Var::SubtreeMutation::mutate, Brush::Util::Normalizer::normalize, Brush::Data::OmopData::OmopData, Brush::Fitness::operator!=, Brush::Node::operator!=, Brush::operator&, Brush::operator&=, Brush::Function< NodeType::Sum >::operator(), Brush::Function< NodeType::Count >::operator(), Brush::Function< NodeType::Not >::operator(), Brush::Function< NodeType::And >::operator(), Brush::Function< NodeType::Or >::operator(), Brush::Function< NodeType::Median >::operator(), std::hash< std::vector< float > >::operator(), Brush::Function< NodeType::Min >::operator(), Brush::Function< NodeType::Max >::operator(), Brush::Function< NodeType::Mean >::operator(), Brush::Function< NodeType::Prod >::operator(), Brush::Function< NodeType::Sum >::operator(), Brush::Function< NodeType::OffsetSum >::operator(), Brush::Function< NodeType::ArgMax >::operator(), Brush::Function< NodeType::Abs >::operator(), Brush::Function< NodeType::Logistic >::operator(), Brush::Function< NodeType::Log >::operator(), Brush::Function< NodeType::Logabs >::operator(), Brush::Function< NodeType::Log1p >::operator(), Brush::Function< NodeType::Ceil >::operator(), Brush::Function< NodeType::Floor >::operator(), Brush::Function< NodeType::Exp >::operator(), Brush::Function< NodeType::Sin >::operator(), Brush::Function< NodeType::Cos >::operator(), Brush::Function< NodeType::Tan >::operator(), Brush::Function< NodeType::Asin >::operator(), Brush::Function< NodeType::Acos >::operator(), Brush::Function< NodeType::Atan >::operator(), Brush::Function< NodeType::Sinh >::operator(), Brush::Function< NodeType::Cosh >::operator(), Brush::Function< NodeType::Tanh >::operator(), Brush::Function< NodeType::Sqrt >::operator(), Brush::Function< NodeType::Sqrtabs >::operator(), Brush::Function< NodeType::Square >::operator(), Brush::Function< NodeType::Add >::operator(), Brush::Function< NodeType::Sub >::operator(), Brush::Function< NodeType::Mul >::operator(), Brush::Function< NodeType::Div >::operator(), Brush::Function< NodeType::Pow >::operator(), Brush::Function< NodeType::Before >::operator(), Brush::Function< NodeType::After >::operator(), Brush::Function< NodeType::During >::operator(), Brush::Function< NodeType::SplitOn >::operator(), Brush::Function< NodeType::Min >::operator(), Brush::Function< NodeType::Max >::operator(), Brush::Function< N >::operator(), Brush::Function< NodeType::Min >::operator(), Brush::Function< NodeType::Max >::operator(), Brush::Function< NodeType::Mean >::operator(), Brush::Function< NodeType::Median >::operator(), Brush::Function< NodeType::Prod >::operator(), Brush::Function< NodeType::Sum >::operator(), Brush::Function< NodeType::Count >::operator(), Brush::Data::TimeSeries< T >::operator(), Brush::Data::Dataset::operator(), Brush::ResidualEvaluator< PT >::operator(), Brush::TinyCostFunction< CostFunctor, DualType, ScalarType, StorageOrder >::operator(), Brush::Sel::NSGA2< T >::sort_n::operator(), Brush::Sel::NSGA2< T >::comparator_obj::operator(), Brush::TinyCostFunction< CostFunctor, DualType, ScalarType, StorageOrder >::operator(), Brush::Pop::Population< T >::SortComplexity::operator(), Brush::Pop::Population< T >::SameFitComplexity::operator(), std::hash< std::tuple< TT... > >::operator(), Brush::uint32_vector_hasher::operator(), Brush::uint32_vector_hasher::operator(), Brush::ResidualEvaluator< PT >::operator(), Brush::Util::Rnd::operator(), Brush::Data::TimeSeries< T >::operator*, Brush::Fitness::operator<, Brush::Node::operator<, Brush::operator<<, Brush::operator<<, Brush::Util::operator<<, Brush::Data::operator<<, Brush::operator<<, Brush::operator<<, Brush::operator<<, Brush::Fitness::operator<=, Brush::Node::operator<=, Brush::DispatchTable< Fit >::operator=, Brush::DispatchTable< Fit >::operator=, Brush::Fitness::operator==, Brush::Node::operator==, Brush::Fitness::operator>, Brush::Node::operator>, Brush::Fitness::operator>=, Brush::Node::operator>=, Brush::Pop::Population< T >::operator[], Brush::Pop::Population< T >::operator[], Brush::operator^, Brush::operator^=, Brush::operator|, Brush::operator|=, Brush::operator~, Brush::Util::pearson_correlation, Brush::Data::TimeSeries< T >::pow, Brush::Program< PType >::predict, Brush::Operator< NodeType::MeanLabel, S, Fit >::predict, Operator< NT, S, Fit, enable_if_t< is_in_v< NT, NodeType::SplitOn, NodeType::SplitBest > > >::predict, Brush::Engine< T >::predict, Brush::Pop::Individual< T >::predict, Brush::Program< PType >::predict, Brush::Engine< T >::predict_archive, Brush::Engine< T >::predict_archive, Brush::Pop::Individual< T >::predict_proba, Brush::Program< PType >::predict_proba, Brush::Engine< T >::predict_proba, Brush::Pop::Individual< T >::predict_proba, Brush::Program< PType >::predict_proba, Brush::Engine< T >::predict_proba_archive, Brush::Engine< T >::predict_proba_archive, Brush::Program< PType >::predict_with_weights, Brush::Program< PType >::predict_with_weights, Brush::DispatchTable< Fit >::print, Brush::Data::Dataset::print, Brush::Data::TimeSeries< T >::print, Brush::Util::print, Brush::Pop::Population< T >::print_models, Brush::Engine< T >::print_progress, Brush::Engine< T >::print_stats, Brush::Data::TimeSeries< T >::prod, Brush::Program< PType >::Program, Brush::SearchSpace::PTC2, PYBIND11_MODULE, Brush::Util::Rnd::random_choice, Brush::Util::Rnd::random_choice, Brush::Util::Rnd::random_choice, Brush::RandomDequeue, Brush::Data::read_csv, Brush::Data::TimeSeries< T >::reduce, Brush::Util::reorder, Brush::Util::ReplaceString, Brush::Util::ReplaceStringInPlace, Brush::Fitness::repr, Brush::Util::reverse_map, Brush::Util::Rnd::rnd_dbl, Brush::Util::Rnd::rnd_flt, Brush::Util::Rnd::rnd_int, Brush::Util::rtrim, Brush::Engine< T >::run, Brush::Pop::Archive< T >::sameFitComplexity, Brush::Pop::Archive< T >::sameObjectives, Brush::SearchSpace::sample_op, Brush::SearchSpace::sample_op, Brush::SearchSpace::sample_op_with_arg, Brush::SearchSpace::sample_subtree, Brush::SearchSpace::sample_terminal, Brush::SearchSpace::sample_terminal, Brush::Pop::Population< T >::save, Brush::Eval::Scorer< P >::score, Brush::Eval::Scorer< P >::score, Brush::Eval::Scorer< P >::score, Brush::Sel::Lexicase< T >::select, Brush::Sel::NSGA2< T >::select, Brush::Sel::Selection< T >::select, Brush::Util::Rnd::select_randomly, Brush::Util::Rnd::select_randomly, Brush::Parameters::set_batch_size, Brush::Data::Dataset::set_batch_size, Brush::Parameters::set_classification, Brush::Fitness::set_complexity, Brush::Fitness::set_crowding_dist, Brush::Parameters::set_current_gen, Brush::Parameters::set_cx_prob, Brush::Fitness::set_dcounter, Brush::Fitness::set_depth, Brush::Fitness::set_dominated, Brush::Node::set_feature, Brush::Parameters::set_feature_names, Brush::Pop::Individual< T >::set_fitness, Brush::Parameters::set_functions, Brush::Pop::Individual< T >::set_id, Brush::Engine< T >::set_is_fitted, Brush::Parameters::set_load_population, Brush::Util::Logger::set_log_level, Brush::Parameters::set_logfile, Brush::Fitness::set_loss, Brush::Fitness::set_loss_v, Brush::Parameters::set_max_depth, Brush::Parameters::set_max_gens, Brush::Parameters::set_max_size, Brush::Parameters::set_max_stall, Brush::Parameters::set_max_time, Brush::Parameters::set_mig_prob, Brush::Parameters::set_mutation_probs, Brush::Parameters::set_n_classes, Brush::Parameters::set_n_jobs, Brush::Parameters::set_num_islands, Brush::Parameters::set_objectives, Brush::Pop::Individual< T >::set_objectives, Brush::Sel::Selection< T >::set_operator, Brush::Engine< T >::set_params, Brush::Pop::Individual< T >::set_parents, Brush::Pop::Individual< T >::set_parents, Brush::Parameters::set_pop_size, Brush::Node::set_prob_change, Brush::Parameters::set_random_state, Brush::Parameters::set_save_population, Brush::Parameters::set_scorer_, Brush::Program< PType >::set_search_space, Brush::Util::Rnd::set_seed, Brush::Parameters::set_sel, Brush::Parameters::set_shuffle_split, Brush::Fitness::set_size, Brush::Parameters::set_surv, Brush::Parameters::set_use_arch, Brush::Parameters::set_val_from_arch, Brush::Parameters::set_validation_size, Brush::Fitness::set_values, Brush::Parameters::set_verbosity, Brush::Program< PType >::set_weights, Brush::Fitness::set_weights, Brush::Util::Rnd::shuffle, Brush::Util::Rnd::shuffled_index, Brush::Data::TimeSeries< T >::sin, Brush::Data::TimeSeries< T >::sinh, Brush::Program< PType >::size, Brush::Program< PType >::size_at, Brush::Util::skew, Brush::Util::slice, Brush::Util::slope, Brush::Function< NodeType::Softmax >::softmax, Brush::Util::softmax, Brush::Pop::Archive< T >::sortComplexity, Brush::Pop::Population< T >::sorted_front, Brush::Pop::Archive< T >::sortObj1, Brush::Util::split, Brush::Data::Dataset::split, Brush::Data::TimeSeries< T >::sqrt, Brush::Data::TimeSeries< T >::sqrtabs, Brush::Data::TimeSeries< T >::square, Brush::Data::StateType, Brush::Data::TimeSeries< T >::std, Split::stitch, Brush::Data::TimeSeries< T >::sum, Brush::Sel::NSGA2< T >::survive, Brush::Sel::Selection< T >::survive, Brush::Data::TimeSeries< T >::tan, Brush::Data::TimeSeries< T >::tanh, Split::threshold_mask, Brush::Split::threshold_mask< State >, Brush::to_json, Brush::Pop::to_json, Brush::to_json, Brush::to_json, nlohmann::adl_serializer< std::shared_ptr< T > >::to_json, to_json, Brush::Fitness::toString, Brush::Sel::NSGA2< T >::tournament, Brush::Data::TimeSeries< T >::transform, Brush::Util::trim, Brush::Util::unique, Brush::Util::unique, Brush::Util::unique, Brush::Util::unique, Brush::Util::unique_insert, Brush::Util::Log_Stats::update, Brush::Pop::Archive< T >::update, Brush::WeightOptimizer::update, Brush::Pop::Population< T >::update, Brush::Engine< T >::update_best, Brush::Eval::Evaluation< T >::update_fitness, Brush::Program< PType >::update_weights, Brush::Util::variance, Brush::Var::Variation< T >::vary, Brush::Util::vectorToTuple, Brush::Util::vectorToTupleHelper.